/** @file dnp3_config.h 
 *
 * @brief
 * Device configuration header file
 *
 * @details
 * Contains macro definitions for device parametrization (number of points, array sizes, enabled features etc).
 *
 * @copyright
 * Copyright 2019-2020 JPEmbedded.
 * This software is protected Intellectual Property and may only be used
 * according to the licence agreement.
 *
 * @author Jan Mazan
 */
 
#if !defined(_DNP3_CONFIG_H)
#define _DNP3_CONFIG_H

/** Version of DNP3 library sources */
#define CFG_VERSION                       "1.1.5"

/** Maximum number of Outstation instances */
#define CFG_OUTSTATION_COUNT              4

/** Maximum number of Outstation instances */
#define CFG_MASTER_COUNT                  4

/** Number of binary points */
#define CFG_BIN_PT_CNT                     1000

/** Number of events generated by binary points */
#define CFG_BIN_EV_CNT                     8

/** Number of double  binary points */
#define CFG_DBIN_PT_CNT                    8

/** Number of events generated by double-binary points */
#define CFG_DBIN_EV_CNT                    8

/** Number of binary output points */
#define CFG_BINOUT_PT_CNT                  16

/** Number of events generated by binary outputs */
#define CFG_BINOUT_EV_CNT                  32

/** Number of double binary points */
#define CFG_COUNT_PT_CNT                   16

/** Number of events generated by double-binary points */
#define CFG_COUNT_EV_CNT                   16

/** Number of analog points */
#define CFG_ANALOG_PT_CNT                  8

/** Number of events generated by analog points */
#define CFG_ANALOG_EV_CNT                  8

/** Number of analog points */
#define CFG_ANALOGOUT_PT_CNT               8

/** Number of events generated by analog points */
#define CFG_ANALOGOUT_EV_CNT               8

/** Enable frozen values */
#define CFG_ENABLE_FREEZ                   1

/** Enable handling of unsolicited messaging */
#define CFG_UNSOLICITED_ENABLED            1

/** Enable control operations */
#define CFG_CTRL_ENABLED                   1

#if CFG_CTRL_ENABLED
#define CFG_OPER_CNT                       4

#define CFG_CONTROL_TIMER                  3000
#else 
#define CFG_OPER_CNT                       0
#endif

/** Maximum number of simultaneous connections to outstation instance */
#define CFG_MAX_OS_CONNECTIONS             2

/** Maximum number of simultaneous connections per DNP3 process */
#define CFG_MAX_CONNECTIONS                (CFG_MAX_OS_CONNECTIONS * CFG_OUTSTATION_COUNT) + CFG_MASTER_COUNT

/** Maximum value of index of static point or event */
#define CFG_MAX_INDEX_VAL                  999

/** Number of group 0 configuration points */
#define CFG_GROUP0_MAX_ELEM                255

/** Size of 'other' request buffering queue  */
#define CFG_REQ_CNT                        16

/** Size of read requests buffering in queue  */
#define CFG_RD_REQ_CNT                   8

/** Size of events buffering queue  */
#define CFG_EV_REQ_CNT                     32

/** Number of unsolicitedevents buffering queue  */
#define CFG_UNSOL_REQ_CNT                  16

/** Maximum size of the response PDU */
#define CFG_MAX_RESP_SIZE                  1024

/** Number of retransmissions of unsolicited messages */
#define CFG_RETRANSMIT_CNT                 4

/** Retransmission time of unsolicited messages */
#define CFG_RETRANSMIT_TIMER               2000

/** Retransmission of master requests */
#define CFG_REQ_RETRY_CNT                  2

/** Timeout for client keep alive messages - seto to 0 to disable keep alive sending */
#define CFG_CLI_KEEP_ALIVE                 10000

/** Timeout for master waiting on outstation response or unsolicited message */
#define CFG_MASTER_RX_TOUT                 0

/** Name of the ethernet interface to be used */
//#define CFG_NETWORK_INTERFACE                 "eth0"
#define CFG_NETWORK_INTERFACE                 "{93B6B8AB-FC74-4E00-9127-064343ADBD27}"

#define CFG_SECURE_AUTH                     0

#ifndef NULL
#ifdef __cplusplus
#define NULL 0
#else
#define NULL                 ((void*)0)
#endif
#endif

#include "Basetypes.h"
#include <stdio.h>

/** Macro definition used to avoid compiler warnings when something is not used */
#define UNUSEDARG(a)            (void)(a)

/** Defines level of logs generated by hardware abstraction layer (LOG_LEVEL_INFO, LOG_LEVEL_ERR, LOG_LEVEL_ALL)*/
extern const int8u CFG_LOG_HAL;
extern unsigned short _dbgFlag;

#endif
