#define S_FUNCTION_LEVEL 2
#undef S_FUNCTION_NAME
#define S_FUNCTION_NAME sg_IO601_write_s_3

#include <stddef.h>
#include <stdlib.h>
#include <stdbool.h>
#include "simstruc.h"

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#endif

#ifndef MATLAB_MEX_FILE
#include <windows.h>
#include "xpcimports.h"
#include "ioext_xpcimport.h"
#endif

#define DEVNAME                "Speedgoat IO601"
#define VENDORID               (0x10b5)
#define DEVICEID               (0x9030)
#define SUBVENDORID            (0x10b5)
#define SUBDEVICEID            (0x2977)

#define NUMBER_OF_ARGS         (9)

#define MODULEID_ARG           ssGetSFcnParam(S,0)
#define STATUS_ARG             ssGetSFcnParam(S,1)
#define INPORT_DATA_TYPE_ARG   ssGetSFcnParam(S,2)
#define MAXMSG_ARG             ssGetSFcnParam(S,3)
#define PORT_ARG               ssGetSFcnParam(S,4)
#define CAN_INIT_ARG           ssGetSFcnParam(S,5)
#define CAN_TERM_ARG           ssGetSFcnParam(S,6)
#define SAMP_TIME_ARG          ssGetSFcnParam(S,7)
#define SLOT_ARG               ssGetSFcnParam(S,8)

#define NO_I_WORKS             (4)
#define BASE_ADDR_I_IND        (0)
#define BASE_ADDR0_I_IND       (1)
#define POSBUFFER1             (2)
#define POSBUFFER2             (3)

#define NO_R_WORKS             (0)

#define NO_P_WORKS             (0)

static char_T msg[256];

extern uint8_T ptrWritePointer1[];
extern uint8_T ptrWritePointer2[];

/* CAN message is the datatype as used by Matlab. */
typedef struct
{
    uint8_T Extended;
    uint8_T Length;
    uint8_T Remote;
    uint8_T Error;
    int32_T ID;
    double Timestamp;
    uint8_T Data[8];    
}canMsg;

/* CAN entry is the CAN message as stored in the DPRAM of IO601. 
 * 
 * Extremely important: if a struct is non aligned on 32 bits, some gap
 * will be autogenerated by the compiler.
 *
 */


typedef struct QUEUEENTRY
{
    uint32_T word[5];
}QUEUEENTRY;




#ifndef MATLAB_MEX_FILE


/**************************************************************************
 * This function returns the identifier given in parameter, coded in 
 * Motorola format.
 *
 * Motorola uses a Big Endian format, this means that:
 *
 * In a word (4 bytes):
 * 
 * Intel[0] = Motorola[3]
 * Intel[1] = Motorola[2]
 * Intel[2] = Motorola[1]
 * Intel[3] = Motorola[0] 
 *
 * Important, if the data is not complete (size != 32), we have to align
 * it.
 *************************************************************************/
static uint32_T ConvertIdentifier(uint32_T id, uint32_T nBits)
{
    uint32_T motorola;
    
    motorola = (id << (32 - nBits));
    motorola = (uint32_T)(((motorola & 0x000000FF) << 24) + 
                          ((motorola & 0x0000FF00) << 8) +
                          ((motorola & 0x00FF0000) >> 8) +
                          ((motorola & 0xFF000000) >> 24));
    return motorola;
}

/**************************************************************************
 *               
 * a CAN entry contains up to 20 elements, which are:
 *|---------------------------------------|
 *|  n    |   standard    |    extended   |
 *|---------------------------------------|
 *|  0    |   status      |  status       |
 *|  1    |   count       |  count        | 
 *|  2    |   TimeStamp   |  TimeStamp    |
 *|  3    |   TimeStamp   |  TimeStamp    |
 *|  4    |   TimeStamp   |  TimeStamp    |
 *|  5    |   TimeStamp   |  TimeStamp    |
 *|  6    |   Type        |  Type         |
 *|  7    |   Information |  Information  |
 *|  8    |   Identifier  |  Identifier   |
 *|  9    |   Identifier  |  Identifier   |
 *| 10    |   Data        |  Identifier   |
 *| 11    |   Data        |  Identifier   |
 *| 12    |   Data        |  Data         |
 *| 13    |   Data        |  Data         |
 *| 14    |   Data        |  Data         |
 *| 15    |   Data        |  Data         |
 *| 16    |   Data        |  Data         |
 *| 17    |   Data        |  Data         |
 *| 18    |   Reserved    |  Data         |
 *| 19    |   Reserved    |  Data         |
 *|---------------------------------------/
 *
 * TimeStamp is not relevant. Because the MC generates it.
 * Type is always 0 for sending
 * 
 * Information is:
 * Bits 0-3: DLC (up to 8 bytes).
 * Bits 4-5: reserved
 * Bits 6  : remote frame (0: data frame, 1: remote frame)
 * Bits 7  : frame format (0: standard, 1: extended) 
 *     
 *************************************************************************/
static uint8_T PrepareQueueEntry(canMsg message, QUEUEENTRY *pQueue)
{
    uint8_T status, nBytes, information; 
    uint16_T standardID;
    uint32_T extendedID;
    
    status = pQueue->word[0] & 0xFF;
    if (status == 0) // is the queue free to be written?
    {
        if (message.Extended)
        {
            status = 1;
            nBytes = 10 + message.Length;
            information = message.Length | (message.Remote << 6) | (message.Extended << 7);
            extendedID = ConvertIdentifier(message.ID, 29);
            
            pQueue->word[1] = (information << 24);
            pQueue->word[2] = (extendedID);
            pQueue->word[3] = (message.Data[3] << 24) | (message.Data[2] << 16) | (message.Data[1] << 8) | message.Data[0]; 
            pQueue->word[4] = (message.Data[7] << 24) | (message.Data[6] << 16) | (message.Data[5] << 8) | message.Data[4]; 
            pQueue->word[0] = (nBytes << 8) | (status);
        }
        else
        {
            status = 1;
            nBytes = 8 + message.Length;
            information = (message.Length) | (message.Remote << 6) | (message.Extended << 7);
            standardID = ConvertIdentifier(message.ID, 11);
            
            pQueue->word[1] = (information << 24);
            pQueue->word[2] = (message.Data[1] << 24) | (message.Data[0] << 16) | standardID;
            pQueue->word[3] = (message.Data[5] << 24) | (message.Data[4] << 16) | (message.Data[3] << 8) | message.Data[2];
            pQueue->word[4] = (message.Data[7] << 8) | message.Data[6];  
            pQueue->word[0] = (nBytes << 8) | (status);
        }
        return 1;
    }
    else
    {
        return 0;
    }                
}

static int8_T SendCANMessage(SimStruct *S, int32_T port, canMsg message)
{  
    
    /*
     * Variable declaration:
     */
    int32_T frc, position;
    QUEUEENTRY *pQueue;
    uint32_T base;
        
    /*
     * Initialization
     */
    base = ssGetIWorkValue(S, BASE_ADDR_I_IND);
    frc = 0;
    
    
    /* 1. We determine if the frame can be sent or no. */   
    if (port != 1 && port != 2) 
    {
        frc = -10;
    }

    switch (message.Extended)
    {    
        case 0:
            if (message.ID > 2047)
            {
                frc = -12; //in standard, identifer cannot be larger than 2^11 - 1
            }
            break;

        case 1:
            if (message.ID > 536870911)
            {
                frc = -13; //in extended, identifer cannot be larger than 2^19 - 1
            }
            break;
            
        default:
            frc = -11; // not a correct frame format.
            break;
    }
    
    if (message.Length > 8)
    {
        frc = -14;
    }
    
    /* when the frames passed all the tests, we send it. A negative ident
       is a "don't send this message" flag. */
    if (frc == 0 && message.ID >= 0)
    {   

        if (port == 1)
        {
            
            position = ptrWritePointer1[(uint32_T)mxGetPr(MODULEID_ARG)[0] - 1]; // get the current buffer position for port 1.
            //printf("position: %d\n", position);
            
            //printf("0x%X\n", base + 0x50 + position * sizeof(QUEUEENTRY));
            pQueue = (QUEUEENTRY *)(base + 0x50 + position * sizeof(QUEUEENTRY));
        }
        else
        {
            position = ptrWritePointer2[(uint32_T)mxGetPr(MODULEID_ARG)[0] - 1]; // get the current buffer position for port 2.
            pQueue = (QUEUEENTRY *)(base + 0x438 + position * sizeof(QUEUEENTRY));  
        }
        
        /* now the CAN message has to be placed in the queueentry. */
        if (PrepareQueueEntry(message, pQueue))
        {

            /* increment the position in the DPRAM buffer (0 to 49)*/
            position = (position == 49)? 0 : ++position;

            /* save the position */
            if (port == 1)
            {
                ptrWritePointer1[(uint32_T)mxGetPr(MODULEID_ARG)[0] - 1] = position;
            }
            else
            {
                ptrWritePointer2[(uint32_T)mxGetPr(MODULEID_ARG)[0] - 1] = position;
            }
        }
        else
        {
            frc = -1; /* the queue entry wasn't free. */
        }
    
    }    
                
    return frc;
    
}
#endif


static void mdlInitializeSizes(SimStruct *S)
{

    int_T i;

    ssSetNumSFcnParams(S, NUMBER_OF_ARGS);
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        sprintf(msg, "Wrong number of input arguments passed.\n%d arguments are expected\n", NUMBER_OF_ARGS);
        ssSetErrorStatus(S,msg);
        return;
    }

    ssSetNumContStates(S, 0);
    ssSetNumDiscStates(S, 0);

	// inport datatype can be either a matrix (m*6 or m*5)
	if ((int_T)mxGetPr(INPORT_DATA_TYPE_ARG)[0] == 1)
    {
        ssSetNumInputPorts(S, 1);
        ssSetInputPortDirectFeedThrough(S, 0, 1);
        ssSetInputPortRequiredContiguous(S, 0, 1);  
		if (!ssSetInputPortMatrixDimensions(S, 0, DYNAMICALLY_SIZED, DYNAMICALLY_SIZED)) 
            return;

	}
	else
    { //or CAN_MESSAGE

        ssSetNumInputPorts(S, 2);
        
        ssSetInputPortWidth(S, 0, (uint32_T)mxGetPr(MAXMSG_ARG)[0]);
        ssSetInputPortDirectFeedThrough(S, 0, 1);
        ssSetInputPortRequiredContiguous(S, 0, 1);  
        
        ssSetInputPortWidth(S, 1, 1);
        ssSetInputPortDirectFeedThrough(S, 1, 1);
        ssSetInputPortRequiredContiguous(S, 1, 1); 
        
        
#ifdef MATLAB_MEX_FILE   
        {
            int_T canMsgT, status;
            DTypeId id;
            canMsg tmp;
        
            id = ssRegisterDataType(S, "CAN_MESSAGE");
            if (id == INVALID_DTYPE_ID) 
                return;

            status = ssSetDataTypeSize(S, id, sizeof(tmp));  
            ssSetInputPortDataType(S, 0, id); 
        }
#endif 		
	}

    if ((int_T)mxGetPr(STATUS_ARG)[0] && (int_T)mxGetPr(INPORT_DATA_TYPE_ARG)[0] == 1)
    {
        ssSetNumOutputPorts(S, 1);
        ssSetOutputPortWidth(S, 0, DYNAMICALLY_SIZED);
    } 
    else if ((int_T)mxGetPr(STATUS_ARG)[0] && (int_T)mxGetPr(INPORT_DATA_TYPE_ARG)[0] == 2)
    {
        ssSetNumOutputPorts(S, 1);
        ssSetOutputPortWidth(S, 0, (uint32_T)mxGetPr(MAXMSG_ARG)[0]);
    }
    else
    {
        ssSetNumOutputPorts(S, 0);
    }


    ssSetNumSampleTimes(S, 1);

    ssSetNumRWork(S, NO_R_WORKS);
    ssSetNumIWork(S, NO_I_WORKS);
    ssSetNumPWork(S, 0);

    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    for (i = 0; i < NUMBER_OF_ARGS; i++)
    {
        ssSetSFcnParamNotTunable(S, i);
    }

    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);

}

#define MDL_SET_INPUT_PORT_DIMENSION_INFO
static void mdlSetInputPortDimensionInfo(SimStruct *S, int portIndex, const DimsInfo_T *dimsInfo)
{

    /* Configure the inputs. */
	if( (int_T)mxGetPr(INPORT_DATA_TYPE_ARG)[0] == 1)
    {
		if (dimsInfo->dims[1] != 5 && dimsInfo->dims[1] != 6) 
        {
			sprintf(msg,"Input must be a m*5 or a m*6  matrix");
			ssSetErrorStatus(S,msg);
			return;
		}
		if (!ssSetInputPortDimensionInfo(S, portIndex, dimsInfo)) 
            return;
        
        if ((int_T)mxGetPr(STATUS_ARG)[0]) 
        {
            if (!ssSetOutputPortVectorDimension(S, 0, dimsInfo->dims[0])) return;
        }
    }
    else
    {        
        if (!ssSetInputPortDimensionInfo(S, portIndex, dimsInfo)) return;
            
        /* Configure the outputs. */
        if ((int_T)mxGetPr(STATUS_ARG)[0]) 
        {
            if (!ssSetOutputPortVectorDimension(S, 0, dimsInfo->dims[0])) 
                return;
        }
    }
    


}

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
static void mdlSetOutputPortDimensionInfo(SimStruct *S, int portIndex, const DimsInfo_T *dimsInfo)
{
    if (!ssSetOutputPortDimensionInfo(S, portIndex, dimsInfo)) return;
}

#define MDL_SET_DEFAULT_PORT_DIMENSION_INFO
static void mdlSetDefaultPortDimensionInfo(SimStruct *S)
{
	if( (int_T)mxGetPr(INPORT_DATA_TYPE_ARG)[0] == 1)
    {
		if (!ssSetInputPortMatrixDimensions(S, 0, 1, 5)) 
            return;
        
		if ((int_T)mxGetPr(STATUS_ARG)[0]) 
        {
			if (!ssSetOutputPortVectorDimension(S, 0, 1)) 
                return;
		}
	}
}


static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, mxGetPr(SAMP_TIME_ARG)[0]);
    if (mxGetN((SAMP_TIME_ARG))==1) {
        ssSetOffsetTime(S, 0, 0.0);
    } else {
        ssSetOffsetTime(S, 0, mxGetPr(SAMP_TIME_ARG)[1]);
    }

}

#define MDL_START
static void mdlStart(SimStruct *S)
{
#ifndef MATLAB_MEX_FILE
    xpcPCIDevice pciinfo;
    int32_T  bus, slot;
    canMsg message;
    int32_T frc;
    int32_T i, j, m;
    int_T port, start;
    uint8_T data[8];
    uint8_T length;
    volatile uint32_T *ioaddress0;
    uint32_T regtemp;
    uint32_T nbOccurences, temp;
    
    /* board detection */
    if (mxGetN(SLOT_ARG) == 1)
    {
        if ((int32_T)mxGetPr(SLOT_ARG)[0] == -1)
        {
            nbOccurences = 0;
              
            // browse bus and slot until deviceID and vendorID have been found
            for (bus = 0; bus < 256; bus++)
            {
                for (slot = 0; slot < 32; slot++)
                {
                    xpcOutpDW(0xCF8, 0x80000000 | (bus << 16) | (slot << 11));
                    temp = xpcInpDW(0xCFC);

                    if ((temp & 0xFFFF) == VENDORID && ((temp >> 16)& 0xFFFF) == DEVICEID)
                    {
                        
                        nbOccurences += 1;
                        if (nbOccurences == ((uint32_T)mxGetPr(MODULEID_ARG)[0]))     
                        {
                            break;
                        }
                    }

                }

                if (nbOccurences == ((uint32_T)mxGetPr(MODULEID_ARG)[0]))
                {
                    break;
                }              
            };
            
            if (nbOccurences < ((uint32_T)mxGetPr(MODULEID_ARG)[0]))     
            {
                sprintf(msg, "%s: Failed to find I/O Module with ID %d", DEVNAME, (uint32_T)mxGetPr(MODULEID_ARG)[0]);
                ssSetErrorStatus(S, msg);
                return;
            }
        }
        else
        {
            bus = 0;
            slot = (int_T)mxGetPr(SLOT_ARG)[0];
        }
    }
    else
    {
        bus = (int_T)mxGetPr(SLOT_ARG)[0];
        slot = (int_T)mxGetPr(SLOT_ARG)[1];
    }

    /* look for the PCI-Device */
    if (xpcGetPCIDeviceInfo((uint16_T)VENDORID, (uint16_T)DEVICEID, (uint16_T)SUBVENDORID, (uint16_T)SUBDEVICEID, bus, slot, &pciinfo))
    {
        sprintf(msg, "%s (bus %d, slot %d): board not present", DEVNAME, bus, slot);
        ssSetErrorStatus(S,msg);
        return;
    }

    pciinfo.VirtAddress[2] = (unsigned long)xpcReserveMemoryRegion((void *)pciinfo.BaseAddress[2], pciinfo.Length[2], XPC_RT_PG_USERREADWRITE);    
    pciinfo.VirtAddress[0] = (unsigned long)xpcReserveMemoryRegion((void *)pciinfo.BaseAddress[0], pciinfo.Length[0], XPC_RT_PG_USERREADWRITE); 
    ssSetIWorkValue(S, BASE_ADDR_I_IND, pciinfo.VirtAddress[2]);
    ssSetIWorkValue(S, BASE_ADDR0_I_IND, pciinfo.VirtAddress[0]);
    ssSetIWorkValue(S, POSBUFFER1, 0);
    ssSetIWorkValue(S, POSBUFFER2, 0);
    
    ioaddress0 = (void *)(pciinfo.VirtAddress[0]);  
    
    if (!xpceIsModelInit())
    {
        start = 1;
        // at +tg, we eventually send an init frame.
        if ((uint32_T)mxGetN(CAN_INIT_ARG))
        {
            m = (uint_T)mxGetPr(CAN_INIT_ARG)[0]; 
            for (i = 0; i < m; i++)
            {                
                port = (int_T)mxGetPr(CAN_INIT_ARG)[start];
                length = (int_T)mxGetPr(CAN_INIT_ARG)[start+3];
        
                for (j = 0; j < length; j++) {
                    data[j] = (uint8_T)mxGetPr(CAN_INIT_ARG)[start + 4 + j];
                }
                
                message.Data[0] = data[0]; 
                message.Data[1] = data[1]; 
                message.Data[2] = data[2]; 
                message.Data[3] = data[3]; 
                message.Data[4] = data[4]; 
                message.Data[5] = data[5]; 
                message.Data[6] = data[6]; 
                message.Data[7] = data[7];      
                message.Length = length;
                message.Extended = (int_T)mxGetPr(CAN_INIT_ARG)[start+1];
                message.ID = (uint32_T)mxGetPr(CAN_INIT_ARG)[start+2];
                message.Remote = 0;  
                
                frc = SendCANMessage(S, port, message);
                if (frc == 0)
                {
                    regtemp = ioaddress0[0x15];
                    ioaddress0[0x15] = regtemp & ~(1 << 2);
                    ioaddress0[0x15] = regtemp | (1 << 2);
                } 
                // wait for the required time.
                rl32eWaitDouble(mxGetPr(CAN_INIT_ARG)[start + 12]);
                start += 13;
            
            }  
        }

    }
           
#endif
}

static void mdlOutputs(SimStruct *S, int_T tid)
{    
#ifndef MATLAB_MEX_FILE

    int32_T frc, port, control, ID;
    real_T *u, *y;
    real_T data;
    uint8_T *pData;
    uint8_T doMC;
    canMsg *u1;
    canMsg message;
    int_T *dims;
    uint32_T i, m, nMessages, count;
    volatile uint32_T *ioaddress0;
    uint32_T regtemp;   
    uint8_T extended, length;

    uint32_T base0 = ssGetIWorkValue(S, BASE_ADDR0_I_IND);
    ioaddress0 = (void *)base0;    
    
    /* Get message format and sizes... */
    if ((int_T)mxGetPr(INPORT_DATA_TYPE_ARG)[0] == 2) // input is of type CAN_MESSAGE
    {           
        u1 = (canMsg *)ssGetInputPortSignal(S, 0);  
        u  = (real_T *)ssGetInputPortSignal(S, 1); 
        count = (uint32_T)u[0];
        nMessages = (uint32_T)mxGetPr(MAXMSG_ARG)[0];
        if (count < nMessages) 
        {            
            nMessages = count;   
        }        
    }
    else
    {
        /* determine the matrix format and its sizes. */        
        dims = ssGetInputPortDimensions(S, 0);
        m = dims[1];
        nMessages = dims[0];     
        u = (real_T *)ssGetInputPortSignal(S, 0);   
    }
    
    doMC = 0;
    for (i = 0; i < nMessages; i++)
    {    

        if ((int_T)mxGetPr(INPORT_DATA_TYPE_ARG)[0] == 2)
        {
             
            message = u1[i];
            port = (int32_T)mxGetPr(PORT_ARG)[0];
            control = 1;
        }
        else /* the frame is extracted from the Matrix and stored in the CAN message. */
        {
            
            /* m is the number of column. Input format is:
             * m0: ID
             * m1: port             
             * m2: type
             * m3: frame size
             * m4: data (double: 64 bits)
             * m5: control (when 0, the frame is not sent)
             */         
            ID = (int32_T)u[i + nMessages * 0];            
            port = (int32_T)u[i + nMessages * 1];            
            extended = (uint8_T)u[i + nMessages * 2];            
            length = (uint8_T)u[i + nMessages * 3];                     
            
            data = u[i + nMessages * 4];
            pData = (uint8_T*)&data;
            
            message.Data[0] = pData[0]; 
            message.Data[1] = pData[1]; 
            message.Data[2] = pData[2]; 
            message.Data[3] = pData[3]; 
            message.Data[4] = pData[4]; 
            message.Data[5] = pData[5]; 
            message.Data[6] = pData[6]; 
            message.Data[7] = pData[7];      
            message.Length = length;
            message.Extended = extended;
            message.ID = ID;
            message.Remote = 0;  
            
            if (m == 6)
            {  
                control = (int32_T)u[i + nMessages * 5];
            } 
            else
            {
                control = 1;
            }
 
        }   
        

        if (control)
        {
            
            frc = SendCANMessage(S, port, message); 
            
            if (frc == 0)
            {
                regtemp = ioaddress0[0x15];
                ioaddress0[0x15] = regtemp & ~(1 << 2);
                ioaddress0[0x15] = regtemp | (1 << 2);
            }
            
            if ((int_T)mxGetPr(STATUS_ARG)[0])
            {
                y = (real_T *)ssGetOutputPortSignal(S, 0);
                y[i] = (real_T)frc;
            }              
        }  
    }
    
    if (doMC)
    {               
        // generate MC interrupt
        regtemp = ioaddress0[0x15];
        ioaddress0[0x15] = regtemp & ~(1 << 2);
        ioaddress0[0x15] = regtemp | (1 << 2);
    }
    
#endif
}

static void mdlTerminate(SimStruct *S)
{
#ifndef  MATLAB_MEX_FILE 
    
    canMsg message;
    int32_T frc;
    int32_T i, j, m;
    int_T port, start;
    uint8_T data[8];
    uint8_T length;
    volatile uint32_T *ioaddress0;
    uint32_T regtemp;    
    uint32_T base0 = ssGetIWorkValue(S, BASE_ADDR0_I_IND);
    ioaddress0 = (void *)base0;        
    
    if (!xpceIsModelInit())
    {
        // at +tg, we eventually send an init frame.
        
        if ((uint32_T)mxGetN(CAN_TERM_ARG))
        {
            m = (uint32_T)mxGetPr(CAN_TERM_ARG)[0]; 
            start = 1;
            for (i = 0; i < m; i++)
            {
                port = (int_T)mxGetPr(CAN_TERM_ARG)[start];
                length = (int_T)mxGetPr(CAN_TERM_ARG)[start+3];
                        
                for (j = 0; j < length; j++) {
                    data[j] = (uint8_T)mxGetPr(CAN_TERM_ARG)[start + 4 + j];
                }
                
                message.Data[0] = data[0]; 
                message.Data[1] = data[1]; 
                message.Data[2] = data[2]; 
                message.Data[3] = data[3]; 
                message.Data[4] = data[4]; 
                message.Data[5] = data[5]; 
                message.Data[6] = data[6]; 
                message.Data[7] = data[7];      
                message.Length = length;
                message.Extended = (int_T)mxGetPr(CAN_TERM_ARG)[start+1];
                message.ID = (uint32_T)mxGetPr(CAN_TERM_ARG)[start+2];
                message.Remote = 0;  
                
                frc = SendCANMessage(S, port, message); 
                if (frc == 0)
                {
                    regtemp = ioaddress0[0x15];
                    ioaddress0[0x15] = regtemp & ~(1 << 2);
                    ioaddress0[0x15] = regtemp | (1 << 2);
                } 
                
                // wait for the required time.
                xpcBusyWait(mxGetPr(CAN_TERM_ARG)[start + 12]);

                start += 13;
            
            }
        }
    }
#endif
}

#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif
