function context = initialContext()
%INITIALCONTEXT State retained between 5 ms virtual-VCU samples.
context = struct('state',uint8(0),'ticks',uint32(0), ...
    'appsError',false,'resetSent',false, ...
    'can',struct('seenMask',uint16(0),'lastId',uint32(0), ...
    'valid',false,'inverterReady',false,'inverterFault',false, ...
    'dcLink12V',0,'dcLink34V',0,'systemValid',false, ...
    'wheelSpeedRadS',zeros(1,4),'wheelSpeedValid',false(1,4)));
end
