function context = initialContext()
%INITIALCONTEXT State retained between 1 ms virtual-VCU samples.
context = struct('state',uint8(0),'ticks',uint32(0), ...
    'can',struct('seenMask',uint16(0),'lastId',uint32(0), ...
    'valid',false,'inverterReady',false,'inverterFault',false, ...
    'dcLink12V',0,'dcLink34V',0));
end
