function build_io614_can_visibility_test(force)
%BUILD_IO614_CAN_VISIBILITY_TEST Generate the R2024b IO614 CAN visibility test.
%
% Implements tests/io614_can_visibility_test_plan.md: a minimal Speedgoat
% IO614 CAN channel 1 transmit/receive smoke test with every field the
% plan requires exposed as a named, instrument-visible signal. CAN IDs
% and the raw-mode design follow inverter_hil/inverter_hil_plan.md
% section 3.4/4/6.1; this test does not claim payload semantics, only
% transport visibility (ID, DLC, payload bytes, counters, CAN status).

if nargin < 1
    force = false;
end
if ~(islogical(force) && isscalar(force))
    error('io614canviz:InvalidBuildOption', 'force must be a logical scalar.');
end
if ~strcmp(version('-release'), '2024b')
    error('io614canviz:WrongRelease', ...
        'This test must be built with MATLAB/Simulink R2024b, not %s.', ...
        version('-release'));
end

root = fileparts(mfilename('fullpath'));
model = 'io614_can_visibility_test_R2024b';
modelPath = fullfile(root, [model '.slx']);
dictionaryPath = fullfile(root, [model '.sldd']);

if bdIsLoaded(model)
    close_system(model, 0);
end
prepareOutput(modelPath, force);
prepareOutput(dictionaryPath, force);

createDictionary(dictionaryPath);

new_system(model);
cleanupModel = onCleanup(@() closeIfLoaded(model));
set_param(model, ...
    'DataDictionary', [model '.sldd'], ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.001', ...
    'StartTime', '0.0', ...
    'StopTime', 'inf', ...
    'SystemTargetFile', 'speedgoat.tlc', ...
    'DefaultParameterBehavior', 'Tunable', ...
    'SignalLogging', 'on');

load_system('speedgoatlib_IO614');

addCanSetup(model);
addClock(model);
addReceivePath(model);
addTransmitPath(model);
addDiagnostics(model);
addAnnotation(model, ...
    ['IO614 CAN VISIBILITY TEST - R2024b\n' ...
     'CAN1, High-Speed, 1 Mbit/s, standard 11-bit IDs, raw mode\n' ...
     'tx_enable defaults FALSE. Verify termination before connecting.\n' ...
     'See io614_can_visibility_test_plan.md and README.md for procedure.'], ...
    [40 20 760 92], 'yellow');

save_system(model, modelPath, 'SaveModelWorkspace', false);
set_param(model, 'SimulationCommand', 'update');
save_system(model, modelPath);
fprintf('Created %s and %s with MATLAB %s.\n', ...
    modelPath, dictionaryPath, version('-release'));
end

function prepareOutput(path, force)
if isfile(path)
    if ~force
        error('io614canviz:ArtifactExists', ...
            'Artifact exists; call build_io614_can_visibility_test(true): %s', path);
    end
    delete(path);
end
end

function createDictionary(path)
dictionary = Simulink.data.dictionary.create(path);
cleanupDict = onCleanup(@() close(dictionary));
section = getSection(dictionary, 'Design Data');

addEntry(section, 'tx_enable', parameter(false, false, true));
addEntry(section, 'tx_id', parameter(uint32(hex2dec('383')), ...
    uint32(0), uint32(2047)));
addEntry(section, 'tx_dlc', parameter(uint8(8), uint8(0), uint8(8)));
addEntry(section, 'tx_payload_u8', parameter( ...
    uint8([1 2 3 4 5 6 7 8]), uint8(zeros(1, 8)), uint8(255 * ones(1, 8))));
addEntry(section, 'tx_period_ms', parameter(100, 1, 60000));

addEntry(section, 'io614_can_visibility_vcu_control_ids', uint32(hex2dec( ...
    {'186', '196', '1A6', '1B6'})));
addEntry(section, 'io614_can_visibility_vcu_status_ids', uint32(hex2dec( ...
    {'383', '385', '393', '395', '3A3', '3A5', '3B3', '3B5', '400'})));

saveChanges(dictionary);
end

function value = parameter(initialValue, minimum, maximum)
value = Simulink.Parameter(initialValue);
value.Min = double(min(minimum(:)));
value.Max = double(max(maximum(:)));
value.CoderInfo.StorageClass = 'SimulinkGlobal';
end

function addCanSetup(model)
setup = add_block('speedgoatlib_IO614/CAN and LIN Setup ', ...
    [model '/IO614 CAN Setup'], 'Position', [40 30 220 100]);
set_param(setup, 'moduleType', 'IO614', 'id', '1', ...
    'canChn1', 'CAN (HS)', 'canChn2', 'Disabled', ...
    'canChn3', 'Disabled', 'canChn4', 'Disabled', ...
    'arbBdrChn1', '1.0 MBaud');
end

function addClock(model)
add_block('simulink/Sources/Digital Clock', [model '/Model Time'], ...
    'sampletime', '0.001', 'Position', [40 130 90 160]);
end

function addReceivePath(model)
read = add_block('speedgoatlib_IO614/CAN Read ', [model '/IO614 CAN FIFO Read Raw'], ...
    'Position', [40 200 240 260]);
set_param(read, 'moduleType', 'IO614', 'id', '1', 'channel', '1', ...
    'canType', 'CAN (HS)', 'useBusOut', 'on', ...
    'HasMulRead', 'Single Read from Buffer (FIFO)', 'LabelInHex', 'on', ...
    'enableInput', 'off', 'ts', '0.001');

sel = add_block('simulink/Signal Routing/Bus Selector', [model '/Rx Bus Selector'], ...
    'Position', [280 195 380 265]);
set_param(sel, 'OutputSignals', 'ID,Extended,Remote,Length,Data,Timestamp');

add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model '/Rx Decoder'], 'Position', [430 170 660 340]);
setMatlabFunctionScript(model, 'Rx Decoder', rxDecoderScript());

add_line(model, 'IO614 CAN FIFO Read Raw/1', 'Rx Decoder/1', 'autorouting', 'on');
add_line(model, 'IO614 CAN FIFO Read Raw/2', 'Rx Bus Selector/1', 'autorouting', 'on');
add_line(model, 'Rx Bus Selector/1', 'Rx Decoder/2', 'autorouting', 'on');
add_line(model, 'Rx Bus Selector/2', 'Rx Decoder/3', 'autorouting', 'on');
add_line(model, 'Rx Bus Selector/3', 'Rx Decoder/4', 'autorouting', 'on');
add_line(model, 'Rx Bus Selector/4', 'Rx Decoder/5', 'autorouting', 'on');
add_line(model, 'Rx Bus Selector/5', 'Rx Decoder/6', 'autorouting', 'on');
add_line(model, 'Rx Bus Selector/6', 'Rx Decoder/7', 'autorouting', 'on');
add_line(model, 'Model Time/1', 'Rx Decoder/8', 'autorouting', 'on');

add_block('simulink/Signal Routing/Demux', [model '/Rx Payload Demux'], ...
    'Outputs', '8', 'Position', [720 260 730 400]);
add_line(model, 'Rx Decoder/6', 'Rx Payload Demux/1', 'autorouting', 'on');

outNames = {'rx_valid', 'rx_id_dec', 'rx_id_hex', 'rx_is_extended', ...
    'rx_is_remote', 'rx_dlc', 'rx_count', 'rx_last_timestamp', ...
    'rx_interarrival_ms'};
srcPorts = [1 2 2 3 4 5 7 8 9];
for index = 1:numel(outNames)
    addNamedOutport(model, outNames{index}, 780, 130 + 40 * index, ...
        'Rx Decoder', srcPorts(index));
end
for byte = 0:7
    addNamedOutport(model, sprintf('rx_payload_b%d', byte), 780, ...
        520 + 30 * byte, 'Rx Payload Demux', byte + 1);
end
end

function addTransmitPath(model)
add_block('simulink/Sources/Constant', [model '/tx_enable Param'], ...
    'Value', 'tx_enable', 'Position', [40 800 160 830]);
add_block('simulink/Sources/Constant', [model '/tx_id Param'], ...
    'Value', 'tx_id', 'Position', [40 850 160 880]);
add_block('simulink/Sources/Constant', [model '/tx_dlc Param'], ...
    'Value', 'tx_dlc', 'Position', [40 900 160 930]);
add_block('simulink/Sources/Constant', [model '/tx_payload_u8 Param'], ...
    'Value', 'tx_payload_u8', 'Position', [40 950 160 980]);
add_block('simulink/Sources/Constant', [model '/tx_period_ms Param'], ...
    'Value', 'tx_period_ms', 'Position', [40 1000 160 1030]);

add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model '/Tx Generator'], 'Position', [220 800 420 900]);
setMatlabFunctionScript(model, 'Tx Generator', txGeneratorScript());

add_line(model, 'tx_enable Param/1', 'Tx Generator/1', 'autorouting', 'on');
add_line(model, 'tx_period_ms Param/1', 'Tx Generator/2', 'autorouting', 'on');
add_line(model, 'Model Time/1', 'Tx Generator/3', 'autorouting', 'on');

add_block('simulink/Sources/Constant', [model '/Tx Extended (0)'], ...
    'Value', 'uint8(0)', 'Position', [480 720 560 745]);
add_block('simulink/Sources/Constant', [model '/Tx Remote (0)'], ...
    'Value', 'uint8(0)', 'Position', [480 760 560 785]);
add_block('simulink/Sources/Constant', [model '/Tx Error (0)'], ...
    'Value', 'uint8(0)', 'Position', [480 800 560 825]);
add_block('simulink/Sources/Constant', [model '/Tx Timestamp (0)'], ...
    'Value', 'double(0)', 'Position', [480 840 560 865]);

add_block('simulink/Signal Routing/Bus Creator', [model '/Tx Bus Creator'], ...
    'Inputs', '7', 'Position', [620 700 720 900]);

busFieldNames = {'Extended', 'Length', 'Remote', 'Error', 'ID', ...
    'Timestamp', 'Data'};

setLineName(add_line(model, 'Tx Extended (0)/1', 'Tx Bus Creator/1', ...
    'autorouting', 'on'), busFieldNames{1});
setLineName(add_line(model, 'tx_dlc Param/1', 'Tx Bus Creator/2', ...
    'autorouting', 'on'), busFieldNames{2});
setLineName(add_line(model, 'Tx Remote (0)/1', 'Tx Bus Creator/3', ...
    'autorouting', 'on'), busFieldNames{3});
setLineName(add_line(model, 'Tx Error (0)/1', 'Tx Bus Creator/4', ...
    'autorouting', 'on'), busFieldNames{4});
setLineName(add_line(model, 'tx_id Param/1', 'Tx Bus Creator/5', ...
    'autorouting', 'on'), busFieldNames{5});
setLineName(add_line(model, 'Tx Timestamp (0)/1', 'Tx Bus Creator/6', ...
    'autorouting', 'on'), busFieldNames{6});
setLineName(add_line(model, 'tx_payload_u8 Param/1', 'Tx Bus Creator/7', ...
    'autorouting', 'on'), busFieldNames{7});

write = add_block('speedgoatlib_IO614/CAN Write ', [model '/IO614 CAN Write'], ...
    'Position', [780 780 980 840]);
set_param(write, 'moduleType', 'IO614', 'id', '1', 'channel', '1', ...
    'canType', 'CAN (HS)', 'useBusIn', 'on', 'numOfMsg', '1', ...
    'enableInput', 'on', 'enableStatusPort', 'on', 'ts', '0.001');

add_line(model, 'Tx Generator/1', 'IO614 CAN Write/1', 'autorouting', 'on');
add_line(model, 'Tx Bus Creator/1', 'IO614 CAN Write/2', 'autorouting', 'on');

add_block('simulink/Signal Routing/Demux', [model '/Tx Payload Demux'], ...
    'Outputs', '8', 'Position', [780 700 790 780]);
add_line(model, 'tx_payload_u8 Param/1', 'Tx Payload Demux/1', 'autorouting', 'on');

addNamedOutport(model, 'tx_enable', 1040, 700, 'tx_enable Param', 1);
addNamedOutport(model, 'tx_id_dec', 1040, 730, 'tx_id Param', 1);
addNamedOutport(model, 'tx_id_hex', 1040, 760, 'tx_id Param', 1);
addNamedOutport(model, 'tx_dlc', 1040, 790, 'tx_dlc Param', 1);
addNamedOutport(model, 'tx_period_ms', 1040, 820, 'tx_period_ms Param', 1);
addNamedOutport(model, 'tx_count', 1040, 850, 'Tx Generator', 2);
addNamedOutport(model, 'can_write_status', 1040, 880, 'IO614 CAN Write', 1);
for byte = 0:7
    addNamedOutport(model, sprintf('tx_payload_b%d', byte), 1040, ...
        910 + 30 * byte, 'Tx Payload Demux', byte + 1);
end
end

function addDiagnostics(model)
status = add_block('speedgoatlib_IO614/CAN Status ', [model '/IO614 CAN Diagnostics'], ...
    'Position', [40 1080 240 1180]);
set_param(status, 'moduleType', 'IO614', 'id', '1', 'channel', '1', ...
    'canType', 'CAN (HS)', 'autoRecovery', 'off', 'ts', '0.001');

diagNames = {'can_bus_load', 'can_bus_off', 'can_recovery_count', ...
    'can_transmit_pending', 'can_receive_overrun', 'can_error_warning'};
for index = 1:numel(diagNames)
    addNamedOutport(model, diagNames{index}, 300, ...
        1090 + 30 * (index - 1), 'IO614 CAN Diagnostics', index);
end
end

function addNamedOutport(model, name, x, y, srcBlock, srcPort)
outBlock = add_block('simulink/Sinks/Out1', [model '/' name], ...
    'Position', [x y x + 40 y + 20]);
portNumber = str2double(get_param(outBlock, 'Port'));
set_param(outBlock, 'Port', num2str(portNumber));
add_line(model, sprintf('%s/%d', srcBlock, srcPort), [name '/1'], ...
    'autorouting', 'on');
end

function setLineName(lineHandle, name)
set_param(lineHandle, 'Name', name);
end

function setMatlabFunctionScript(model, blockName, script)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', [model '/' blockName]);
chart.Script = script;
end

function script = rxDecoderScript()
script = strjoin({ ...
    'function [rx_valid, rx_id, rx_is_extended, rx_is_remote, rx_dlc, ...' , ...
    '    rx_payload_u8, rx_count, rx_last_timestamp, rx_interarrival_ms] = ...', ...
    '    fcn(validIn, idIn, extIn, remIn, dlcIn, dataIn, tsIn, tNow)', ...
    '%#codegen', ...
    'persistent latchedId latchedExt latchedRem latchedDlc latchedData', ...
    'persistent latchedTs count lastValidMs interarrivalMs', ...
    'if isempty(latchedId)', ...
    '    latchedId = uint32(0);', ...
    '    latchedExt = uint8(0);', ...
    '    latchedRem = uint8(0);', ...
    '    latchedDlc = uint8(0);', ...
    '    latchedData = uint8(zeros(1, 8));', ...
    '    latchedTs = double(0);', ...
    '    count = uint32(0);', ...
    '    lastValidMs = double(-1);', ...
    '    interarrivalMs = double(0);', ...
    'end', ...
    'nowMs = tNow * 1000;', ...
    'if validIn', ...
    '    latchedId = uint32(idIn);', ...
    '    latchedExt = uint8(extIn);', ...
    '    latchedRem = uint8(remIn);', ...
    '    latchedDlc = uint8(dlcIn);', ...
    '    latchedData = uint8(dataIn(:))'';', ...
    '    latchedTs = double(tsIn);', ...
    '    count = count + uint32(1);', ...
    '    if lastValidMs >= 0', ...
    '        interarrivalMs = nowMs - lastValidMs;', ...
    '    end', ...
    '    lastValidMs = nowMs;', ...
    'end', ...
    'rx_valid = logical(validIn);', ...
    'rx_id = latchedId;', ...
    'rx_is_extended = latchedExt;', ...
    'rx_is_remote = latchedRem;', ...
    'rx_dlc = latchedDlc;', ...
    'rx_payload_u8 = latchedData;', ...
    'rx_count = count;', ...
    'rx_last_timestamp = latchedTs;', ...
    'rx_interarrival_ms = interarrivalMs;', ...
    'end'}, sprintf('\n'));
end

function script = txGeneratorScript()
% send is the IO614 CAN Write "Tx Control" input: uint32(1) transmits
% the current bus contents this step, uint32(0) skips transmission.
script = strjoin({ ...
    'function [send, tx_count] = fcn(txEnable, periodMs, tNow)', ...
    '%#codegen', ...
    'persistent lastSendMs count', ...
    'if isempty(lastSendMs)', ...
    '    lastSendMs = double(-1);', ...
    '    count = uint32(0);', ...
    'end', ...
    'nowMs = tNow * 1000;', ...
    'safePeriod = max(periodMs, 1);', ...
    'send = uint32(0);', ...
    'if txEnable && (lastSendMs < 0 || (nowMs - lastSendMs) >= safePeriod)', ...
    '    send = uint32(1);', ...
    '    lastSendMs = nowMs;', ...
    '    count = count + uint32(1);', ...
    'end', ...
    'tx_count = count;', ...
    'end'}, sprintf('\n'));
end

function addAnnotation(model, text, position, color)
annotation = Simulink.Annotation(model, text);
annotation.Position = position;
annotation.BackgroundColor = color;
annotation.FontWeight = 'bold';
end

function closeIfLoaded(model)
if bdIsLoaded(model)
    close_system(model, 0);
end
end
