function snapshot = carMakerSteeringSnapshot(bank, tickMs)
%CARMAKERSTEERINGSNAPSHOT Retained 0x507 steering value with a freshness verdict.
%   FRESH requires a retained value, an age within
%   DEFAULTVEHICLESTATECONFIG.CARMAKERSTEERINGFRESHNESSMS, and a proven
%   alive-counter advance -- the same three-part test PEDALDEMANDSNAPSHOT uses
%   for CAN ownership, so a stopped sender (age grows) and a frozen-but-
%   repeating sender (counter does not advance) are both reported stale.
if ~isa(tickMs, 'uint32') || ~isscalar(tickMs)
    error('inverterhil:InvalidTick', 'tickMs must be a uint32 scalar.');
end
config = defaultVehicleStateConfig();
ageMs = intmax('uint32');
if bank.hasValue
    ageMs = uint32(mod(double(tickMs) - double(bank.lastValidTickMs), 2^32));
end
fresh = bank.hasValue && ...
    ageMs <= uint32(config.carMakerSteeringFreshnessMs) && ...
    bank.counterAdvanced;
snapshot = struct('angleDeg', bank.angleDeg, ...
    'speedDegPerSec', bank.speedDegPerSec, ...
    'aliveCounter', bank.aliveCounter, ...
    'hasValue', bank.hasValue, ...
    'counterAdvanced', bank.counterAdvanced, ...
    'ageMs', ageMs, 'fresh', fresh, ...
    'acceptedCount', bank.acceptedCount, ...
    'rejectedCount', bank.rejectedCount, ...
    'lastRejectCode', bank.lastRejectCode);
end
