function snapshot = carMakerSteeringSnapshot(bank, tickMs)
%CARMAKERSTEERINGSNAPSHOT Retained 0x507 steering value with a freshness verdict.
%   FRESH requires a retained value, an age within
%   DEFAULTVEHICLESTATECONFIG.CARMAKERSTEERINGFRESHNESSMS, and a proven
%   counter advance -- the same three-part test PEDALDEMANDSNAPSHOT uses for
%   CAN ownership, so a stopped sender (age grows) and a frozen-but-repeating
%   sender (counter does not advance, and RECEIVECARMAKERSTEERING refuses to
%   refresh the timestamp for it) are both reported stale.
%
%   The retained value is still reported when stale. That is diagnostic only:
%   SELECTSTEERINGSOURCE must not encode a stale angle as a live measurement.
if ~isa(tickMs, 'uint32') || ~isscalar(tickMs)
    error('inverterhil:InvalidTick', 'tickMs must be a uint32 scalar.');
end
config = defaultVehicleStateConfig();
ageMs = intmax('uint32');
if bank.hasValue
    ageMs = uint32(mod(double(tickMs) - double(bank.lastValidTickMs), 2^32));
end
fresh = bank.hasValue && ...
    ageMs <= uint32(config.carMakerSteeringFreshnessMs) && ...
    bank.counterAdvanced;
snapshot = struct('angleRad', bank.angleRad, ...
    'angleDeg', bank.angleDeg, ...
    'groupCounter', bank.groupCounter, ...
    'hasValue', bank.hasValue, ...
    'counterAdvanced', bank.counterAdvanced, ...
    'ageMs', ageMs, 'fresh', fresh, ...
    'acceptedCount', bank.acceptedCount, ...
    'rejectedCount', bank.rejectedCount, ...
    'lastRejectCode', bank.lastRejectCode);
end
