function input = defaultPlantInput(cal)
%DEFAULTPLANTINPUT Return a safe, quiescent four-channel plant input.

if nargin < 1
    cal = defaultCalibration();
end
validateCalibration(cal);
p = protocol();

channel = struct( ...
    'mode', p.state.idle, ...
    'ready', false, ...
    'zeroTorque', true, ...
    'activeFault', 'none', ...
    'commandTorqueTimeout', false, ...
    'commandErrorTimeout', false, ...
    'authorityReason', 'default_safe', ...
    'speedSetpointRpm', 0, ...
    'torqueLimitPositiveNm', 0, ...
    'torqueLimitNegativeNm', 0, ...
    'rawTorquePosCounts', int16(0), ...
    'rawTorqueNegCounts', int16(0), ...
    'loadTorqueNm', 0, ...
    'dcLinkV', 400);
% ACTIVEFAULT and AUTHORITYREASON are overwritten by callers (see
% INVERTERHIL.STEPMODEL) with strings of different lengths than the 'none'/
% 'default_safe' literals above; MATLAB Coder locks a struct field's size at
% first assignment unless told otherwise.
coder.varsize('channel.activeFault', [1, 48], [0, 1]);
coder.varsize('channel.authorityReason', [1, 48], [0, 1]);

input.protocolProfileId = cal.protocolProfileId;
input.channels = repmat(channel, 1, 4);
end
