classdef TestModelArtifacts < matlab.unittest.TestCase
    properties (SetAccess = private)
        Root
        Model = 'inverter_hil'
        Hardware
    end

    methods (TestClassSetup)
        function loadIoDisconnectedArtifact(testCase)
            testFolder = fileparts(mfilename('fullpath'));
            % TESTFOLDER is VC_HIL/tests/inverter_hil; two levels up is
            % VC_HIL itself, whose generated model/app artifacts and their
            % build/verify/deploy scripts now live one level further in
            % VC_HIL/build.
            vcHilRoot = fileparts(fileparts(testFolder));
            testCase.Root = fullfile(vcHilRoot, 'build');
            addpath(testCase.Root);
            testCase.Root = inverter_hil_setup();
            testCase.assertEqual(version('-release'), '2024b');
            load_system(fullfile(testCase.Root, 'inverter_hil.slx'));
            testCase.Hardware = [testCase.Model ...
                '/Hardware I O - PRE-FLIGHT DISABLED'];
            testCase.assertEqual(get_param(testCase.Hardware, 'Commented'), 'off');
            set_param(testCase.Model, 'SimulationCommand', 'update');
        end
    end

    methods (TestClassTeardown)
        function closeArtifact(testCase)
            if bdIsLoaded(testCase.Model)
                close_system(testCase.Model, 0);
            end
            libraries = {'speedgoatlib_IO183', 'speedgoatlib_IO614'};
            for index = 1:numel(libraries)
                if bdIsLoaded(libraries{index})
                    close_system(libraries{index}, 0);
                end
            end
        end
    end

    methods (Test)
        function releaseGuardsPrecedeArtifactMutation(testCase)
            setupText = fileread(fullfile(testCase.Root, ...
                'inverter_hil_setup.m'));
            testCase.verifyTrue(contains(setupText, "version('-release')"));
            testCase.verifyTrue(contains(setupText, "'2024b'"));
            testCase.verifyTrue(contains(setupText, ...
                "'inverterhil:WrongRelease'"));

            buildText = fileread(fullfile(testCase.Root, ...
                'build_inverter_hil_model.m'));
            setupPosition = strfind(buildText, 'root = inverter_hil_setup()');
            mutationPosition = strfind(buildText, ...
                'prepareOutput(modelPath, force)');
            testCase.verifyNumElements(setupPosition, 1);
            testCase.verifyNumElements(mutationPosition, 1);
            testCase.verifyLessThan(setupPosition, mutationPosition, ...
                ['The release guard must run before an existing model or ' ...
                'dictionary can be deleted.']);
        end

        function modelLoadsAndUpdatesWithIoDisconnected(testCase)
            testCase.verifyTrue(bdIsLoaded(testCase.Model));
            testCase.verifyEqual(get_param(testCase.Hardware, 'Commented'), 'off');
            testCase.verifyEmpty(find_system(testCase.Hardware, ...
                'SearchDepth', 1, 'BlockType', 'Inport'));
            testCase.verifyEmpty(find_system(testCase.Hardware, ...
                'SearchDepth', 1, 'BlockType', 'Outport'));
            % A model update must raise no warning of its own. The ONE
            % exception is Speedgoat:Deprecation: the installed I/O
            % blockset announces that IO183 support ends with R2025b, once
            % per IO183 block, every time the model updates. That is a
            % vendor lifecycle notice about the hardware this rig is built
            % on, not a defect in this model -- it fires identically on
            % commits that predate any of the sensor work -- and it is
            % deliberately NOT silenced with SETPREF, because suppressing
            % it machine-wide would also hide it from the humans who need
            % to plan around an R2025b end of support.
            %
            % Everything else still fails. This filters one known
            % identifier rather than weakening the check to "ignore
            % warnings": an unexpected warning is still a test failure,
            % and the deprecation notice is asserted to be the only one
            % present so it cannot mask a second problem hiding behind it.
            % The notice is disabled only for the duration of this update
            % and restored immediately, so the suppression cannot leak into
            % another test or outlive the run.
            previous = warning('off', 'Speedgoat:Deprecation');
            restore = onCleanup(@() warning(previous));
            testCase.verifyWarningFree(@() set_param(testCase.Model, ...
                'SimulationCommand', 'update'), ...
                ['Updating the model raised a warning other than the ' ...
                'known IO183 end-of-support notice.']);
        end

        function executionAndDictionaryAttachmentAreExact(testCase)
            testCase.verifyEqual(get_param(testCase.Model, 'SolverType'), ...
                'Fixed-step');
            testCase.verifyEqual(get_param(testCase.Model, 'Solver'), ...
                'FixedStepDiscrete');
            testCase.verifyEqual(get_param(testCase.Model, 'FixedStep'), ...
                '0.001');
            testCase.verifyEqual(get_param(testCase.Model, ...
                'SystemTargetFile'), 'speedgoat.tlc');
            testCase.verifyEqual(get_param(testCase.Model, ...
                'DataDictionary'), 'inverter_hil.sldd');
        end

        function requiredArchitectureIsPresent(testCase)
            % The decorative "Test Inputs" / "Fault Injection" / "Pedal
            % Sensor Emulation" / "VCU Digital Interface" / fake "IO614 CAN
            % Interface" / "Ephorus Channel 1-4" / "Measurements and
            % Logging" tree was removed: every one of those subsystems
            % terminated its inputs immediately and emitted only constant
            % zeros (see DEADCHANNELSWEREREMOVEDNOTJUSTRELABELED below).
            required = {'Ephorus System Status', ...
                'Hardware I O - PRE-FLIGHT DISABLED'};
            for index = 1:numel(required)
                path = [testCase.Model '/' required{index}];
                testCase.verifyNotEqual(getSimulinkBlockHandle(path), -1, ...
                    sprintf('Missing required architecture block %s.', path));
                testCase.verifyEqual(get_param(path, 'BlockType'), 'SubSystem');
            end
        end

        function hardwareBoundaryHasExactResolvedInstalledLinks(testCase)
            load_system('speedgoatlib_IO183');
            load_system('speedgoatlib_IO614');
            load_system('canlib');
            load_system('canmsglib');
            % Two CAN Read and two CAN Status: one of each per bus after the
            % CAN split (channel 1 = CarMaker bus, channel 2 = VC bus).
            expected = { ...
                'speedgoatlib_IO183/Setup'; ...
                'speedgoatlib_IO183/Analog Input'; ...
                'speedgoatlib_IO183/Analog Output'; ...
                'speedgoatlib_IO183/Digital Input'; ...
                'speedgoatlib_IO183/Digital Output'; ...
                'speedgoatlib_IO614/CAN and LIN Setup '; ...
                'speedgoatlib_IO614/CAN Read '; ...
                'speedgoatlib_IO614/CAN Read '; ...
                'speedgoatlib_IO614/CAN Status '; ...
                'speedgoatlib_IO614/CAN Status '};
            % Nine inverter status frames, two CarMaker telemetry frames,
            % four synchronized sensor frames (three MTi vectors + the LWS
            % standard frame), the Bosch configuration frame, and the four
            % MTi scalar-group frames (group counter, sample time, status
            % word, error code): 20 CAN Write/CAN Pack pairs in total.
            expected = [expected; repmat( ...
                {'speedgoatlib_IO614/CAN Write '}, 20, 1)];
            % Added from canlib, but the link resolves to the underlying
            % shared CAN message library that canlib forwards to.
            expected = [expected; repmat( ...
                {'canmsglib/CAN Pack'}, 20, 1)];
            for index = 1:numel(expected)
                testCase.verifyNotEqual(getSimulinkBlockHandle(expected{index}), -1, ...
                    sprintf('Installed library path is absent: [%s].', ...
                    expected{index}));
            end

            blocks = find_system(testCase.Hardware, 'LookUnderMasks', 'all', ...
                'FollowLinks', 'on', 'Type', 'Block');
            references = cellfun(@(block) get_param(block, 'ReferenceBlock'), ...
                blocks, 'UniformOutput', false);
            linked = blocks(~cellfun(@isempty, references));
            references = references(~cellfun(@isempty, references));
            testCase.verifyNumElements(linked, 50);
            testCase.verifyEqual(sort(references(:)), sort(expected(:)));
            for index = 1:numel(linked)
                testCase.verifyEqual(get_param(linked{index}, 'LinkStatus'), ...
                    'resolved', sprintf('Unresolved link: %s.', linked{index}));
            end
        end

        function io183SafetyAndAllocationAreExact(testCase)
            setup = [testCase.Hardware '/IO183 Setup'];
            ao = [testCase.Hardware '/IO183 AO01-AO04 Safe Zero'];
            ai = [testCase.Hardware '/IO183 AI01-AI04 Rail Monitor'];
            digitalOut = [testCase.Hardware ...
                '/IO183 DIO01-DIO08 Safe Zero'];
            digitalIn = [testCase.Hardware ...
                '/IO183 DIO09-DIO13 VCU Monitor'];

            TestModelArtifacts.verifyParameters(testCase, setup, { ...
                'parDaSimult', 'on'; ...
                'parAdCoupling', 'Single Ended'; ...
                'parAdRange', '0..5V'; ...
                'parAdChannelLow', '1'; ...
                'parAdChannelHigh', '4'; ...
                'parDaChannels', '[1 2 3 4]'; ...
                'parDaRange', '0..5V'; ...
                'parDaInit', '[0 0 0 0]'; ...
                'parDaReset', '[0 0 0 0]'; ...
                'parDoChannels', '[1 2 3 4 5 6 7 8]'; ...
                'parDoInit', '[0 0 0 0 0 0 0 0]'; ...
                'parDoReset', '[0 0 0 0 0 0 0 0]'; ...
                'parDiChannels', '[9 10 11 12 13]'; ...
                'parIOPullReferenceFront', 'Pull-down'});
            TestModelArtifacts.verifyParameters(testCase, ao, { ...
                'parSampTime', '0.001'; ...
                'parDaSimult', 'on'; ...
                'parDaChannels', '[1 2 3 4]'; ...
                'parDaInit', '[0 0 0 0]'; ...
                'parDaReset', '[0 0 0 0]'});
            TestModelArtifacts.verifyParameters(testCase, ai, { ...
                'parSampTime', '0.001'; ...
                'parAdChannelLow', '1'; ...
                'parAdChannelHigh', '4'});
            TestModelArtifacts.verifyParameters(testCase, digitalOut, { ...
                'parSampTime', '0.001'; ...
                'parDoChannels', '[1 2 3 4 5 6 7 8]'; ...
                'parDoInit', '[0 0 0 0 0 0 0 0]'; ...
                'parDoReset', '[0 0 0 0 0 0 0 0]'});
            TestModelArtifacts.verifyParameters(testCase, digitalIn, { ...
                'parSampTime', '0.001'; ...
                'parDiChannels', '[9 10 11 12 13]'});
        end

        function io614CanAndOrderedWritesAreExact(testCase)
            setup = [testCase.Hardware '/IO614 CAN Setup'];
            read = [testCase.Hardware '/IO614 CAN FIFO Read Raw'];
            status = [testCase.Hardware '/IO614 CAN Diagnostics'];
            carMakerRead = [testCase.Hardware '/IO614 CarMaker FIFO Read'];
            carMakerStatus = ...
                [testCase.Hardware '/IO614 CarMaker CAN Diagnostics'];
            % Connector A and connector B are NOT bridged: two independent
            % buses with the Speedgoat the only node on both. channel 2 /
            % Port A is the real-MFE26-VC bus (control RX, status + sensor
            % TX); channel 1 / Port B is the CarMaker bus (0x500 RX,
            % 0x501/0x502 TX). See build_inverter_hil_model.m's "IO614 CAN
            % Setup" comment. Both channels stay CAN (HS) @ 1.0 MBaud.
            TestModelArtifacts.verifyParameters(testCase, setup, { ...
                'moduleType', 'IO614'; ...
                'id', '1'; ...
                'canChn1', 'CAN (HS)'; ...
                'canChn2', 'CAN (HS)'; ...
                'canChn3', 'Disabled'; ...
                'canChn4', 'Disabled'; ...
                'arbBdrChn1', '1.0 MBaud'; ...
                'arbBdrChn2', '1.0 MBaud'});
            % useBusOut ON is required by the RX path, not incidental: the Rx
            % Bus Selector can only split port 2 when it is a CAN_MESSAGE
            % bus. ts is 0.001 (the model's base rate): reading once per 5 ms
            % tick (200 msg/s) permanently fell behind the burst. A naive fix
            % that just raised this ts put the WHOLE status-cycle chain --
            % state machine, plant, CAN Pack/Write -- on a 1 ms rate that
            % collided with the CAN Write blocks' own explicit 5 ms rate;
            % ephorusRxRetentionRunsFasterThanStatusCycle below locks in the
            % actual fix (retention split into its own 1 ms block, joined to
            % the unchanged 5 ms status-cycle block by a Rate Transition) so
            % neither half of that split can drift back out of sync silently.
            % The VC read + diagnostics are on channel 2; the CarMaker read +
            % diagnostics are the same block type on channel 1.
            TestModelArtifacts.verifyParameters(testCase, read, { ...
                'moduleType', 'IO614'; ...
                'id', '1'; ...
                'channel', '2'; ...
                'canType', 'CAN (HS)'; ...
                'useBusOut', 'on'; ...
                'HasMulRead', 'Single Read from Buffer (FIFO)'; ...
                'ts', '0.001'});
            TestModelArtifacts.verifyParameters(testCase, status, { ...
                'moduleType', 'IO614'; ...
                'id', '1'; ...
                'channel', '2'; ...
                'canType', 'CAN (HS)'; ...
                'autoRecovery', 'off'; ...
                'ts', '0.001'});
            TestModelArtifacts.verifyParameters(testCase, carMakerRead, { ...
                'moduleType', 'IO614'; ...
                'id', '1'; ...
                'channel', '1'; ...
                'canType', 'CAN (HS)'; ...
                'useBusOut', 'on'; ...
                'HasMulRead', 'Single Read from Buffer (FIFO)'; ...
                'ts', '0.001'});
            TestModelArtifacts.verifyParameters(testCase, carMakerStatus, { ...
                'moduleType', 'IO614'; ...
                'id', '1'; ...
                'channel', '1'; ...
                'canType', 'CAN (HS)'; ...
                'autoRecovery', 'off'; ...
                'ts', '0.001'});

            expectedIds = uint32(hex2dec({'383', '385', '393', '395', ...
                '3A3', '3A5', '3B3', '3B5', '400'})).';
            actualIds = zeros(1, 9, 'uint32');
            for index = 1:numel(expectedIds)
                path = sprintf('%s/CAN Write 0x%03X', testCase.Hardware, ...
                    expectedIds(index));
                testCase.verifyNotEqual(getSimulinkBlockHandle(path), -1);
                userData = get_param(path, 'UserData');
                testCase.verifyClass(userData, 'uint32');
                actualIds(index) = userData;
                TestModelArtifacts.verifyParameters(testCase, path, { ...
                    'moduleType', 'IO614'; ...
                    'id', '1'; ...
                    'channel', '2'; ...
                    'canType', 'CAN (HS)'; ...
                    'useBusIn', 'off'; ...
                    'numOfMsg', '1'; ...
                    'enableStatusPort', 'on'; ...
                    'ts', '0.005'; ...
                    'UserDataPersistent', 'on'});
            end
            testCase.verifyEqual(actualIds, expectedIds, ...
                'CAN Write UserData IDs must retain status-cycle order.');

            % The two CarMaker telemetry frames are the only writes on
            % channel 1 (the CarMaker bus).
            telemetryIds = uint32(hex2dec({'501', '502'})).';
            for index = 1:numel(telemetryIds)
                path = sprintf('%s/CAN Write 0x%03X', testCase.Hardware, ...
                    telemetryIds(index));
                testCase.verifyNotEqual(getSimulinkBlockHandle(path), -1);
                testCase.verifyEqual(get_param(path, 'UserData'), telemetryIds(index));
                TestModelArtifacts.verifyParameters(testCase, path, { ...
                    'moduleType', 'IO614'; ...
                    'id', '1'; ...
                    'channel', '1'; ...
                    'canType', 'CAN (HS)'; ...
                    'useBusIn', 'off'; ...
                    'numOfMsg', '1'; ...
                    'enableStatusPort', 'on'; ...
                    'ts', '0.005'; ...
                    'UserDataPersistent', 'on'});
            end
        end

        function ephorusRxRetentionRunsFasterThanStatusCycle(testCase)
            % Locks in the CAN RX drain-rate fix: retention (EPHORUS RX
            % RETENTION) must run at the 1 ms base rate so it can pop the
            % FIFO fast enough to keep up with the virtual VCU's five CAN
            % IDs every 5 ms (1000 msg/s); the state machine/plant/CAN-write
            % chain (EPHORUS STATUS CYCLE) must stay on the original 5 ms
            % status-cycle rate the CAN Write blocks require, joined to the
            % fast block by an explicit Rate Transition rather than a
            % silently-inherited one. If either half of this drifts back
            % onto a single shared rate, either the FIFO backs up again or
            % the CAN Write rate collision this split exists to avoid comes
            % back.
            statusPath = [testCase.Model '/Ephorus System Status'];
            retention = [statusPath '/Ephorus RX Retention'];
            carMakerRetention = [statusPath '/CarMaker RX Retention'];
            statusCycle = [statusPath '/Ephorus Status Cycle'];
            rateTransition = [statusPath '/Ephorus RX Observation RT'];
            testCase.verifyNotEqual(getSimulinkBlockHandle(retention), -1);
            testCase.verifyNotEqual( ...
                getSimulinkBlockHandle(carMakerRetention), -1);
            testCase.verifyNotEqual(getSimulinkBlockHandle(statusCycle), -1);
            testCase.verifyNotEqual(getSimulinkBlockHandle(rateTransition), -1);

            testCase.verifyEqual(get_param(retention, 'CompiledSampleTime'), ...
                [0.001 0], 'Ephorus RX Retention must run at the 1 ms base rate.');
            % CarMaker Pedal Retention drains its own channel-1 FIFO at the
            % same 1 ms base rate; the 0x500 pedal demand was split out of
            % Ephorus RX Retention when the CAN bus was divided in two.
            testCase.verifyEqual( ...
                get_param(carMakerRetention, 'CompiledSampleTime'), ...
                [0.001 0], ...
                'CarMaker RX Retention must run at the 1 ms base rate.');
            testCase.verifyEqual(get_param(statusCycle, 'CompiledSampleTime'), ...
                [0.005 0], ['Ephorus Status Cycle must stay on the 5 ms ' ...
                'status-cycle rate the CAN Write blocks require.']);

            portHandles = get_param(retention, 'PortHandles');
            testCase.verifyNumElements(portHandles.Inport, 7, ...
                ['Ephorus RX Retention takes the 6 physical RX fields plus ' ...
                'the CAN control-frame drop mask.']);
            testCase.verifyNumElements(portHandles.Outport, 2, ...
                ['Ephorus RX Retention emits the observation matrix and the ' ...
                'raw control diagnostic; the pedal demand moved to CarMaker ' ...
                'Pedal Retention.']);
            carMakerPorts = get_param(carMakerRetention, 'PortHandles');
            testCase.verifyNumElements(carMakerPorts.Inport, 6, ...
                'CarMaker Pedal Retention takes the 6 physical RX fields.');
            testCase.verifyNumElements(carMakerPorts.Outport, 2, ...
                'CarMaker RX Retention emits pedal demand and physics snapshot.');
            physicsRt = [statusPath '/CarMaker Physics Snapshot RT'];
            testCase.verifyNotEqual(getSimulinkBlockHandle(physicsRt), -1);
            statusPorts = get_param(statusCycle, 'PortHandles');
            testCase.verifyNumElements(statusPorts.Inport, 13, ...
                ['Ephorus Status Cycle takes the rate-transitioned ' ...
                'observation matrix plus the 11 remaining GUI-command ' ...
                'inputs (the 10 inverter/DC-link ones and the steering ' ...
                'angle that drives the shared vehicle state).']);
        end

        function sensorWritesDlcInjectionAndCalibrationPathAreExact(testCase)
            ids = uint32(hex2dec({'034', '032', '076', '2B0', '7C0'}));
            nominalDlc = [6 6 6 5 2];
            for index = 1:numel(ids)
                pack = sprintf('%s/CAN Pack Sensor 0x%03X', ...
                    testCase.Hardware, ids(index));
                assignment = sprintf('%s/Sensor DLC Assignment 0x%03X', ...
                    testCase.Hardware, ids(index));
                writer = sprintf('%s/CAN Write Sensor 0x%03X', ...
                    testCase.Hardware, ids(index));
                testCase.verifyNotEqual(getSimulinkBlockHandle(pack), -1);
                testCase.verifyNotEqual( ...
                    getSimulinkBlockHandle(assignment), -1);
                testCase.verifyNotEqual(getSimulinkBlockHandle(writer), -1);
                testCase.verifyEqual(str2double(get_param(pack, ...
                    'MsgLength')), nominalDlc(index));
                testCase.verifyEqual(get_param(pack, 'BusOutput'), 'on', ...
                    'Runtime DLC assignment requires a CAN_MESSAGE bus.');
                testCase.verifyEqual(get_param(assignment, ...
                    'AssignedSignals'), 'Length');
                testCase.verifyEqual(get_param(writer, 'UserData'), ...
                    ids(index));
                testCase.verifyEqual(get_param(writer, 'enableInput'), 'on');
                testCase.verifyEqual(get_param(writer, 'useBusIn'), 'on', ...
                    'Sensor CAN Write must consume the assigned bus.');
                testCase.verifyEqual(get_param(writer, 'channel'), '2', ...
                    ['Sensor frames are VC-bus traffic: the VCU reads the ' ...
                    'MTi/LWS sensors, CarMaker has no use for them.']);
            end

            producer = [testCase.Hardware '/Synchronized Sensor Payloads'];
            ports = get_param(producer, 'PortHandles');
            testCase.verifyNumElements(ports.Inport, 12, ...
                'Sensor producer must receive all independent fault controls.');
            testCase.verifyNumElements(ports.Outport, 18, ...
                ['Payload/control, target count/age/state, and runtime DLC ' ...
                'outputs must all be published.']);

            % The four MTi scalar-group frames (0x006 group counter, 0x005
            % microsecond sample time, 0x011 status word, 0x001 error code)
            % come from their own small producer, not from the fragile
            % 18-output chart above. They carry no malformed-DLC fault, so
            % they use the Ephorus-status write pattern (BusOutput off,
            % useBusIn off, Tx Control gate) rather than the Bus Assignment
            % path the vector frames need.
            scalarIds = uint32(hex2dec({'006', '005', '011', '001'}));
            scalarDlc = [2 4 4 1];
            for index = 1:numel(scalarIds)
                pack = sprintf('%s/CAN Pack Sensor 0x%03X', ...
                    testCase.Hardware, scalarIds(index));
                writer = sprintf('%s/CAN Write Sensor 0x%03X', ...
                    testCase.Hardware, scalarIds(index));
                assignment = sprintf('%s/Sensor DLC Assignment 0x%03X', ...
                    testCase.Hardware, scalarIds(index));
                testCase.verifyNotEqual(getSimulinkBlockHandle(pack), -1);
                testCase.verifyNotEqual(getSimulinkBlockHandle(writer), -1);
                testCase.verifyEqual( ...
                    getSimulinkBlockHandle(assignment), -1, ...
                    'Scalar frames must not have a runtime DLC assignment.');
                testCase.verifyEqual(str2double(get_param(pack, ...
                    'MsgLength')), scalarDlc(index));
                testCase.verifyEqual(get_param(pack, 'BusOutput'), 'off');
                testCase.verifyEqual(get_param(writer, 'useBusIn'), 'off');
                testCase.verifyEqual(get_param(writer, 'enableInput'), 'on');
                testCase.verifyEqual(get_param(writer, 'channel'), '2');
                testCase.verifyEqual(get_param(writer, 'UserData'), ...
                    scalarIds(index));
                testCase.verifyEqual(get_param(writer, 'ts'), '0.005');
            end
            scalarProducer = [testCase.Hardware '/Scalar Sensor Payloads'];
            testCase.verifyNotEqual( ...
                getSimulinkBlockHandle(scalarProducer), -1);
            scalarPorts = get_param(scalarProducer, 'PortHandles');
            testCase.verifyNumElements(scalarPorts.Inport, 1, ...
                'Scalar producer is gated only by the IMU dropout flag.');
            testCase.verifyNumElements(scalarPorts.Outport, 10, ...
                ['Four scalar payloads, four Tx Control gates, and the ' ...
                'target count/age vectors must all be published.']);
        end

        function dictionaryContractAndSafeDefaultsAreExact(testCase)
            dictionary = Simulink.data.dictionary.open(fullfile( ...
                testCase.Root, 'inverter_hil.sldd'));
            cleanup = onCleanup(@() close(dictionary)); %#ok<NASGU>
            section = getSection(dictionary, 'Design Data');
            constants = pedalCalibrationConstants();

            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_model_release'), 'R2024b');
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_base_sample_s'), 0.001);
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_status_sample_s'), 0.005);
            % Every GUI-owned tunable is a scalar dictionary entry whose name
            % matches +INVERTERHILGUI/PARAMETERCONTRACT.M's flatPath exactly,
            % so DISCOVERCONTRACT resolves it against the real target. See
            % ADDGUICOMMANDPARAMETERS for the block that keeps each one live
            % through code generation.
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_pedals_throttle'), 0);
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_pedals_brake'), 0);
            sensorFaults = {'hil_cmd_steering_dropout', ...
                'hil_cmd_steering_stale', 'hil_cmd_steering_malformed', ...
                'hil_cmd_steering_invalid_status', ...
                'hil_cmd_steering_angle_sentinel', ...
                'hil_cmd_steering_speed_sentinel', ...
                'hil_cmd_imu_dropout', 'hil_cmd_imu_stale', ...
                'hil_cmd_imu_malformed'};
            for sensorFaultIndex = 1:numel(sensorFaults)
                testCase.verifyFalse(TestModelArtifacts.value(section, ...
                    sensorFaults{sensorFaultIndex}));
            end
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_steering_calibration_sequence'), uint32(0));
            testCase.verifyFalse(TestModelArtifacts.value(section, ...
                'hil_cmd_pedals_plausibility_override'));
            testCase.verifyFalse(TestModelArtifacts.value(section, ...
                'hil_cmd_digital_main_button'));
            testCase.verifyFalse(TestModelArtifacts.value(section, ...
                'hil_cmd_digital_cooling_switch'));
            testCase.verifyFalse(TestModelArtifacts.value(section, ...
                'hil_cmd_digital_shutdown_feedback'));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_digital_precharge_sequence'), uint32(0));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_digital_main_button_sequence'), uint32(0));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_dc_link12_v'), 0);
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_dc_link34_v'), 0);
            for channel = 1:4
                testCase.verifyEqual(TestModelArtifacts.value(section, ...
                    sprintf('hil_cmd_inverter%d_load_nm', channel)), 0);
                testCase.verifyTrue(TestModelArtifacts.value(section, ...
                    sprintf('hil_cmd_inverter%d_connected', channel)));
                testCase.verifyEqual(TestModelArtifacts.value(section, ...
                    sprintf('hil_cmd_inverter%d_fault_mask', channel)), ...
                    uint32(0));
                % Pedal endpoints were NaN (deliberately uncalibrated) until
                % 2026-08-02, when they were derived from the VCU firmware's
                % own conversions through its 3.3 V / 65535 ADC domain.
                %
                % The shipped dictionary must match
                % INVERTERHIL.PEDALCALIBRATIONCONSTANTS exactly. An earlier
                % looser check (finite, in 0-5 V, endpoints differ) passed
                % happily on a partly-applied calibration and, more to the
                % point, could not tell a rebuild-wiped dictionary from a
                % recalibrated one -- the NaN wipe it did catch had already
                % shipped to the target. Equality against the version-
                % controlled constants is what makes the wipe loud.
                expected = constants([constants.channel] == channel);
                testCase.assertNumElements(expected, 1);
                releasedV = TestModelArtifacts.value(section, ...
                    sprintf('hil_cal_pedals_released_v%d', channel));
                pressedV = TestModelArtifacts.value(section, ...
                    sprintf('hil_cal_pedals_pressed_v%d', channel));
                testCase.verifyEqual(releasedV, expected.releasedV, ...
                    sprintf(['released_v%d must match ' ...
                    'pedalCalibrationConstants; re-run ' ...
                    'apply_pedal_calibration.'], channel));
                testCase.verifyEqual(pressedV, expected.pressedV, ...
                    sprintf(['pressed_v%d must match ' ...
                    'pedalCalibrationConstants; re-run ' ...
                    'apply_pedal_calibration.'], channel));
                % Still asserted independently of the constants: these are
                % the physical limits of the IO183 output, so a future
                % recalibration that violates them is a defect even though it
                % would agree with itself.
                testCase.verifyGreaterThanOrEqual(releasedV, 0);
                testCase.verifyLessThanOrEqual(releasedV, 5);
                testCase.verifyGreaterThanOrEqual(pressedV, 0);
                testCase.verifyLessThanOrEqual(pressedV, 5);
                testCase.verifyNotEqual(releasedV, pressedV, ...
                    sprintf(['channel %d endpoints must differ or the ' ...
                    'pedal cannot sweep.'], channel));
            end
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_can_drop_control_mask'), uint8(0));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_can_drop_status_mask'), uint16(0));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_gui_heartbeat'), uint32(0));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_safe_analog_reset_v'), zeros(1, 4));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_safe_digital_reset'), false(1, 8));

            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_control_can_ids'), uint32(hex2dec( ...
                {'186', '196', '1A6', '1B6'})));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_status_can_ids'), uint32(hex2dec( ...
                {'383', '385', '393', '395', '3A3', '3A5', ...
                '3B3', '3B5', '400'})));
            % Torque scale RESOLVED 2026-08-02 by firmware evidence (see
            % INVERTERHIL.PROTOCOL's torqueProfiles.vcu256 comment): the
            % dictionary now carries the verified 1/256 profile, not the
            % retired 1/512 provisional one.
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_torque_profile_id'), ...
                'ephorus3-v1.03-candidate-1over256');
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_torque_scale_nm_per_count'), 1 / 256);
            testCase.verifyTrue(TestModelArtifacts.value(section, ...
                'hil_torque_scale_verified'));
            testCase.verifyTrue(TestModelArtifacts.value(section, ...
                'hil_hardware_preflight_complete'));
            testCase.verifyTrue(TestModelArtifacts.value(section, ...
                'hil_torque_results_provisional'));
        end

        function carMakerPedalSelectorIsAtomicAndImmediatelyUpstream(testCase)
            hw = [testCase.Model '/Hardware I O - PRE-FLIGHT DISABLED'];
            pedal = [hw '/Pedal Voltage Calibration'];
            selectors = {'Throttle Source Switch', 'Brake Source Switch'};
            for index = 1:numel(selectors)
                selector = [hw '/' selectors{index}];
                testCase.verifyNotEqual(getSimulinkBlockHandle(selector), -1);
                testCase.verifyEqual(get_param(selector, 'Criteria'), 'u2 ~= 0');
                handles = get_param(selector, 'PortHandles');
                ownershipLine = get_param(handles.Inport(2), 'Line');
                ownershipSource = get_param( ...
                    get_param(ownershipLine, 'SrcPortHandle'), 'Parent');
                testCase.verifyThat(ownershipSource, ...
                    matlab.unittest.constraints.ContainsSubstring( ...
                    'CarMaker Pedal Demand Demux'));
            end
            pedalHandles = get_param(pedal, 'PortHandles');
            for port = 1:2
                line = get_param(pedalHandles.Inport(port), 'Line');
                source = get_param(get_param(line, 'SrcPortHandle'), 'Parent');
                testCase.verifyThat(source, ...
                    matlab.unittest.constraints.ContainsSubstring(selectors{port}));
            end
        end

        function preflightGateIsEnforcedByTopology(testCase)
            dictionary = Simulink.data.dictionary.open(fullfile( ...
                testCase.Root, 'inverter_hil.sldd'));
            cleanup = onCleanup(@() close(dictionary)); %#ok<NASGU>
            section = getSection(dictionary, 'Design Data');
            testCase.verifyTrue(TestModelArtifacts.value(section, ...
                'hil_hardware_preflight_complete'));
            testCase.verifyEqual(get_param(testCase.Hardware, 'Commented'), 'off');
            initFcn = get_param(testCase.Model, 'InitFcn');
            testCase.verifyTrue(contains(initFcn, ...
                'enforceHardwarePreflight'));
            % Shipped defaults (operator-attested preflight complete, boundary
            % live): the gate passes.
            testCase.verifyWarningFree(@() enforceHardwarePreflight( ...
                testCase.Model));

            % Commenting the boundary back out short-circuits the gate
            % regardless of the dictionary flag.
            set_param(testCase.Hardware, 'Commented', 'on');
            restoreCommented = onCleanup(@() set_param(testCase.Hardware, ...
                'Commented', 'off')); %#ok<NASGU>
            testCase.verifyWarningFree(@() enforceHardwarePreflight( ...
                testCase.Model));
            set_param(testCase.Hardware, 'Commented', 'off');

            % With the boundary live, an unattested (false) flag still blocks
            % the model, so the shipped 'true' default is a real gate and not
            % a bypass.
            % PREFLIGHT GATE REMOVED 2026-08-02 by explicit operator
            % decision. An unattested (false) flag now WARNS and continues
            % instead of throwing, so the hardware boundary comes up without
            % the electrical/ground/isolation/termination attestation.
            % Asserted explicitly, because a silently-missing warning would
            % mean the operator gets no signal at all.
            entry = getEntry(section, 'hil_hardware_preflight_complete');
            restoreValue = onCleanup(@() setValue(entry, true)); %#ok<NASGU>
            setValue(entry, false);
            saveChanges(dictionary);
            testCase.verifyWarning(@() enforceHardwarePreflight( ...
                testCase.Model), 'inverterhil:HardwarePreflightOpen');

            % The flag is still validated, so a non-logical value is still a
            % hard error rather than being waved through.
            setValue(entry, 7);
            saveChanges(dictionary);
            testCase.verifyError(@() enforceHardwarePreflight( ...
                testCase.Model), ...
                'inverterhil:InvalidHardwarePreflightGate');
            setValue(entry, true);
            saveChanges(dictionary);
        end

        function generatedArtifactsAreIgnoredRepositoryWide(testCase)
            % .gitignore lives in VC_HIL itself, one level above
            % TESTCASE.ROOT (VC_HIL/build, where the generated model/app
            % artifacts and their build scripts live).
            text = fileread(fullfile(fileparts(testCase.Root), '.gitignore'));
            lines = strip(splitlines(string(text)));
            expected = [".simulink/"; "slprj/"; "*.slxc"; ...
                "*_sg_rtw/"; "*_grt_rtw/"; "*_ert_rtw/"];
            for index = 1:numel(expected)
                testCase.verifyTrue(any(lines == expected(index)), ...
                    sprintf('Missing repository-wide ignore rule: %s', ...
                    expected(index)));
            end
        end

        function deadChannelsWereRemovedNotJustRelabeled(testCase)
            % The "Ephorus Channel 1-4" subsystems (buildChannel, plus the
            % Load/DC Link/Fault Demux and Test Inputs/Fault Injection/
            % Pedal Sensor Emulation/VCU Digital Interface/fake IO614 CAN
            % Interface tree feeding them) were removed entirely: every one
            % of them terminated its inputs immediately and emitted only
            % constant zeros, with no path into the real CAN/state-machine/
            % plant logic. Assert they are actually gone, not merely
            % relabeled -- the real logic lives in Ephorus System Status
            % (Ephorus RX Retention / Ephorus Status Cycle),
            % ADDHARDWAREBOUNDARY, and ADDGUICOMMANDPARAMETERS.
            removedNames = {'Ephorus Channel 1', 'Ephorus Channel 2', ...
                'Ephorus Channel 3', 'Ephorus Channel 4', 'Test Inputs', ...
                'Fault Injection', 'Pedal Sensor Emulation', ...
                'VCU Digital Interface', 'Measurements and Logging', ...
                'Load Demux', 'Fault Demux', 'DC Link Demux'};
            topBlocks = find_system(testCase.Model, 'SearchDepth', 1, ...
                'Type', 'Block');
            topNames = get_param(topBlocks, 'Name');
            for index = 1:numel(removedNames)
                testCase.verifyFalse(any(strcmp(topNames, removedNames{index})), ...
                    sprintf('%s is dead code and must not exist.', ...
                    removedNames{index}));
            end
            % The fake "IO614 CAN Interface" name collides with the real
            % hardware boundary's own subsystem naming, so check its exact
            % top-level path rather than any-depth name matching.
            testCase.verifyEmpty(find_system(testCase.Model, 'SearchDepth', 1, ...
                'Name', 'IO614 CAN Interface'));

            annotations = find_system(testCase.Model, 'FindAll', 'on', ...
                'Type', 'annotation');
            names = get_param(annotations, 'Name');
            if ischar(names)
                names = {names};
            end
            claimsActiveMil = any(cellfun(@(name) contains(name, ...
                'MIL architecture active'), names));
            testCase.verifyFalse(claimsActiveMil, ...
                ['The annotation must not claim an active MIL architecture; ' ...
                'the decorative channel tree was removed rather than resurrected.']);
        end

        function deploymentNeverArmsAStartupApplication(testCase)
            source = fileread(fullfile(testCase.Root, 'deploy_inverter_hil.m'));
            testCase.verifySubstring(source, 'clearStartupApp(target)');
            testCase.verifyEmpty(regexp(source, ...
                '(?m)^\s*setStartupApp\s*\(', 'once'), ...
                'Deployment must never configure an application to auto-run.');
        end
    end

    methods (Static, Access = private)
        function verifyParameters(testCase, block, expected)
            for index = 1:size(expected, 1)
                testCase.verifyEqual(get_param(block, expected{index, 1}), ...
                    expected{index, 2}, sprintf('%s parameter %s differs.', ...
                    block, expected{index, 1}));
            end
        end

        function result = value(section, name)
            entry = getEntry(section, name);
            result = getValue(entry);
            if isa(result, 'Simulink.Parameter')
                result = result.Value;
            end
        end
    end
end
