import simscape.battery.builder.*


% Generate Cell
cylindricalGeometry = CylindricalGeometry(Height = simscape.Value(0.07,"m"),...
    Radius = simscape.Value(0.0105,"m"));

batteryCell = Cell(Geometry = cylindricalGeometry);


batteryCell.CellModelOptions.BlockParameters.T_dependence = "yes";
batteryCell.CellModelOptions.BlockParameters.thermal_port = "model";
batteryCell.CellModelOptions.BlockParameters.prm_dyn = "off";
batteryCell.CellModelOptions.BlockParameters.prm_dir = "noCurrentDirectionality";
batteryCell.Mass = simscape.Value(0.068,"kg");

% Using Battery Equivalent Circuit will add an option to insert faults in the module
batteryCell.CellModelOptions.CellModelBlockPath = "batt_lib/Cells/Battery Equivalent Circuit";
batteryCell.CellModelOptions.BlockParameters.ThermalModel = "LumpedThermalMass";

% Generate parallel assembly. ex: NumParallelCells is total number of cells in stacked in no of
% 'Rows'.
batteryParallelAssembly = ParallelAssembly(Cell = batteryCell, ...
    NumParallelCells = 1, ...
    Rows = 1, ...
    Topology = "Hexagonal", ...
    CoolingPlate="Bottom", ...
    ModelResolution = "Detailed",...
    BalancingStrategy="External");


batteryParallelAssemblyChart = BatteryChart(Battery = batteryParallelAssembly, ...
    SimulationStrategyVisible = "on");
%%
% Battery module is generated here
batteryModule = Module(ParallelAssembly = batteryParallelAssembly,...
    NumSeriesAssemblies = 12, ...
    ModelResolution ="Detailed", ...
    SeriesGrouping = [1 1 1 1 1 1 1 1 1 1 1 1], ...
    InterParallelAssemblyGap = simscape.Value(0.005,"m"), ...
    AmbientThermalPath = "CellBasedThermalResistance", ...
    BalancingStrategy = "External");


batteryModuleChart = BatteryChart(Battery = batteryModule, ...
    SimulationStrategyVisible = "on");
%%
% Build battery from module

buildBattery(batteryModule, LibraryName = "BatteryModuleLibrary_12Cells" ,...
    Directory ="C:\Workspace\BMS_repo_clone\BMS-Controller-HIL-wFaults\BatteryModule_12Cells");
