function build_test_torque_model(force)
%BUILD_TEST_TORQUE_MODEL Generate the minimal CAN throttle-to-torque model.
%
%   Deliberately small counterpart to inverter_hil/build_inverter_hil_model.m:
%   no VCU state machine, no decoder banks, no per-wheel torque vectoring,
%   and no proportional throttle-to-torque mapping either. One job only --
%   prove throttle can flow CarMaker -> Speedgoat -> torque -> back to
%   CarMaker over CAN: whenever CAN pedal ownership is held (a valid,
%   fresh, active 0x500 frame), transmit a fixed max torque; otherwise
%   zero.
%
%   Reuses the already-hardware-exercised CAN contracts instead of
%   reinventing them:
%     - RX: CarMakerPedalDemand, CAN ID 0x500, decoded by
%       inverter_hil/+inverterhil/decodePedalDemandFrame.m (CRC-8/SAE-J1850
%       + alive-counter + 100 ms freshness -- see
%       inverter_hil/docs/can_pedal_demand_frame_spec.md and this
%       worktree's own note on commit 61a9dd6, "CarMaker -> CAN ->
%       Speedgoat proven end to end on hardware", branch IPG-CAN).
%     - TX: the CarMaker inverter-telemetry pair, CAN IDs 0x501 (four
%       signed int16 torque setpoints, 1/32 N.m/count) and 0x502 (four
%       ready bits), packed by inverter_hil/+inverterhil/
%       packCarMakerTelemetry.m -- the exact wire contract CarMaker's
%       IPG-MFE/FCM_Projects/FS_race/src_cm4sl/IO.c already decodes in
%       IO_In() into the CarMaker dictionary quantities
%       MFE_CAN.TorqueRequestTotalNm and MFE_CAN.DriveActive (declared in
%       User.c's User_DeclQuants(), no RBS/XCP Setup GUI import needed --
%       these are plain CarMaker Dictionary quantities, resolved by name
%       like any other CM Dict quantity).
%
%   Only one new number is invented here: a flat max-torque constant
%   (test_torque_max_nm dictionary parameter, default 20 N.m -- see the
%   comment at its declaration below for why). torqueNm is exactly
%   maxTorqueNm whenever CAN pedal ownership is held, else exactly zero
%   -- no scaling by throttle amount, a fixed value only. Broadcast as
%   inverter-1's setpoint (channels 2-4 sent as zero, so
%   MFE_CAN_TorqueRequestTotalNm's four-way sum equals the single scalar
%   exactly rather than 4x it). throttlePercent is still decoded and
%   exposed as a verification tap; it just no longer drives the torque
%   value.

if nargin < 1
    force = false;
end
if ~(islogical(force) && isscalar(force))
    error('testTorque:InvalidBuildOption', 'force must be a logical scalar.');
end

root = test_torque_setup();
model = 'test_torque';
modelPath = fullfile(root, [model '.slx']);
dictionaryPath = fullfile(root, [model '.sldd']);

if bdIsLoaded(model)
    close_system(model, 0);
end
prepareOutput(modelPath, force);
prepareOutput(dictionaryPath, force);

load_system('canlib');

createDictionary(dictionaryPath);
new_system(model);
cleanupModel = onCleanup(@() closeIfLoaded(model));
set_param(model, ...
    'DataDictionary', [model '.sldd'], ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.001', ...
    'StartTime', '0.0', ...
    'StopTime', 'inf', ...
    'SystemTargetFile', 'speedgoat.tlc', ...
    'DefaultParameterBehavior', 'Tunable', ...
    'SignalLogging', 'on');

addAnnotation(model, ...
    ['TEST_TORQUE - R2024b - minimal CAN throttle-to-torque bridge\n' ...
     'RX 0x500 CarMakerPedalDemand (proven, see inverter_hil pedal-demand\n' ...
     'decoder) -> flat throttlePercent/100*test_torque_max_nm -> TX 0x501/0x502\n' ...
     '(CarMaker inverter telemetry contract). No VCU state machine, no\n' ...
     'per-wheel vectoring, no decoder banks. Deliberately separate from\n' ...
     'inverter_hil.slx -- see test_torque/README context in the build script.'], ...
    [40 20 900 90], 'yellow');

buildCanTorqueBridge([model '/CAN Torque Bridge'], [140 140 620 420]);

save_system(model, modelPath, 'SaveModelWorkspace', false);
set_param(model, 'SimulationCommand', 'update');
save_system(model, modelPath);

fprintf('Created %s and %s with MATLAB %s.\n', ...
    modelPath, dictionaryPath, version('-release'));
end

function prepareOutput(path, force)
if isfile(path)
    if ~force
        error('testTorque:ArtifactExists', ...
            'Artifact exists; call build_test_torque_model(true): %s', path);
    end
    delete(path);
end
end

function closeIfLoaded(model)
if bdIsLoaded(model)
    close_system(model, 0);
end
end

function createDictionary(path)
dictionary = Simulink.data.dictionary.create(path);
cleanup = onCleanup(@() close(dictionary));
section = getSection(dictionary, 'Design Data');

% Flat max-torque constant: the whole point of this model is a linear
% throttle-percent-to-torque mapping with zero control sophistication.
% 20 N.m is chosen as a deliberately conservative single-scalar test
% value -- enough that, summed into MFE_CAN_TorqueRequestTotalNm and
% consumed by TorqueVect's existing 1/(4*T_i_max) normalization and
% torque-vectoring "Full Control Loop" (unchanged by this model), it
% should be sufd to produce visible rolling motion at full throttle
% without being an aggressive first-movement value on a bench/sim rig.
% Tunable at the target via getparam/setparam like every other
% dictionary entry in this codebase, so it can be raised once the car is
% confirmed to move.
addEntry(section, 'test_torque_max_nm', parameter(20, 0, 200));

saveChanges(dictionary);
end

function value = parameter(initialValue, minimum, maximum)
value = Simulink.Parameter(initialValue);
value.Min = double(min(minimum(:)));
value.Max = double(max(maximum(:)));
value.CoderInfo.StorageClass = 'SimulinkGlobal';
end

function addAnnotation(model, text, position, color)
annotation = add_block('built-in/Note', [model '/Notes'], ...
    'Position', position);
set_param(annotation, 'Text', sprintf(text));
if nargin >= 4
    set_param(annotation, 'BackgroundColor', color);
end
end

function buildCanTorqueBridge(path, position)
%BUILDCANTORQUEBRIDGE The entire model in one subsystem, wrapped so
%GETSIGNAL(target, path, portIndex) can read each verification tap after
%deploy -- a bare top-level Outport does not "originate" a port the way a
%subsystem boundary does (see inverter_hil's own note on this in its
%Virtual VCU Observability history).
add_block('simulink/Ports & Subsystems/Subsystem', path, ...
    'Position', position);
clearSubsystem(path);

setup = add_block('speedgoatlib_IO614/CAN and LIN Setup ', ...
    [path '/IO614 CAN Setup'], 'Position', [40 30 220 100]);
set_param(setup, 'moduleType', 'IO614', 'id', '1', ...
    'canChn1', 'CAN (HS)', 'canChn2', 'Disabled', ...
    'canChn3', 'Disabled', 'canChn4', 'Disabled', ...
    'arbBdrChn1', '1.0 MBaud');

% Same FIFO-drain-at-1ms rationale as inverter_hil's ADDHARDWAREBOUNDARY:
% a 5ms poll under-drains a 10ms-cycle sender and the retained frame goes
% stale. Single read per tick, matching the proven bench configuration.
read = add_block('speedgoatlib_IO614/CAN Read ', ...
    [path '/IO614 CAN FIFO Read Raw'], 'Position', [40 130 220 190]);
set_param(read, 'moduleType', 'IO614', 'id', '1', 'channel', '1', ...
    'canType', 'CAN (HS)', 'useBusOut', 'on', ...
    'HasMulRead', 'Single Read from Buffer (FIFO)', ...
    'LabelInHex', 'on', 'ts', '0.001');

rxSelector = add_block('simulink/Signal Routing/Bus Selector', ...
    [path '/Rx Bus Selector'], 'Position', [260 130 275 220]);
set_param(rxSelector, 'OutputSignals', 'ID,Extended,Remote,Length,Data');
add_line(path, 'IO614 CAN FIFO Read Raw/2', 'Rx Bus Selector/1', ...
    'autorouting', 'on');

% Decode 0x500 and compute torque. Persistent state (pedal-demand bank,
% 1ms tick) lives inside this single MATLAB Function block -- there is no
% separate retention/status-cycle split here because there is no other
% consumer and no 5ms-cycle logic to protect from a fast CAN sender.
decodeFcnPath = [path '/Decode Throttle And Compute Torque'];
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    decodeFcnPath, 'Position', [340 30 620 220]);
setMatlabFunctionScript(decodeFcnPath, decodeThrottleScript());

add_block('simulink/Sources/Constant', ...
    [path '/Max Torque Nm'], 'Value', 'test_torque_max_nm', ...
    'SampleTime', '0.001', 'Position', [260 30 400 60]);

dataPresentIndex = 1; % IO614 CAN FIFO Read Raw port 1 = "Data present".
add_line(path, sprintf('IO614 CAN FIFO Read Raw/%d', dataPresentIndex), ...
    'Decode Throttle And Compute Torque/1', 'autorouting', 'on');
add_line(path, 'Rx Bus Selector/1', ...
    'Decode Throttle And Compute Torque/2', 'autorouting', 'on'); % ID
add_line(path, 'Rx Bus Selector/2', ...
    'Decode Throttle And Compute Torque/3', 'autorouting', 'on'); % Extended
add_line(path, 'Rx Bus Selector/3', ...
    'Decode Throttle And Compute Torque/4', 'autorouting', 'on'); % Remote
add_line(path, 'Rx Bus Selector/4', ...
    'Decode Throttle And Compute Torque/5', 'autorouting', 'on'); % Length
add_line(path, 'Rx Bus Selector/5', ...
    'Decode Throttle And Compute Torque/6', 'autorouting', 'on'); % Data
add_line(path, 'Max Torque Nm/1', ...
    'Decode Throttle And Compute Torque/7', 'autorouting', 'on');

% Pack the CarMaker inverter-telemetry pair (0x501/0x502) from the single
% scalar torque + ownership gate. torqueNm goes entirely into channel 1
% (channels 2-4 zero) so IO.c's MFE_CAN_TorqueRequestTotalNm four-way sum
% equals this model's one scalar exactly; the ownership gate is broadcast
% to all four ready bits so MFE_CAN_DriveActive's four-way OR reduces to
% the same single gate. No per-wheel torque vectoring is implied by using
% four wire slots -- that is purely CarMaker's already-built, unmodified
% wire contract (inverter_hil/docs/can_pedal_demand_frame_spec.md S5).
packFcnPath = [path '/Pack CarMaker Telemetry'];
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    packFcnPath, 'Position', [660 30 880 130]);
setMatlabFunctionScript(packFcnPath, packTelemetryScript());
add_line(path, 'Decode Throttle And Compute Torque/2', ...
    'Pack CarMaker Telemetry/1', 'autorouting', 'on'); % active
add_line(path, 'Decode Throttle And Compute Torque/3', ...
    'Pack CarMaker Telemetry/2', 'autorouting', 'on'); % torqueRequestNm

ids = [hex2dec('501'), hex2dec('502')];
names = {'Torque', 'Ready'};
for index = 1:2
    id = ids(index);
    y = 30 + 130 * (index - 1);
    packBlock = add_block('canlib/CAN Pack', ...
        sprintf('%s/CAN Pack 0x%03X', path, id), ...
        'Position', [920 y 1040 y + 35]);
    set_param(packBlock, 'DataFormat', 'raw data', 'MsgIDType', ...
        'Standard (11-bit identifier)', 'MsgIdentifier', num2str(id), ...
        'CANIDInput', 'off', 'MsgLength', '8', 'Remote', 'off', ...
        'BusOutput', 'off', 'Description', ...
        sprintf('%s payload, CarMaker inverter telemetry ID 0x%03X', ...
        names{index}, id));
    add_line(path, sprintf('Pack CarMaker Telemetry/%d', index), ...
        sprintf('CAN Pack 0x%03X/1', id), 'autorouting', 'on');

    % 1 ms cadence, matching the CAN Read/decode chain that feeds it (no
    % Rate Transition block in this minimal model). The documented
    % CarMaker inverter-telemetry wire contract
    % (can_pedal_demand_frame_spec.md S5) calls for 5 ms; nothing about
    % CarMaker's IO_In() receive loop requires that exact cadence, and a
    % faster, single-rate 1 ms transmit is simpler here and still well
    % within the PCAN link's headroom (0x500 already transmits at 10 ms
    % from the CarMaker side on the same bus).
    % enableInput left off (default): both frames transmit unconditionally
    % every ts -- no drop-mask/Tx-control logic in this minimal model.
    writer = add_block('speedgoatlib_IO614/CAN Write ', ...
        sprintf('%s/CAN Write 0x%03X', path, id), ...
        'Position', [1070 y 1230 y + 35]);
    set_param(writer, 'moduleType', 'IO614', 'id', '1', ...
        'channel', '1', 'canType', 'CAN (HS)', 'useBusIn', 'off', ...
        'numOfMsg', '1', 'enableStatusPort', 'on', 'enableInput', 'off', ...
        'ts', '0.001', 'UserData', uint32(id), 'UserDataPersistent', 'on', ...
        'Description', sprintf('Transmits CarMaker telemetry ID 0x%03X', id));
    add_line(path, sprintf('CAN Pack 0x%03X/1', id), ...
        sprintf('CAN Write 0x%03X/1', id), 'autorouting', 'on');
end

% Verification taps: getsignal(target, 'test_torque/CAN Torque Bridge', N)
% for each. Numbered in the order most useful to check first.
addVerificationOutport(path, 'ThrottlePercent', ...
    'Decode Throttle And Compute Torque/1', 1, [1280 30 1420 55]);
addVerificationOutport(path, 'TorqueActive', ...
    'Decode Throttle And Compute Torque/2', 2, [1280 70 1420 95]);
addVerificationOutport(path, 'TorqueRequestNm', ...
    'Decode Throttle And Compute Torque/3', 3, [1280 110 1420 135]);
addVerificationOutport(path, 'TorquePayloadBytes', ...
    'Pack CarMaker Telemetry/1', 4, [1280 150 1420 175]);
addVerificationOutport(path, 'ReadyPayloadBytes', ...
    'Pack CarMaker Telemetry/2', 5, [1280 190 1420 215]);
end

function addVerificationOutport(path, name, sourcePort, portNumber, position)
add_block('simulink/Sinks/Out1', [path '/' name], ...
    'Port', num2str(portNumber), 'Position', position);
add_line(path, sourcePort, [name '/1'], 'autorouting', 'on');
end

function clearSubsystem(path)
lineHandles = get_param(path, 'LineHandles');
fields = fieldnames(lineHandles);
for index = 1:numel(fields)
    handles = lineHandles.(fields{index});
    handles = handles(handles ~= -1);
    for handle = handles(:)'
        try %#ok<TRYNC>
            delete_line(handle);
        end
    end
end
blocks = find_system(path, 'SearchDepth', 1, 'Type', 'Block');
for index = 2:numel(blocks)
    delete_block(blocks{index});
end
end

function setMatlabFunctionScript(blockPath, script)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', '-and', 'Path', blockPath);
chart(1).Script = script;
end

function script = decodeThrottleScript()
script = sprintf([ ...
    'function [throttlePercent, torqueActive, torqueRequestNm] = ...\n' ...
    '    testTorqueDecodeStep(rxDataPresent, rxId, rxExtended, rxRemote, ...\n' ...
    '    rxLength, rxData, maxTorqueNm)\n' ...
    '%%#codegen\n' ...
    '%%TESTTORQUEDECODESTEP Decode CarMakerPedalDemand (CAN 0x500) with the\n' ...
    '%%same hardware-proven CRC-8/SAE-J1850 + alive-counter + 100ms\n' ...
    '%%freshness logic inverter_hil.slx uses (inverterhil.*). No PID, no\n' ...
    '%%per-wheel vectoring, no VCU state machine, and no proportional\n' ...
    '%%throttle-to-torque scaling either: torqueRequestNm is a fixed\n' ...
    '%%maxTorqueNm whenever CAN pedal ownership is currently held (fresh\n' ...
    '%%frame, CRC ok, alive counter advanced, Active=1), and exactly zero\n' ...
    '%%otherwise. throttlePercent is still decoded and exposed as a\n' ...
    '%%verification tap, it just no longer scales the torque value.\n' ...
    'persistent bank tickMs\n' ...
    'if isempty(bank)\n' ...
    '    bank = inverterhil.initialPedalDemandBank();\n' ...
    '    tickMs = uint32(0);\n' ...
    'end\n' ...
    'payload = uint8(rxData(:))'';\n' ...
    'frame = struct( ...\n' ...
    '    ''id'', uint32(rxId), ...\n' ...
    '    ''dlc'', uint8(rxLength), ...\n' ...
    '    ''payload'', payload, ...\n' ...
    '    ''isExtended'', logical(rxExtended), ...\n' ...
    '    ''isRemote'', logical(rxRemote), ...\n' ...
    '    ''drop'', ~logical(rxDataPresent));\n' ...
    'bank = inverterhil.receivePedalDemandFrame(bank, frame, tickMs);\n' ...
    'snapshot = inverterhil.pedalDemandSnapshot(bank, tickMs);\n' ...
    'throttlePercent = snapshot.throttlePercent;\n' ...
    'torqueActive = double(snapshot.ownsPedals);\n' ...
    'torqueRequestNm = torqueActive * maxTorqueNm;\n' ...
    'tickMs = tickMs + uint32(1);\n' ...
    'end\n']);
end

function script = packTelemetryScript()
script = sprintf([ ...
    'function [torquePayload, readyPayload] = testTorquePackStep( ...\n' ...
    '    torqueActive, torqueRequestNm)\n' ...
    '%%#codegen\n' ...
    '%%TESTTORQUEPACKSTEP Pack the CarMaker inverter-telemetry pair\n' ...
    '%%(0x501/0x502) CarMaker''s IO.c already decodes into\n' ...
    '%%MFE_CAN.TorqueRequestTotalNm / MFE_CAN.DriveActive. The entire\n' ...
    '%%scalar torque request goes in channel 1 (channels 2-4 zero) so the\n' ...
    '%%C-side four-way sum equals this model''s single scalar exactly; the\n' ...
    '%%ownership gate is broadcast to all four ready bits so the C-side\n' ...
    '%%four-way OR reduces to the same single gate.\n' ...
    'telemetry.torqueSetpointNm = [torqueRequestNm 0 0 0];\n' ...
    'telemetry.ready = logical([torqueActive torqueActive torqueActive torqueActive]);\n' ...
    '[torquePayload, readyPayload] = inverterhil.packCarMakerTelemetry(telemetry);\n' ...
    'end\n']);
end
