function validateCalibration(cal)
%VALIDATECALIBRATION Reject values that could energize or destabilize the model.

required = {'sampleTimeS', 'protocolProfileId', ...
    'torqueScaleNmPerCount', 'torqueScaleVerified', ...
    'dcLinkMinimumV', 'switchingFrequencyKHz', 'configErrorScope', ...
    'speedKp', 'speedKi', 'inertiaKgM2', 'dragNmPerRadS', ...
    'torqueConstantNmPerA', 'torqueLagS', 'torqueSlewNmPerS', ...
    'modelTorqueMinNm', 'modelTorqueMaxNm', 'motorShutdownC', ...
    'ascThresholdRpm', 'resetBackoffMaxS', 'speedMaxRpm', ...
    'modelCurrentMaxA', 'motorDerateStartC', 'motorDerateEndC', ...
    'motoringEfficiency', 'regenEfficiency', 'dcVoltageFloorV', ...
    'ambientTemperatureC', 'motorThermalTimeConstantS', ...
    'switchThermalTimeConstantS', 'motorThermalResistanceCPerW', ...
    'switchThermalResistanceCPerW', 'motorLossFraction', 'pedals', ...
    'guiHeartbeatTimeoutS'};
requireFields(cal, required, 'calibration');
if ~isstruct(cal.pedals) || ~isscalar(cal.pedals)
    invalid('pedals must be a scalar structure.');
end
requireFields(cal.pedals, ...
    {'releasedV', 'pressedV', 'minimumV', 'maximumV'}, ...
    'pedal calibration');

mustFinitePositive(cal.sampleTimeS, 'sampleTimeS');
mustFinitePositive(cal.dcLinkMinimumV, 'dcLinkMinimumV');
mustFinitePositive(cal.switchingFrequencyKHz, 'switchingFrequencyKHz');
mustFinitePositive(cal.resetBackoffMaxS, 'resetBackoffMaxS');
mustFinitePositive(cal.guiHeartbeatTimeoutS, 'guiHeartbeatTimeoutS');

if ~(isequal(cal.configErrorScope, uint8(0)) || ...
        isequal(cal.configErrorScope, uint8(1)))
    error('inverterhil:InvalidCalibration', ...
        'configErrorScope must be 0 (per-channel) or 1 (unit-wide).');
end

p = protocol();
allowedIds = {p.torqueProfiles.provisional512.id, ...
    p.torqueProfiles.vcu256.id};
if ~ischar(cal.protocolProfileId) || ...
        ~any(strcmp(cal.protocolProfileId, allowedIds))
    error('inverterhil:InvalidCalibration', ...
        'Protocol profile ID is not a versioned supported profile.');
end
if ~isnumeric(cal.torqueScaleNmPerCount) || ...
        ~isscalar(cal.torqueScaleNmPerCount) || ...
        ~isreal(cal.torqueScaleNmPerCount) || ...
        ~isfinite(cal.torqueScaleNmPerCount)
    invalid('torqueScaleNmPerCount must be a real finite numeric scalar.');
end
if ~(islogical(cal.torqueScaleVerified) || ...
        isnumeric(cal.torqueScaleVerified)) || ...
        ~isscalar(cal.torqueScaleVerified) || ...
        ~isreal(cal.torqueScaleVerified) || ...
        ~isfinite(double(cal.torqueScaleVerified)) || ...
        ~(double(cal.torqueScaleVerified) == 0 || ...
        double(cal.torqueScaleVerified) == 1)
    invalid('torqueScaleVerified must be logical 0 or 1.');
end
profile = p.torqueProfiles.provisional512;
if strcmp(cal.protocolProfileId, p.torqueProfiles.vcu256.id)
    profile = p.torqueProfiles.vcu256;
end
if cal.torqueScaleNmPerCount ~= profile.scaleNmPerCount || ...
        logical(cal.torqueScaleVerified) ~= profile.verified
    error('inverterhil:InvalidCalibration', ...
        'Protocol scale and verification state must match the profile ID.');
end

fourPositive = {'inertiaKgM2', 'torqueConstantNmPerA', 'torqueLagS', ...
    'torqueSlewNmPerS', 'motorShutdownC', 'ascThresholdRpm', ...
    'speedMaxRpm', 'modelCurrentMaxA', 'motoringEfficiency', ...
    'regenEfficiency', 'dcVoltageFloorV', ...
    'motorThermalTimeConstantS', 'switchThermalTimeConstantS', ...
    'motorThermalResistanceCPerW', 'switchThermalResistanceCPerW'};
for k = 1:numel(fourPositive)
    name = fourPositive{k};
    value = cal.(name);
    if ~isnumeric(value) || ~isequal(size(value), [1 4]) || ...
            ~isreal(value) || any(~isfinite(value)) || any(value <= 0)
        error('inverterhil:InvalidCalibration', ...
            '%s must contain four finite positive values.', name);
    end
end

fourFinite = {'speedKp', 'speedKi', 'dragNmPerRadS', ...
    'modelTorqueMinNm', 'modelTorqueMaxNm', ...
    'motorDerateStartC', 'motorDerateEndC', ...
    'ambientTemperatureC', 'motorLossFraction'};
for k = 1:numel(fourFinite)
    name = fourFinite{k};
    value = cal.(name);
    if ~isnumeric(value) || ~isequal(size(value), [1 4]) || ...
            ~isreal(value) || any(~isfinite(value))
        error('inverterhil:InvalidCalibration', ...
            '%s must contain four finite values.', name);
    end
end
nonnegative = {'speedKp', 'speedKi', 'dragNmPerRadS'};
for k = 1:numel(nonnegative)
    name = nonnegative{k};
    if any(cal.(name) < 0)
        error('inverterhil:InvalidCalibration', ...
            '%s values must be nonnegative.', name);
    end
end
if any(cal.modelTorqueMinNm >= cal.modelTorqueMaxNm)
    error('inverterhil:InvalidCalibration', ...
        'Each model torque minimum must be below its maximum.');
end
if any(cal.modelTorqueMinNm > 0) || any(cal.modelTorqueMaxNm < 0)
    error('inverterhil:InvalidCalibration', ...
        'Each model torque interval must include safe zero torque.');
end
if any(cal.motoringEfficiency > 1) || any(cal.regenEfficiency > 1)
    error('inverterhil:InvalidCalibration', ...
        'Motoring and regenerative efficiencies cannot exceed one.');
end
if any(cal.motorLossFraction < 0) || any(cal.motorLossFraction > 1)
    error('inverterhil:InvalidCalibration', ...
        'motorLossFraction values must be between zero and one.');
end
if any(cal.motorDerateStartC >= cal.motorDerateEndC) || ...
        any(cal.motorDerateEndC > cal.motorShutdownC)
    error('inverterhil:InvalidCalibration', ...
        ['Motor derating must start below its zero-permission endpoint, ' ...
        'which cannot exceed motor shutdown temperature.']);
end

pedalFields = {'releasedV', 'pressedV', 'minimumV', 'maximumV'};
for k = 1:numel(pedalFields)
    value = cal.pedals.(pedalFields{k});
    if ~isnumeric(value) || ~isequal(size(value), [1 4]) || ~isreal(value)
        error('inverterhil:InvalidCalibration', ...
            'Pedal calibration fields must contain four values.');
    end
end
if any(~isfinite(cal.pedals.minimumV)) || ...
        any(~isfinite(cal.pedals.maximumV)) || ...
        any(cal.pedals.minimumV < 0) || ...
        any(cal.pedals.maximumV > 5) || ...
        any(cal.pedals.minimumV >= cal.pedals.maximumV)
    error('inverterhil:InvalidCalibration', ...
        'Pedal clamps must be finite, ordered, and within 0-5 V.');
end
pedalValues = {'releasedV', 'pressedV'};
for k = 1:numel(pedalValues)
    name = pedalValues{k};
    value = cal.pedals.(name);
    if ~isreal(value) || any(isinf(value))
        error('inverterhil:InvalidCalibration', ...
            '%s may use NaN only for an unverified value.', name);
    end
    verified = ~isnan(value);
    if any(value(verified) < cal.pedals.minimumV(verified)) || ...
            any(value(verified) > cal.pedals.maximumV(verified))
        error('inverterhil:InvalidCalibration', ...
            '%s values must be inside their channel clamps.', name);
    end
end
end

function mustFinitePositive(value, name)
if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
        ~isfinite(value) || value <= 0
    error('inverterhil:InvalidCalibration', ...
        '%s must be a finite positive scalar.', name);
end
end

function requireFields(value, fields, label)
if ~isstruct(value) || ~isscalar(value)
    invalid('%s must be a scalar structure.', label);
end
for k = 1:numel(fields)
    if ~isfield(value, fields{k})
        invalid('%s is missing field %s.', label, fields{k});
    end
end
end

function invalid(message, varargin)
error('inverterhil:InvalidCalibration', message, varargin{:});
end
