function contract = parameterContract()
%PARAMETERCONTRACT Declarative logical-name contract for GUI-owned parameters.
%
%   Every GUI control refers to a logical name only. Each entry carries BOTH a
%   nested-structure backing path and an independent flat-scalar backing path
%   because plan open decision 16 (field-level SETPARAM support in R2024b
%   Simulink Real-Time) is UNRESOLVED and the Part 2 spike has not been run.
%   INVERTERHILGUI.DISCOVERCONTRACT selects whichever backing the connected
%   application actually exposes, so callbacks never depend on the answer.
%
%   Fields per entry:
%     name       - logical name used by every callback
%     type       - 'double', 'logical', 'uint8', 'uint16' or 'uint32'
%     minimum    - inclusive lower clamp bound
%     maximum    - inclusive upper clamp bound
%     structPath - nested-structure target parameter path
%     flatPath   - independent flat-scalar target parameter path
%     required   - true when a missing path is a version mismatch
%     group      - control-policy owner group

entry = @(varargin) makeEntry(varargin{:});

contract = [ ...
    entry('pedals.throttle', 'double', 0, 1, ...
        'hil_cmd.pedals.throttle', 'hil_cmd_pedals_throttle', ...
        true, 'pedals'); ...
    entry('pedals.brake', 'double', 0, 1, ...
        'hil_cmd.pedals.brake', 'hil_cmd_pedals_brake', ...
        true, 'pedals'); ...
    entry('steering.angle_deg', 'double', -780, 780, ...
        'hil_cmd.steering.angle_deg', 'hil_cmd_steering_angle_deg', ...
        true, 'sensorStimulus'); ...
    entry('steering.dropout', 'logical', 0, 1, ...
        'hil_cmd.steering.dropout', 'hil_cmd_steering_dropout', ...
        true, 'sensorStimulus'); ...
    entry('steering.stale', 'logical', 0, 1, ...
        'hil_cmd.steering.stale', 'hil_cmd_steering_stale', ...
        true, 'sensorStimulus'); ...
    entry('steering.malformed', 'logical', 0, 1, ...
        'hil_cmd.steering.malformed', 'hil_cmd_steering_malformed', ...
        true, 'sensorStimulus'); ...
    entry('steering.invalid_status', 'logical', 0, 1, ...
        'hil_cmd.steering.invalid_status', ...
        'hil_cmd_steering_invalid_status', true, 'sensorStimulus'); ...
    entry('steering.angle_sentinel', 'logical', 0, 1, ...
        'hil_cmd.steering.angle_sentinel', ...
        'hil_cmd_steering_angle_sentinel', true, 'sensorStimulus'); ...
    entry('steering.speed_sentinel', 'logical', 0, 1, ...
        'hil_cmd.steering.speed_sentinel', ...
        'hil_cmd_steering_speed_sentinel', true, 'sensorStimulus'); ...
    entry('steering.calibration_sequence', 'uint32', 0, 4294967295, ...
        'hil_cmd.steering.calibration_sequence', ...
        'hil_cmd_steering_calibration_sequence', true, 'calibration'); ...
    entry('imu.dropout', 'logical', 0, 1, ...
        'hil_cmd.imu.dropout', 'hil_cmd_imu_dropout', ...
        true, 'sensorStimulus'); ...
    entry('imu.stale', 'logical', 0, 1, ...
        'hil_cmd.imu.stale', 'hil_cmd_imu_stale', ...
        true, 'sensorStimulus'); ...
    entry('imu.malformed', 'logical', 0, 1, ...
        'hil_cmd.imu.malformed', 'hil_cmd_imu_malformed', ...
        true, 'sensorStimulus'); ...
    entry('digital.main_button', 'logical', 0, 1, ...
        'hil_cmd.digital.main_button', 'hil_cmd_digital_main_button', ...
        true, 'digital'); ...
    entry('digital.cooling_switch', 'logical', 0, 1, ...
        'hil_cmd.digital.cooling_switch', ...
        'hil_cmd_digital_cooling_switch', true, 'digital'); ...
    entry('digital.shutdown_feedback', 'logical', 0, 1, ...
        'hil_cmd.digital.shutdown_feedback', ...
        'hil_cmd_digital_shutdown_feedback', true, 'digital'); ...
    entry('digital.precharge_sequence', 'uint32', 0, 4294967295, ...
        'hil_cmd.digital.precharge_sequence', ...
        'hil_cmd_digital_precharge_sequence', true, 'momentary'); ...
    entry('digital.main_button_sequence', 'uint32', 0, 4294967295, ...
        'hil_cmd.digital.main_button_sequence', ...
        'hil_cmd_digital_main_button_sequence', true, 'momentary'); ...
    entry('electrical.dc_link12_v', 'double', 0, 1023.984375, ...
        'hil_cmd.dc_link12_v', 'hil_cmd_dc_link12_v', ...
        true, 'electrical'); ...
    entry('electrical.dc_link34_v', 'double', 0, 1023.984375, ...
        'hil_cmd.dc_link34_v', 'hil_cmd_dc_link34_v', ...
        true, 'electrical'); ...
    entry('inverter1.load_nm', 'double', -200, 200, ...
        'hil_cmd.inverter(1).load_nm', 'hil_cmd_inverter1_load_nm', ...
        true, 'plant'); ...
    entry('inverter2.load_nm', 'double', -200, 200, ...
        'hil_cmd.inverter(2).load_nm', 'hil_cmd_inverter2_load_nm', ...
        true, 'plant'); ...
    entry('inverter3.load_nm', 'double', -200, 200, ...
        'hil_cmd.inverter(3).load_nm', 'hil_cmd_inverter3_load_nm', ...
        true, 'plant'); ...
    entry('inverter4.load_nm', 'double', -200, 200, ...
        'hil_cmd.inverter(4).load_nm', 'hil_cmd_inverter4_load_nm', ...
        true, 'plant'); ...
    entry('inverter1.connected', 'logical', 0, 1, ...
        'hil_cmd.inverter(1).connected', 'hil_cmd_inverter1_connected', ...
        true, 'plant'); ...
    entry('inverter2.connected', 'logical', 0, 1, ...
        'hil_cmd.inverter(2).connected', 'hil_cmd_inverter2_connected', ...
        true, 'plant'); ...
    entry('inverter3.connected', 'logical', 0, 1, ...
        'hil_cmd.inverter(3).connected', 'hil_cmd_inverter3_connected', ...
        true, 'plant'); ...
    entry('inverter4.connected', 'logical', 0, 1, ...
        'hil_cmd.inverter(4).connected', 'hil_cmd_inverter4_connected', ...
        true, 'plant'); ...
    entry('inverter1.fault_mask', 'uint32', 0, 4294967295, ...
        'hil_cmd.inverter(1).fault_mask', 'hil_cmd_inverter1_fault_mask', ...
        true, 'fault'); ...
    entry('inverter2.fault_mask', 'uint32', 0, 4294967295, ...
        'hil_cmd.inverter(2).fault_mask', 'hil_cmd_inverter2_fault_mask', ...
        true, 'fault'); ...
    entry('inverter3.fault_mask', 'uint32', 0, 4294967295, ...
        'hil_cmd.inverter(3).fault_mask', 'hil_cmd_inverter3_fault_mask', ...
        true, 'fault'); ...
    entry('inverter4.fault_mask', 'uint32', 0, 4294967295, ...
        'hil_cmd.inverter(4).fault_mask', 'hil_cmd_inverter4_fault_mask', ...
        true, 'fault'); ...
    entry('can.drop_control_mask', 'uint8', 0, 255, ...
        'hil_cmd.can.drop_control_mask', ...
        'hil_cmd_can_drop_control_mask', true, 'canFault'); ...
    entry('can.drop_status_mask', 'uint16', 0, 65535, ...
        'hil_cmd.can.drop_status_mask', ...
        'hil_cmd_can_drop_status_mask', true, 'canFault'); ...
    entry('gui_heartbeat', 'uint32', 0, 4294967295, ...
        'hil_cmd.gui_heartbeat', 'hil_cmd_gui_heartbeat', ...
        true, 'heartbeat'); ...
    entry('pedals.plausibility_override', 'logical', 0, 1, ...
        'hil_cmd.pedals.plausibility_override', ...
        'hil_cmd_pedals_plausibility_override', false, 'pedals'); ...
    entry('cal.pedals.released_v1', 'double', 0, 5, ...
        'hil_cal.pedals.releasedV(1)', 'hil_cal_pedals_released_v1', ...
        false, 'calibration'); ...
    entry('cal.pedals.released_v2', 'double', 0, 5, ...
        'hil_cal.pedals.releasedV(2)', 'hil_cal_pedals_released_v2', ...
        false, 'calibration'); ...
    entry('cal.pedals.released_v3', 'double', 0, 5, ...
        'hil_cal.pedals.releasedV(3)', 'hil_cal_pedals_released_v3', ...
        false, 'calibration'); ...
    entry('cal.pedals.released_v4', 'double', 0, 5, ...
        'hil_cal.pedals.releasedV(4)', 'hil_cal_pedals_released_v4', ...
        false, 'calibration'); ...
    entry('cal.pedals.pressed_v1', 'double', 0, 5, ...
        'hil_cal.pedals.pressedV(1)', 'hil_cal_pedals_pressed_v1', ...
        false, 'calibration'); ...
    entry('cal.pedals.pressed_v2', 'double', 0, 5, ...
        'hil_cal.pedals.pressedV(2)', 'hil_cal_pedals_pressed_v2', ...
        false, 'calibration'); ...
    entry('cal.pedals.pressed_v3', 'double', 0, 5, ...
        'hil_cal.pedals.pressedV(3)', 'hil_cal_pedals_pressed_v3', ...
        false, 'calibration'); ...
    entry('cal.pedals.pressed_v4', 'double', 0, 5, ...
        'hil_cal.pedals.pressedV(4)', 'hil_cal_pedals_pressed_v4', ...
        false, 'calibration')];
end

function item = makeEntry(name, type, minimum, maximum, structPath, ...
        flatPath, required, group)
item = struct( ...
    'name', name, ...
    'type', type, ...
    'minimum', minimum, ...
    'maximum', maximum, ...
    'structPath', structPath, ...
    'flatPath', flatPath, ...
    'required', logical(required), ...
    'group', group);
end
