function input = defaultPlantInput(cal)
%DEFAULTPLANTINPUT Return a safe, quiescent four-channel plant input.

if nargin < 1
    cal = inverterhil.defaultCalibration();
end
inverterhil.validateCalibration(cal);
p = inverterhil.protocol();

channel = struct( ...
    'mode', p.state.idle, ...
    'ready', false, ...
    'zeroTorque', true, ...
    'activeFault', 'none', ...
    'commandTorqueTimeout', false, ...
    'commandErrorTimeout', false, ...
    'authorityReason', 'default_safe', ...
    'speedSetpointRpm', 0, ...
    'torqueLimitPositiveNm', 0, ...
    'torqueLimitNegativeNm', 0, ...
    'rawTorquePosCounts', int16(0), ...
    'rawTorqueNegCounts', int16(0), ...
    'loadTorqueNm', 0, ...
    'dcLinkV', 400);

input.protocolProfileId = cal.protocolProfileId;
input.channels = repmat(channel, 1, 4);
end
