classdef TestModelArtifacts < matlab.unittest.TestCase
    properties (SetAccess = private)
        Root
        Model = 'inverter_hil'
        Hardware
    end

    methods (TestClassSetup)
        function loadIoDisconnectedArtifact(testCase)
            testFolder = fileparts(mfilename('fullpath'));
            repoRoot = fileparts(fileparts(testFolder));
            testCase.Root = fullfile(repoRoot, 'inverter_hil');
            addpath(testCase.Root);
            testCase.Root = inverter_hil_setup();
            testCase.assertEqual(version('-release'), '2024b');
            load_system(fullfile(testCase.Root, 'inverter_hil.slx'));
            testCase.Hardware = [testCase.Model ...
                '/Hardware I O - PRE-FLIGHT DISABLED'];
            testCase.assertEqual(get_param(testCase.Hardware, 'Commented'), 'on');
            set_param(testCase.Model, 'SimulationCommand', 'update');
        end
    end

    methods (TestClassTeardown)
        function closeArtifact(testCase)
            if bdIsLoaded(testCase.Model)
                close_system(testCase.Model, 0);
            end
            libraries = {'speedgoatlib_IO183', 'speedgoatlib_IO614'};
            for index = 1:numel(libraries)
                if bdIsLoaded(libraries{index})
                    close_system(libraries{index}, 0);
                end
            end
        end
    end

    methods (Test)
        function releaseGuardsPrecedeArtifactMutation(testCase)
            setupText = fileread(fullfile(testCase.Root, ...
                'inverter_hil_setup.m'));
            testCase.verifyTrue(contains(setupText, "version('-release')"));
            testCase.verifyTrue(contains(setupText, "'2024b'"));
            testCase.verifyTrue(contains(setupText, ...
                "'inverterhil:WrongRelease'"));

            buildText = fileread(fullfile(testCase.Root, ...
                'build_inverter_hil_model.m'));
            setupPosition = strfind(buildText, 'root = inverter_hil_setup()');
            mutationPosition = strfind(buildText, ...
                'prepareOutput(modelPath, force)');
            testCase.verifyNumElements(setupPosition, 1);
            testCase.verifyNumElements(mutationPosition, 1);
            testCase.verifyLessThan(setupPosition, mutationPosition, ...
                ['The release guard must run before an existing model or ' ...
                'dictionary can be deleted.']);
        end

        function modelLoadsAndUpdatesWithIoDisconnected(testCase)
            testCase.verifyTrue(bdIsLoaded(testCase.Model));
            testCase.verifyEqual(get_param(testCase.Hardware, 'Commented'), 'on');
            testCase.verifyEmpty(find_system(testCase.Hardware, ...
                'SearchDepth', 1, 'BlockType', 'Inport'));
            testCase.verifyEmpty(find_system(testCase.Hardware, ...
                'SearchDepth', 1, 'BlockType', 'Outport'));
            testCase.verifyWarningFree(@() set_param(testCase.Model, ...
                'SimulationCommand', 'update'));
        end

        function executionAndDictionaryAttachmentAreExact(testCase)
            testCase.verifyEqual(get_param(testCase.Model, 'SolverType'), ...
                'Fixed-step');
            testCase.verifyEqual(get_param(testCase.Model, 'Solver'), ...
                'FixedStepDiscrete');
            testCase.verifyEqual(get_param(testCase.Model, 'FixedStep'), ...
                '0.001');
            testCase.verifyEqual(get_param(testCase.Model, ...
                'SystemTargetFile'), 'speedgoat.tlc');
            testCase.verifyEqual(get_param(testCase.Model, ...
                'DataDictionary'), 'inverter_hil.sldd');
        end

        function requiredArchitectureAndChannelsAreDistinct(testCase)
            required = {'Test Inputs', 'Fault Injection', ...
                'Pedal Sensor Emulation', 'VCU Digital Interface', ...
                'IO614 CAN Interface', 'Ephorus Channel 1', ...
                'Ephorus Channel 2', 'Ephorus Channel 3', ...
                'Ephorus Channel 4', 'Ephorus System Status', ...
                'Measurements and Logging', ...
                'Hardware I O - PRE-FLIGHT DISABLED'};
            for index = 1:numel(required)
                path = [testCase.Model '/' required{index}];
                testCase.verifyNotEqual(getSimulinkBlockHandle(path), -1, ...
                    sprintf('Missing required architecture block %s.', path));
                testCase.verifyEqual(get_param(path, 'BlockType'), 'SubSystem');
            end

            channels = arrayfun(@(index) getSimulinkBlockHandle(sprintf( ...
                '%s/Ephorus Channel %d', testCase.Model, index)), 1:4);
            testCase.verifyNumElements(unique(channels), 4);
        end

        function hardwareBoundaryHasExactResolvedInstalledLinks(testCase)
            load_system('speedgoatlib_IO183');
            load_system('speedgoatlib_IO614');
            expected = { ...
                'speedgoatlib_IO183/Setup'; ...
                'speedgoatlib_IO183/Analog Input'; ...
                'speedgoatlib_IO183/Analog Output'; ...
                'speedgoatlib_IO183/Digital Input'; ...
                'speedgoatlib_IO183/Digital Output'; ...
                'speedgoatlib_IO614/CAN and LIN Setup '; ...
                'speedgoatlib_IO614/CAN Read '; ...
                'speedgoatlib_IO614/CAN Status '};
            expected = [expected; repmat( ...
                {'speedgoatlib_IO614/CAN Write '}, 9, 1)];
            for index = 1:numel(expected)
                testCase.verifyNotEqual(getSimulinkBlockHandle(expected{index}), -1, ...
                    sprintf('Installed library path is absent: [%s].', ...
                    expected{index}));
            end

            blocks = find_system(testCase.Hardware, 'LookUnderMasks', 'all', ...
                'FollowLinks', 'on', 'Type', 'Block');
            references = cellfun(@(block) get_param(block, 'ReferenceBlock'), ...
                blocks, 'UniformOutput', false);
            linked = blocks(~cellfun(@isempty, references));
            references = references(~cellfun(@isempty, references));
            testCase.verifyNumElements(linked, 17);
            testCase.verifyEqual(sort(references(:)), sort(expected(:)));
            for index = 1:numel(linked)
                testCase.verifyEqual(get_param(linked{index}, 'LinkStatus'), ...
                    'resolved', sprintf('Unresolved link: %s.', linked{index}));
            end
        end

        function io183SafetyAndAllocationAreExact(testCase)
            setup = [testCase.Hardware '/IO183 Setup'];
            ao = [testCase.Hardware '/IO183 AO01-AO04 Safe Zero'];
            ai = [testCase.Hardware '/IO183 AI01-AI04 Rail Monitor'];
            digitalOut = [testCase.Hardware ...
                '/IO183 DIO01-DIO08 Safe Zero'];
            digitalIn = [testCase.Hardware ...
                '/IO183 DIO09-DIO13 VCU Monitor'];

            TestModelArtifacts.verifyParameters(testCase, setup, { ...
                'parDaSimult', 'on'; ...
                'parAdCoupling', 'Single Ended'; ...
                'parAdRange', '0..5V'; ...
                'parAdChannelLow', '1'; ...
                'parAdChannelHigh', '4'; ...
                'parDaChannels', '[1 2 3 4]'; ...
                'parDaRange', '0..5V'; ...
                'parDaInit', '[0 0 0 0]'; ...
                'parDaReset', '[0 0 0 0]'; ...
                'parDoChannels', '[1 2 3 4 5 6 7 8]'; ...
                'parDoInit', '[0 0 0 0 0 0 0 0]'; ...
                'parDoReset', '[0 0 0 0 0 0 0 0]'; ...
                'parDiChannels', '[9 10 11 12 13]'; ...
                'parIOPullReferenceFront', 'Pull-down'});
            TestModelArtifacts.verifyParameters(testCase, ao, { ...
                'parSampTime', '0.001'; ...
                'parDaSimult', 'on'; ...
                'parDaChannels', '[1 2 3 4]'; ...
                'parDaInit', '[0 0 0 0]'; ...
                'parDaReset', '[0 0 0 0]'});
            TestModelArtifacts.verifyParameters(testCase, ai, { ...
                'parSampTime', '0.001'; ...
                'parAdChannelLow', '1'; ...
                'parAdChannelHigh', '4'});
            TestModelArtifacts.verifyParameters(testCase, digitalOut, { ...
                'parSampTime', '0.001'; ...
                'parDoChannels', '[1 2 3 4 5 6 7 8]'; ...
                'parDoInit', '[0 0 0 0 0 0 0 0]'; ...
                'parDoReset', '[0 0 0 0 0 0 0 0]'});
            TestModelArtifacts.verifyParameters(testCase, digitalIn, { ...
                'parSampTime', '0.001'; ...
                'parDiChannels', '[9 10 11 12 13]'});
        end

        function io614CanAndOrderedWritesAreExact(testCase)
            setup = [testCase.Hardware '/IO614 CAN Setup'];
            read = [testCase.Hardware '/IO614 CAN FIFO Read Raw'];
            status = [testCase.Hardware '/IO614 CAN Diagnostics'];
            TestModelArtifacts.verifyParameters(testCase, setup, { ...
                'moduleType', 'IO614'; ...
                'id', '1'; ...
                'canChn1', 'CAN (HS)'; ...
                'canChn2', 'Disabled'; ...
                'canChn3', 'Disabled'; ...
                'canChn4', 'Disabled'; ...
                'arbBdrChn1', '1.0 MBaud'});
            TestModelArtifacts.verifyParameters(testCase, read, { ...
                'moduleType', 'IO614'; ...
                'id', '1'; ...
                'channel', '1'; ...
                'canType', 'CAN (HS)'; ...
                'useBusOut', 'off'; ...
                'HasMulRead', 'Single Read from Buffer (FIFO)'; ...
                'ts', '0.001'});
            TestModelArtifacts.verifyParameters(testCase, status, { ...
                'moduleType', 'IO614'; ...
                'id', '1'; ...
                'channel', '1'; ...
                'canType', 'CAN (HS)'; ...
                'autoRecovery', 'off'; ...
                'ts', '0.001'});

            expectedIds = uint32(hex2dec({'383', '385', '393', '395', ...
                '3A3', '3A5', '3B3', '3B5', '400'})).';
            actualIds = zeros(1, 9, 'uint32');
            for index = 1:numel(expectedIds)
                path = sprintf('%s/CAN Write 0x%03X', testCase.Hardware, ...
                    expectedIds(index));
                testCase.verifyNotEqual(getSimulinkBlockHandle(path), -1);
                userData = get_param(path, 'UserData');
                testCase.verifyClass(userData, 'uint32');
                actualIds(index) = userData;
                TestModelArtifacts.verifyParameters(testCase, path, { ...
                    'moduleType', 'IO614'; ...
                    'id', '1'; ...
                    'channel', '1'; ...
                    'canType', 'CAN (HS)'; ...
                    'useBusIn', 'off'; ...
                    'numOfMsg', '1'; ...
                    'enableStatusPort', 'on'; ...
                    'ts', '0.005'; ...
                    'UserDataPersistent', 'on'});
            end
            testCase.verifyEqual(actualIds, expectedIds, ...
                'CAN Write UserData IDs must retain status-cycle order.');
        end

        function dictionaryContractAndSafeDefaultsAreExact(testCase)
            dictionary = Simulink.data.dictionary.open(fullfile( ...
                testCase.Root, 'inverter_hil.sldd'));
            cleanup = onCleanup(@() close(dictionary)); %#ok<NASGU>
            section = getSection(dictionary, 'Design Data');

            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_model_release'), 'R2024b');
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_base_sample_s'), 0.001);
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_status_sample_s'), 0.005);
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_pedals_throttle'), 0);
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_pedals_brake'), 0);
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_digital'), false(1, 8));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_dc_link_v'), [0 0]);
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_load_nm'), zeros(1, 4));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_connected'), true(1, 4));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_fault_mask'), zeros(1, 4, 'uint32'));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_cmd_gui_heartbeat'), uint32(0));

            released = TestModelArtifacts.value(section, ...
                'hil_cal_pedal_released_v');
            pressed = TestModelArtifacts.value(section, ...
                'hil_cal_pedal_pressed_v');
            testCase.verifyEqual(size(released), [1 4]);
            testCase.verifyEqual(size(pressed), [1 4]);
            testCase.verifyTrue(all(isnan(released)));
            testCase.verifyTrue(all(isnan(pressed)));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_safe_analog_reset_v'), zeros(1, 4));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_safe_digital_reset'), false(1, 8));

            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_control_can_ids'), uint32(hex2dec( ...
                {'186', '196', '1A6', '1B6'})));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_status_can_ids'), uint32(hex2dec( ...
                {'383', '385', '393', '395', '3A3', '3A5', ...
                '3B3', '3B5', '400'})));
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_torque_profile_id'), ...
                'ephorus3-v1.03-provisional-1over512');
            testCase.verifyEqual(TestModelArtifacts.value(section, ...
                'hil_torque_scale_nm_per_count'), 1 / 512);
            testCase.verifyFalse(TestModelArtifacts.value(section, ...
                'hil_torque_scale_verified'));
            testCase.verifyFalse(TestModelArtifacts.value(section, ...
                'hil_hardware_preflight_complete'));
            testCase.verifyTrue(TestModelArtifacts.value(section, ...
                'hil_torque_results_provisional'));
        end

        function preflightGateIsEnforcedByTopology(testCase)
            dictionary = Simulink.data.dictionary.open(fullfile( ...
                testCase.Root, 'inverter_hil.sldd'));
            cleanup = onCleanup(@() close(dictionary)); %#ok<NASGU>
            section = getSection(dictionary, 'Design Data');
            testCase.verifyFalse(TestModelArtifacts.value(section, ...
                'hil_hardware_preflight_complete'));
            testCase.verifyEqual(get_param(testCase.Hardware, 'Commented'), 'on');
            initFcn = get_param(testCase.Model, 'InitFcn');
            testCase.verifyTrue(contains(initFcn, ...
                'inverterhil.enforceHardwarePreflight'));
            inverterhil.enforceHardwarePreflight(testCase.Model);
            set_param(testCase.Hardware, 'Commented', 'off');
            restore = onCleanup(@() set_param(testCase.Hardware, ...
                'Commented', 'on')); %#ok<NASGU>
            testCase.verifyError(@() inverterhil.enforceHardwarePreflight( ...
                testCase.Model), 'inverterhil:HardwarePreflightOpen');
        end

        function generatedArtifactsAreIgnoredRepositoryWide(testCase)
            text = fileread(fullfile(testCase.Root, '.gitignore'));
            lines = strip(splitlines(string(text)));
            expected = [".simulink/"; "slprj/"; "*.slxc"; ...
                "*_sg_rtw/"; "*_grt_rtw/"; "*_ert_rtw/"];
            for index = 1:numel(expected)
                testCase.verifyTrue(any(lines == expected(index)), ...
                    sprintf('Missing repository-wide ignore rule: %s', ...
                    expected(index)));
            end
        end

        function annotationDoesNotOverclaimFunctionalCore(testCase)
            channelPaths = arrayfun(@(index) sprintf( ...
                '%s/Ephorus Channel %d', testCase.Model, index), 1:4, ...
                'UniformOutput', false);
            scaffoldOnly = true;
            for index = 1:numel(channelPaths)
                blocks = find_system(channelPaths{index}, 'SearchDepth', 1, ...
                    'Type', 'Block');
                blockTypes = get_param(blocks(2:end), 'BlockType');
                allowed = {'Inport', 'Outport', 'Terminator', 'Constant'};
                scaffoldOnly = scaffoldOnly && all(ismember(blockTypes, allowed));
                testCase.verifyEqual(sum(strcmp(blockTypes, 'Inport')), 4);
                testCase.verifyEqual(sum(strcmp(blockTypes, 'Terminator')), 4);
                testCase.verifyEqual(sum(strcmp(blockTypes, 'Constant')), 3);
                testCase.verifyEqual(sum(strcmp(blockTypes, 'Outport')), 3);
            end
            testCase.verifyTrue(scaffoldOnly, ...
                'Channel topology must be classified from its saved contents.');

            annotations = find_system(testCase.Model, 'FindAll', 'on', ...
                'Type', 'annotation');
            names = get_param(annotations, 'Name');
            if ischar(names)
                names = {names};
            end
            claimsActiveMil = any(cellfun(@(name) contains(name, ...
                'MIL architecture active'), names));
            testCase.verifyFalse(scaffoldOnly && claimsActiveMil, ...
                ['The annotation claims an active MIL architecture, but each ' ...
                'channel terminates every input and emits only safe constants.']);
        end
    end

    methods (Static, Access = private)
        function verifyParameters(testCase, block, expected)
            for index = 1:size(expected, 1)
                testCase.verifyEqual(get_param(block, expected{index, 1}), ...
                    expected{index, 2}, sprintf('%s parameter %s differs.', ...
                    block, expected{index, 1}));
            end
        end

        function result = value(section, name)
            entry = getEntry(section, name);
            result = getValue(entry);
            if isa(result, 'Simulink.Parameter')
                result = result.Value;
            end
        end
    end
end
