function add_virtual_vcu_to_model(modelPath)
%ADD_VIRTUAL_VCU_TO_MODEL Add the minimal Module 3 / Port A bench boundary.
if ~strcmp(version('-release'), '2024b')
    error('virtualvcu:WrongRelease', 'Build with MATLAB R2024b only.');
end
root = fileparts(fileparts(mfilename('fullpath')));
addpath(root);
if nargin < 1
    modelPath = fullfile(fileparts(root), 'inverter_hil', 'inverter_hil.slx');
end
model = 'inverter_hil';
load_system(modelPath);
cleanup = onCleanup(@() close_system(model, 0));
if getSimulinkBlockHandle([model '/Virtual VCU']) ~= -1
    return;
end
path = [model '/Virtual VCU'];
add_block('simulink/Ports & Subsystems/Subsystem', path, ...
    'Position', [960 80 1190 230], ...
    'Description', 'Virtual VCU: IO183 Module 3 and IO614 Port A (CAN channel 2).');
open_system(path);
add_block('speedgoatlib_IO183/Setup', [path '/IO183 Module 3 Setup'], ...
    'Position', [25 25 190 90]);
set_param([path '/IO183 Module 3 Setup'], 'parModuleId', '3', ...
    'parPciSlot', '-1', 'parDaSimult', 'on', ...
    'parAdCoupling', 'Single Ended', 'parAdRange', '0..5V', ...
    'parAdChannelLow', '1', 'parAdChannelHigh', '4', ...
    'parDaChannels', '[1 2 3 4]', 'parDaRange', '0..5V', ...
    'parDaInit', '[0 0 0 0]', 'parDaReset', '[0 0 0 0]', ...
    'parDoChannels', '[1 2 3 4 5 6 7 8]', ...
    'parDoInit', '[0 0 0 0 0 0 0 0]', ...
    'parDoReset', '[0 0 0 0 0 0 0 0]', ...
    'parDiChannels', '[1 2 3 4 5 6 7 8]', ...
    'parIOPullReferenceFront', 'Pull-down');
ai = add_block('speedgoatlib_IO183/Analog Input', [path '/Module 3 AI01-AI04'], ...
    'Position', [25 120 190 175]);
set_param(ai, 'parModuleId', '3', 'parSampTime', '0.001', ...
    'parAdChannelLow', '1', 'parAdChannelHigh', '4');
di = add_block('speedgoatlib_IO183/Digital Input', [path '/Module 3 DI01-DI08'], ...
    'Position', [25 205 190 260]);
set_param(di, 'parModuleId', '3', 'parSampTime', '0.001', ...
    'parDiChannels', '[1 2 3 4 5 6 7 8]');
add_block('simulink/Signal Routing/Mux', [path '/Module 3 Analog Mux'], ...
    'Inputs', '4', 'Position', [220 120 240 175]);
for k = 1:4
    add_line(path, sprintf('Module 3 AI01-AI04/%d', k), ...
        sprintf('Module 3 Analog Mux/%d', k));
end
% IO614 has one module-level setup. The main inverter boundary owns it and
% enables both channel 1/Port B and channel 2/Port A at the same bitrate.
read = add_block('speedgoatlib_IO614/CAN Read ', [path '/Port A CAN FIFO Read'], ...
    'Position', [270 120 440 180]);
set_param(read, 'moduleType', 'IO614', 'id', '1', 'channel', '2', ...
    'canType', 'CAN (HS)', 'useBusOut', 'on', ...
    'HasMulRead', 'Single Read from Buffer (FIFO)', 'LabelInHex', 'on', ...
    'ts', '0.001');
selector = add_block('simulink/Signal Routing/Bus Selector', ...
    [path '/Port A RX Selector'], 'Position', [475 115 490 250]);
set_param(selector, 'OutputSignals', 'ID,Extended,Remote,Length,Data');
add_line(path, 'Port A CAN FIFO Read/2', 'Port A RX Selector/1');
fcn = add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [path '/Virtual VCU LV_ON'], 'Position', [520 25 750 260]);
setMatlabFunctionScript(fcn, vcuScript());
ports = get_param(fcn, 'PortHandles');
if numel(ports.Inport) ~= 1 || numel(ports.Outport) ~= 1
    error('virtualvcu:ChartInterface', 'Expected 1 input/1 output.');
end
add_line(path, 'Module 3 Analog Mux/1', 'Virtual VCU LV_ON/1');
add_block('simulink/Signal Routing/Demux', [path '/VCU Payload Split'], ...
    'Outputs', '[8 8 8 8 8]', 'Position', [780 25 800 200]);
add_line(path, 'Virtual VCU LV_ON/1', 'VCU Payload Split/1');
% The CAN receive path remains physical and observable. No-data is preserved
% as false/unknown; it is not converted into a fabricated status frame.
for k = 1:5
    add_block('simulink/Signal Routing/Goto', ...
        [path sprintf('/Port A RX Field %d', k)], ...
        'GotoTag', sprintf('VirtualVcuRxField%d', k), 'TagVisibility', 'global', ...
        'Position', [520 285 + 25*k 680 305 + 25*k]);
    add_line(path, sprintf('Port A RX Selector/%d', k), ...
        sprintf('Port A RX Field %d/1', k));
end
add_block('simulink/Sinks/Terminator', [path '/Module 3 Digital Monitor'], ...
    'Position', [220 215 240 235]);
add_line(path, 'Module 3 DI01-DI08/1', 'Module 3 Digital Monitor/1');
add_block('simulink/Signal Routing/Goto', [path '/Virtual VCU AI Telemetry'], ...
    'GotoTag', 'VirtualVcuMeasuredAI', 'TagVisibility', 'global', ...
    'Position', [520 270 680 290]);
add_line(path, 'Module 3 Analog Mux/1', 'Virtual VCU AI Telemetry/1');
ids = [uint32(hex2dec('1F5')) uint32(hex2dec('186')) ...
    uint32(hex2dec('196')) uint32(hex2dec('1A6')) uint32(hex2dec('1B6'))];
for k = 1:5
    transition = add_block('simulink/Signal Attributes/Rate Transition', ...
        [path sprintf('/Port A Payload Rate Transition %d', k)], ...
        'Position', [820 25 + 55*k 840 55 + 55*k]);
    pack = add_block('canlib/CAN Pack', [path sprintf('/Port A CAN Pack %d', k)], ...
        'Position', [920 25 + 55*k 1030 55 + 55*k]);
    set_param(pack, 'DataFormat', 'raw data', 'MsgIDType', ...
        'Standard (11-bit identifier)', 'MsgIdentifier', num2str(ids(k)), ...
        'CANIDInput', 'off', 'MsgLength', '8', 'Remote', 'off', ...
        'BusOutput', 'off');
    write = add_block('speedgoatlib_IO614/CAN Write ', ...
        [path sprintf('/Port A CAN Write %d', k)], ...
        'Position', [1060 25 + 55*k 1180 55 + 55*k]);
    set_param(write, 'moduleType', 'IO614', 'id', '1', 'channel', '2', ...
        'canType', 'CAN (HS)', 'useBusIn', 'off', 'numOfMsg', '1', ...
        'enableStatusPort', 'on', 'ts', '0.005', 'UserData', ids(k), ...
        'UserDataPersistent', 'on');
    add_line(path, sprintf('VCU Payload Split/%d', k), ...
        sprintf('Port A Payload Rate Transition %d/1', k));
    add_line(path, sprintf('Port A Payload Rate Transition %d/1', k), ...
        sprintf('Port A CAN Pack %d/1', k));
    add_line(path, sprintf('Port A CAN Pack %d/1', k), sprintf('Port A CAN Write %d/1', k));
end
set_param(path, 'Commented', 'off');
% Re-assert the chart source after all signal connections; R2024b may
% refresh a MATLAB Function block's default template when a downstream
% vector-width diagnostic is first evaluated.
setMatlabFunctionScript(fcn, vcuScript());
save_system(model, modelPath);
% Persist the chart source once more after a close/reopen. This mirrors the
% R2024b App/Stateflow serialization behavior and prevents a stale default
% `function y=fcn(u)` template from shadowing the generated script.
close_system(model, 0);
load_system(modelPath);
setMatlabFunctionScript([path], vcuScript());
save_system(model, modelPath);
end

function script = vcuScript()
script = fileread(fullfile(fileparts(mfilename('fullpath')), ...
    'virtualVcuDeployStep.m'));
end

function setMatlabFunctionScript(blockPath, script)
rt = sfroot(); chart = rt.find('-isa', 'Stateflow.EMChart', '-and', 'Path', blockPath);
chart(1).Script = script;
if ~contains(chart(1).Script, 'function payloads = virtualVcuDeployStep(u)')
    error('virtualvcu:ChartScript', 'Virtual VCU chart script was not installed.');
end
end
