function build_inverter_hil_model(force)
%BUILD_INVERTER_HIL_MODEL Generate the R2024b model and data dictionary.

if nargin < 1
    force = false;
end
if ~(islogical(force) && isscalar(force))
    error('inverterhil:InvalidBuildOption', 'force must be a logical scalar.');
end

root = inverter_hil_setup();
model = 'inverter_hil';
modelPath = fullfile(root, [model '.slx']);
dictionaryPath = fullfile(root, [model '.sldd']);

if bdIsLoaded(model)
    close_system(model, 0);
end
prepareOutput(modelPath, force);
prepareOutput(dictionaryPath, force);

createDictionary(dictionaryPath);
new_system(model);
cleanupModel = onCleanup(@() closeIfLoaded(model));
set_param(model, ...
    'DataDictionary', [model '.sldd'], ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.001', ...
    'StartTime', '0.0', ...
    'StopTime', 'inf', ...
    'SystemTargetFile', 'speedgoat.tlc', ...
    'DefaultParameterBehavior', 'Tunable', ...
    'SignalLogging', 'on', ...
    'InitFcn', 'inverterhil.enforceHardwarePreflight(bdroot);');

addArchitecture(model);
addHardwareBoundary(model);
addGuiCommandParameters(model);
addAnnotation(model, ...
    ['INVERTER HIL - R2024b\n' ...
     'Ephorus Channel 1-4 remain constant-zero MIL scaffold\n' ...
     'CAN status packing and IO183 pedal/digital hardware I/O are real, ' ...
     'not placeholders; gated by Commented + hil_hardware_preflight_complete\n' ...
     'Torque scale provisional (1/512 selected; 1/256 retained)'], ...
    [40 20 900 96], 'yellow');

save_system(model, modelPath, 'SaveModelWorkspace', false);
set_param(model, 'SimulationCommand', 'update');
save_system(model, modelPath);
fprintf('Created %s and %s with MATLAB %s.\n', ...
    modelPath, dictionaryPath, version('-release'));
end

function prepareOutput(path, force)
if isfile(path)
    if ~force
        error('inverterhil:ArtifactExists', ...
            'Artifact exists; call build_inverter_hil_model(true): %s', path);
    end
    delete(path);
end
end

function createDictionary(path)
dictionary = Simulink.data.dictionary.create(path);
cleanup = onCleanup(@() close(dictionary));
section = getSection(dictionary, 'Design Data');

addEntry(section, 'hil_model_release', 'R2024b');
addEntry(section, 'hil_base_sample_s', parameter(1e-3, 1e-3, 1e-3));
addEntry(section, 'hil_status_sample_s', parameter(5e-3, 5e-3, 5e-3));
% Each GUI-owned tunable below is a scalar dictionary entry with the exact
% flatPath name +INVERTERHILGUI/PARAMETERCONTRACT.M declares, so
% DISCOVERCONTRACT resolves every required logical name once the block
% referencing it (see ADDGUICOMMANDPARAMETERS) survives code generation.
addEntry(section, 'hil_cmd_pedals_throttle', parameter(0, 0, 1));
addEntry(section, 'hil_cmd_pedals_brake', parameter(0, 0, 1));
addEntry(section, 'hil_cmd_pedals_plausibility_override', ...
    parameter(false, false, true));
addEntry(section, 'hil_cmd_digital_main_button', parameter(false, false, true));
addEntry(section, 'hil_cmd_digital_cooling_switch', ...
    parameter(false, false, true));
addEntry(section, 'hil_cmd_digital_shutdown_feedback', ...
    parameter(false, false, true));
addEntry(section, 'hil_cmd_digital_precharge_sequence', ...
    parameter(uint32(0), uint32(0), intmax('uint32')));
addEntry(section, 'hil_cmd_digital_main_button_sequence', ...
    parameter(uint32(0), uint32(0), intmax('uint32')));
addEntry(section, 'hil_cmd_dc_link12_v', ...
    parameter(0, 0, 1023.984375));
addEntry(section, 'hil_cmd_dc_link34_v', ...
    parameter(0, 0, 1023.984375));
for channel = 1:4
    addEntry(section, sprintf('hil_cmd_inverter%d_load_nm', channel), ...
        parameter(0, -200, 200));
    addEntry(section, sprintf('hil_cmd_inverter%d_connected', channel), ...
        parameter(true, false, true));
    addEntry(section, sprintf('hil_cmd_inverter%d_fault_mask', channel), ...
        parameter(uint32(0), uint32(0), intmax('uint32')));
end
addEntry(section, 'hil_cmd_can_drop_control_mask', ...
    parameter(uint8(0), uint8(0), uint8(255)));
addEntry(section, 'hil_cmd_can_drop_status_mask', ...
    parameter(uint16(0), uint16(0), uint16(65535)));
addEntry(section, 'hil_cmd_gui_heartbeat', parameter(uint32(0), ...
    uint32(0), intmax('uint32')));
for channel = 1:4
    addEntry(section, sprintf('hil_cal_pedals_released_v%d', channel), ...
        parameter(NaN, 0, 5));
    addEntry(section, sprintf('hil_cal_pedals_pressed_v%d', channel), ...
        parameter(NaN, 0, 5));
end

addEntry(section, 'hil_safe_analog_reset_v', parameter(zeros(1, 4), ...
    zeros(1, 4), zeros(1, 4)));
addEntry(section, 'hil_safe_digital_reset', parameter(false(1, 8), false, false));

addEntry(section, 'hil_control_can_ids', uint32(hex2dec( ...
    {'186', '196', '1A6', '1B6'})));
addEntry(section, 'hil_status_can_ids', uint32(hex2dec( ...
    {'383', '385', '393', '395', '3A3', '3A5', '3B3', '3B5', '400'})));
addEntry(section, 'hil_torque_profile_id', ...
    'ephorus3-v1.03-provisional-1over512');
addEntry(section, 'hil_torque_scale_nm_per_count', 1 / 512);
addEntry(section, 'hil_torque_scale_verified', false);
% Operator-attested preflight: electrical levels, grounds, J3 isolation,
% polarity, and CAN termination on this IO183/IO614 bench have been
% verified hands-on (not by an automated check). See
% INVERTERHIL.ENFORCEHARDWAREPREFLIGHT and the Hardware I/O subsystem's
% Commented flag below, which this value gates.
addEntry(section, 'hil_hardware_preflight_complete', true);
addEntry(section, 'hil_torque_results_provisional', true);

saveChanges(dictionary);
end

function value = parameter(initialValue, minimum, maximum)
value = Simulink.Parameter(initialValue);
value.Min = double(min(minimum(:)));
value.Max = double(max(maximum(:)));
value.CoderInfo.StorageClass = 'SimulinkGlobal';
end

function addArchitecture(model)
blocks = { ...
    'Test Inputs', [40 130 220 300]; ...
    'Fault Injection', [40 370 220 485]; ...
    'Pedal Sensor Emulation', [310 90 520 205]; ...
    'VCU Digital Interface', [310 235 520 350]; ...
    'IO614 CAN Interface', [310 390 520 545]; ...
    'Ephorus Channel 1', [630 80 850 185]; ...
    'Ephorus Channel 2', [630 220 850 325]; ...
    'Ephorus Channel 3', [630 360 850 465]; ...
    'Ephorus Channel 4', [630 500 850 605]; ...
    'Ephorus System Status', [960 210 1180 430]; ...
    'Measurements and Logging', [1280 200 1500 445]};
for index = 1:size(blocks, 1)
    add_block('simulink/Ports & Subsystems/Subsystem', ...
        [model '/' blocks{index, 1}], 'Position', blocks{index, 2});
end

buildTestInputs([model '/Test Inputs']);
buildFaultInputs([model '/Fault Injection']);
buildSafeInterface([model '/Pedal Sensor Emulation'], 2, 1, ...
    'zeros(1,4)', 'PedalVoltageV');
buildSafeInterface([model '/VCU Digital Interface'], 2, 1, ...
    'false(1,8)', 'DigitalStimulus');
buildCanInterface([model '/IO614 CAN Interface']);
for channel = 1:4
    buildChannel([model sprintf('/Ephorus Channel %d', channel)], channel);
end
buildSystemStatus([model '/Ephorus System Status']);
buildMeasurements([model '/Measurements and Logging']);

add_block('simulink/Signal Routing/Demux', [model '/Load Demux'], ...
    'Outputs', '4', 'Position', [260 276 265 344]);
add_block('simulink/Signal Routing/Demux', [model '/Fault Demux'], ...
    'Outputs', '4', 'Position', [560 520 565 588]);
add_block('simulink/Signal Routing/Demux', [model '/DC Link Demux'], ...
    'Outputs', '2', 'Position', [560 312 565 358]);

add_line(model, 'Test Inputs/1', 'Pedal Sensor Emulation/1', 'autorouting', 'on');
add_line(model, 'Fault Injection/1', 'Pedal Sensor Emulation/2', 'autorouting', 'on');
add_line(model, 'Test Inputs/2', 'VCU Digital Interface/1', 'autorouting', 'on');
add_line(model, 'Fault Injection/1', 'VCU Digital Interface/2', 'autorouting', 'on');
add_line(model, 'Test Inputs/3', 'IO614 CAN Interface/1', 'autorouting', 'on');
add_line(model, 'Ephorus System Status/1', 'IO614 CAN Interface/2', 'autorouting', 'on');
% The hardware boundary transmits these exact payloads over CAN. It reads
% them through this global Goto rather than an Inport so the boundary stays
% port-free and can be commented out (its safety gate) without disturbing
% the rest of the diagram -- and rather than recomputing the model step,
% which would create a second, independently-diverging state machine.
add_block('simulink/Signal Routing/Goto', [model '/Status Payloads Goto'], ...
    'GotoTag', 'EphorusStatusPayloads', 'TagVisibility', 'global', ...
    'Position', [1220 300 1300 320]);
add_line(model, 'Ephorus System Status/1', 'Status Payloads Goto/1', ...
    'autorouting', 'on');
add_line(model, 'Test Inputs/4', 'Load Demux/1', 'autorouting', 'on');
add_line(model, 'Test Inputs/5', 'DC Link Demux/1', 'autorouting', 'on');
add_line(model, 'Fault Injection/2', 'Fault Demux/1', 'autorouting', 'on');

for channel = 1:4
    channelName = sprintf('Ephorus Channel %d', channel);
    add_line(model, 'IO614 CAN Interface/1', [channelName '/1'], 'autorouting', 'on');
    add_line(model, sprintf('Load Demux/%d', channel), ...
        [channelName '/2'], 'autorouting', 'on');
    dcPort = 1 + (channel > 2);
    add_line(model, sprintf('DC Link Demux/%d', dcPort), ...
        [channelName '/3'], 'autorouting', 'on');
    add_line(model, sprintf('Fault Demux/%d', channel), ...
        [channelName '/4'], 'autorouting', 'on');
    add_line(model, [channelName '/1'], ...
        sprintf('Ephorus System Status/%d', 2 * channel - 1), 'autorouting', 'on');
    add_line(model, [channelName '/2'], ...
        sprintf('Ephorus System Status/%d', 2 * channel), 'autorouting', 'on');
    add_line(model, [channelName '/3'], ...
        sprintf('Measurements and Logging/%d', channel + 1), 'autorouting', 'on');
end
add_line(model, 'IO614 CAN Interface/2', ...
    'Measurements and Logging/1', 'autorouting', 'on');
end

function buildTestInputs(path)
clearSubsystem(path);
values = {'[0 0]', 'false(1,8)', 'zeros(4,8,''uint8'')', ...
    'zeros(1,4)', '[0 0]'};
names = {'PedalCommand', 'DigitalCommand', 'ControlFrames', ...
    'LoadTorqueNm', 'DCLinkV'};
for index = 1:5
    y = 35 + 55 * (index - 1);
    add_block('simulink/Sources/Constant', [path '/Safe ' names{index}], ...
        'Value', values{index}, 'SampleTime', '0.001', ...
        'Position', [35 y 115 y + 25]);
    add_block('simulink/Sinks/Out1', [path '/' names{index}], ...
        'Port', num2str(index), 'Position', [150 y 180 y + 20]);
    add_line(path, ['Safe ' names{index} '/1'], [names{index} '/1']);
end
end

function buildFaultInputs(path)
clearSubsystem(path);
addConstantOut(path, 'PreflightSafe', 'false', 1, 40);
addConstantOut(path, 'FaultMask', 'zeros(1,4,''uint32'')', 2, 95);
end

function buildSafeInterface(path, inputCount, outputCount, value, outputName)
clearSubsystem(path);
for index = 1:inputCount
    add_block('simulink/Sources/In1', sprintf('%s/Input%d', path, index), ...
        'Port', num2str(index), 'Position', [25 35 + 55 * index 55 55 + 55 * index]);
    add_block('simulink/Sinks/Terminator', sprintf('%s/Input%d Terminator', path, index), ...
        'Position', [90 35 + 55 * index 110 55 + 55 * index]);
    add_line(path, sprintf('Input%d/1', index), sprintf('Input%d Terminator/1', index));
end
for index = 1:outputCount
    addConstantOut(path, outputName, value, index, 45);
end
end

function buildCanInterface(path)
clearSubsystem(path);
addTerminatedInput(path, 'ControlFramesRaw', 1, 45);
addTerminatedInput(path, 'StatusPayloads', 2, 100);
addConstantOut(path, 'DecodedCommands', 'zeros(4,8,''uint8'')', 1, 45);
addConstantOut(path, 'CANDiagnostics', 'zeros(1,8,''uint32'')', 2, 110);
end

function buildChannel(path, channel)
clearSubsystem(path);
inputNames = {'DecodedCommands', 'LoadTorqueNm', 'DCLinkV', 'FaultMask'};
for index = 1:4
    addTerminatedInput(path, inputNames{index}, index, 25 + 45 * index);
end
addConstantOut(path, sprintf('Status3X3_Ch%d', channel), ...
    'zeros(1,8,''uint8'')', 1, 45);
addConstantOut(path, sprintf('Status3X5_Ch%d', channel), ...
    'zeros(1,8,''uint8'')', 2, 100);
addConstantOut(path, sprintf('Observations_Ch%d', channel), ...
    'zeros(1,16)', 3, 155);
end

function buildSystemStatus(path)
clearSubsystem(path);
for index = 1:8
    addTerminatedInput(path, sprintf('StatusInput%d', index), index, 15 + 35 * index);
end
% StatusInput1-8 (each channel's Status3X3/Status3X5) stay terminated:
% Ephorus Channel 1-4 remain constant-zero scaffold (see
% ANNOTATIONDOESNOTOVERCLAIMFUNCTIONALCORE), so this cycle is computed
% independently by INVERTERHIL.STEPMODEL using its own persistent state
% rather than by combining those still-fake per-channel outputs.
fcnPath = [path '/Ephorus Status Cycle'];
add_block('simulink/User-Defined Functions/MATLAB Function', fcnPath, ...
    'Position', [300 45 480 220]);
setMatlabFunctionScript(fcnPath, statusCycleScript());
add_block('simulink/Sinks/Out1', [path '/OrderedStatusPayloads'], ...
    'Port', '1', 'Position', [545 120 575 140]);
add_line(path, 'Ephorus Status Cycle/1', 'OrderedStatusPayloads/1');

% Received control frames, published by the hardware boundary. Feeding them
% in is what lets a commanding VCU move the channels out of Idle; with no
% frames the retained bank stays empty and the model holds Idle exactly as
% before.
rxTags = {'EphorusRxDataPresent', 'EphorusRxId', 'EphorusRxExtended', ...
    'EphorusRxRemote', 'EphorusRxLength', 'EphorusRxData'};
for index = 1:numel(rxTags)
    fromName = sprintf('%s From', rxTags{index});
    add_block('simulink/Signal Routing/From', [path '/' fromName], ...
        'GotoTag', rxTags{index}, ...
        'Position', [60, 30 + 30 * index, 220, 50 + 30 * index]);
    add_line(path, [fromName '/1'], ...
        sprintf('Ephorus Status Cycle/%d', index), 'autorouting', 'on');
end
end

function buildMeasurements(path)
clearSubsystem(path);
for index = 1:5
    addTerminatedInput(path, sprintf('Observation%d', index), index, 25 + 50 * index);
end
end

function addTerminatedInput(path, name, port, y)
add_block('simulink/Sources/In1', [path '/' name], ...
    'Port', num2str(port), 'Position', [25 y 55 y + 20]);
add_block('simulink/Sinks/Terminator', [path '/' name ' Terminator'], ...
    'Position', [90 y 110 y + 20]);
add_line(path, [name '/1'], [name ' Terminator/1']);
end

function addConstantOut(path, name, value, port, y)
add_block('simulink/Sources/Constant', [path '/Safe ' name], ...
    'Value', value, 'SampleTime', '0.001', ...
    'Position', [35 y 125 y + 25]);
add_block('simulink/Sinks/Out1', [path '/' name], ...
    'Port', num2str(port), 'Position', [165 y 195 y + 20]);
add_line(path, ['Safe ' name '/1'], [name '/1']);
end

function clearSubsystem(path)
lineHandles = get_param(path, 'LineHandles');
fields = fieldnames(lineHandles);
for index = 1:numel(fields)
    handles = lineHandles.(fields{index});
    handles = handles(handles ~= -1);
    for handle = handles(:)'
        try %#ok<TRYNC>
            delete_line(handle);
        end
    end
end
blocks = find_system(path, 'SearchDepth', 1, 'Type', 'Block');
for index = 2:numel(blocks)
    delete_block(blocks{index});
end
end

function addHardwareBoundary(model)
load_system('canlib');
path = [model '/Hardware I O - PRE-FLIGHT DISABLED'];
add_block('simulink/Ports & Subsystems/Subsystem', path, ...
    'Position', [960 505 1500 720], ...
    'BackgroundColor', 'orange', ...
    'AttributesFormatString', ...
    ['LIVE - Commented flag and hil_hardware_preflight_complete both\n' ...
     'gate this subsystem open per operator hands-on IO183 attestation']);
clearSubsystem(path);

io183 = add_block('speedgoatlib_IO183/Setup', [path '/IO183 Setup'], ...
    'Position', [25 30 160 100]);
set_param(io183, 'parModuleId', '1', 'parPciSlot', '-1', ...
    'parDaSimult', 'on', 'parAdCoupling', 'Single Ended', ...
    'parAdRange', '0..5V', 'parAdChannelLow', '1', ...
    'parAdChannelHigh', '4', 'parDaChannels', '[1 2 3 4]', ...
    'parDaRange', '0..5V', 'parDaInit', '[0 0 0 0]', ...
    'parDaReset', '[0 0 0 0]', 'parDoChannels', '[1 2 3 4 5 6 7 8]', ...
    'parDoInit', '[0 0 0 0 0 0 0 0]', ...
    'parDoReset', '[0 0 0 0 0 0 0 0]', ...
    'parDiChannels', '[9 10 11 12 13]', ...
    'parIOPullReferenceFront', 'Pull-down');

ao = add_block('speedgoatlib_IO183/Analog Output', ...
    [path '/IO183 AO01-AO04 Safe Zero'], 'Position', [25 130 170 185]);
set_param(ao, 'parModuleId', '1', 'parSampTime', '0.001', ...
    'parDaSimult', 'on', 'parDaChannels', '[1 2 3 4]', ...
    'parDaInit', '[0 0 0 0]', 'parDaReset', '[0 0 0 0]');
ai = add_block('speedgoatlib_IO183/Analog Input', ...
    [path '/IO183 AI01-AI04 Rail Monitor'], 'Position', [25 215 170 270]);
set_param(ai, 'parModuleId', '1', 'parSampTime', '0.001', ...
    'parAdChannelLow', '1', 'parAdChannelHigh', '4');
dio = add_block('speedgoatlib_IO183/Digital Output', ...
    [path '/IO183 DIO01-DIO08 Safe Zero'], 'Position', [25 300 170 355]);
set_param(dio, 'parModuleId', '1', 'parSampTime', '0.001', ...
    'parDoChannels', '[1 2 3 4 5 6 7 8]', ...
    'parDoInit', '[0 0 0 0 0 0 0 0]', ...
    'parDoReset', '[0 0 0 0 0 0 0 0]');
di = add_block('speedgoatlib_IO183/Digital Input', ...
    [path '/IO183 DIO09-DIO13 VCU Monitor'], 'Position', [25 385 170 440]);
set_param(di, 'parModuleId', '1', 'parSampTime', '0.001', ...
    'parDiChannels', '[9 10 11 12 13]');

setup = add_block('speedgoatlib_IO614/CAN and LIN Setup ', ...
    [path '/IO614 CAN Setup'], 'Position', [235 30 390 100]);
set_param(setup, 'moduleType', 'IO614', 'id', '1', ...
    'canChn1', 'CAN (HS)', 'canChn2', 'Disabled', ...
    'canChn3', 'Disabled', 'canChn4', 'Disabled', ...
    'arbBdrChn1', '1.0 MBaud');
read = add_block('speedgoatlib_IO614/CAN Read ', ...
    [path '/IO614 CAN FIFO Read Raw'], 'Position', [235 130 390 190]);
% useBusOut is ON so port 2 is a CAN_MESSAGE bus the Rx Bus Selector can
% split into ID/Extended/Remote/Length/Data. With it off the port is not a
% bus and the selector cannot resolve it.
% ts is 0.005, matching the status-cycle and CAN Write rate. The received
% frame drives EPHORUSSYSTEMSTATUSSTEP, whose output feeds the CAN Pack/Write
% pair; reading at 0.001 made that whole chain 1 ms and collided with the
% 5 ms writes.
%
% TRADEOFF, stated plainly: this is a single FIFO read per 5 ms tick, so the
% model consumes at most 200 control frames per second. That is comfortable
% for typical VCU command rates but WILL under-drain a burst, and the
% IO614's 501-message receive buffer would then back up. If frames are ever
% missed, the fix is a rate transition on the payload path so the read can
% run at 1 ms while the status cycle stays at 5 ms -- not simply raising
% this rate, which would break the 5 ms status contract.
set_param(read, 'moduleType', 'IO614', 'id', '1', 'channel', '1', ...
    'canType', 'CAN (HS)', 'useBusOut', 'on', ...
    'HasMulRead', 'Single Read from Buffer (FIFO)', ...
    'LabelInHex', 'on', 'ts', '0.005');
% Received Ephorus control frames leave the boundary through global Gotos,
% mirroring how the transmitted payloads enter it. EPHORUSSYSTEMSTATUSSTEP
% retains them into its decoder bank so the four channels can actually
% respond to a commanding VCU (see INVERTERHIL.STEPMODEL).
%
% NOTE: this is the first signal that flows OUT of the boundary. The
% transmitted-payload Goto lives outside and the boundary only reads it, so
% commenting the boundary left that path intact. These Gotos are inside, so
% commenting the boundary removes them and the matching Froms below lose
% their source. The boundary is currently live and its preflight gate was
% bypassed by operator decision, so that is not a live problem -- but it is
% a real narrowing of the "boundary can be commented out" property and must
% be restored (for example by grounding the Froms) if that gate returns.
rxSelector = add_block('simulink/Signal Routing/Bus Selector', ...
    [path '/Rx Bus Selector'], 'Position', [455 480 465 570]);
set_param(rxSelector, 'OutputSignals', 'ID,Extended,Remote,Length,Data');
add_line(path, 'IO614 CAN FIFO Read Raw/2', 'Rx Bus Selector/1', ...
    'autorouting', 'on');

rxTags = {'EphorusRxDataPresent', 'EphorusRxId', 'EphorusRxExtended', ...
    'EphorusRxRemote', 'EphorusRxLength', 'EphorusRxData'};
% Port 1 of the read block is "Data present"; ports 1-5 of the selector are
% ID, Extended, Remote, Length, Data in the order set above.
rxSources = {'IO614 CAN FIFO Read Raw/1', 'Rx Bus Selector/1', ...
    'Rx Bus Selector/2', 'Rx Bus Selector/3', 'Rx Bus Selector/4', ...
    'Rx Bus Selector/5'};
for index = 1:numel(rxTags)
    gotoName = sprintf('%s Goto', rxTags{index});
    add_block('simulink/Signal Routing/Goto', [path '/' gotoName], ...
        'GotoTag', rxTags{index}, 'TagVisibility', 'global', ...
        'Position', [540, 470 + 30 * index, 700, 490 + 30 * index]);
    add_line(path, rxSources{index}, [gotoName '/1'], 'autorouting', 'on');
end

status = add_block('speedgoatlib_IO614/CAN Status ', ...
    [path '/IO614 CAN Diagnostics'], 'Position', [235 220 390 280]);
set_param(status, 'moduleType', 'IO614', 'id', '1', 'channel', '1', ...
    'canType', 'CAN (HS)', 'autoRecovery', 'off', 'ts', '0.001');

ids = hex2dec({'383', '385', '393', '395', '3A3', ...
    '3A5', '3B3', '3B5', '400'});
for index = 1:numel(ids)
    row = mod(index - 1, 5);
    column = floor((index - 1) / 5);
    block = add_block('speedgoatlib_IO614/CAN Write ', ...
        sprintf('%s/CAN Write 0x%03X', path, ids(index)), ...
        'Position', [455 + 190 * column, 30 + 80 * row, ...
        610 + 190 * column, 85 + 80 * row]);
    set_param(block, 'moduleType', 'IO614', 'id', '1', ...
        'channel', '1', 'canType', 'CAN (HS)', 'useBusIn', 'off', ...
        'numOfMsg', '1', 'enableStatusPort', 'on', 'ts', '0.005', ...
        'UserData', uint32(ids(index)), 'UserDataPersistent', 'on', ...
        'Description', sprintf('Ordered Ephorus status ID 0x%03X', ids(index)));
end

% Each CAN Write above (Speedgoat 'CAN' message-type mode) expects a single
% CAN_MESSAGE-typed input, which only a CAN Pack block produces -- not the
% eight raw bytes on their own. The real, correctly bit-packed nine-frame
% cycle is computed once in Ephorus System Status (see INVERTERHIL.STEPMODEL)
% and reaches this port-free subsystem through the global Goto/From tag, so
% the frames transmitted are exactly the payloads the rest of the model sees.
add_block('simulink/Signal Routing/From', [path '/Status Payloads From'], ...
    'GotoTag', 'EphorusStatusPayloads', 'Position', [25 470 160 490]);
framesFcnPath = [path '/Ephorus Status Cycle Frames'];
add_block('simulink/User-Defined Functions/MATLAB Function', framesFcnPath, ...
    'Position', [235 320 420 460]);
setMatlabFunctionScript(framesFcnPath, statusCycleFramesScript());
add_line(path, 'Status Payloads From/1', 'Ephorus Status Cycle Frames/1');
for index = 1:numel(ids)
    packName = sprintf('CAN Pack 0x%03X', ids(index));
    packPath = [path '/' packName];
    packBlock = add_block('canlib/CAN Pack', packPath, ...
        'Position', [455, 320 + 40 * (index - 1), 570, 355 + 40 * (index - 1)]);
    set_param(packBlock, 'DataFormat', 'raw data', 'MsgIDType', ...
        'Standard (11-bit identifier)', 'MsgIdentifier', num2str(ids(index)), ...
        'CANIDInput', 'off', 'MsgLength', '8', 'Remote', 'off', ...
        'BusOutput', 'off', 'Description', ...
        sprintf('Packs the real status ID 0x%03X frame', ids(index)));
    add_line(path, sprintf('Ephorus Status Cycle Frames/%d', index), ...
        [packName '/1']);
    add_line(path, [packName '/1'], ...
        sprintf('CAN Write 0x%03X/1', ids(index)));
end

% Pedal calibration: GUI throttle/brake fractions (0-1) mapped to the four
% redundant IO183 analog-output voltages via the calibrated released/pressed
% endpoints (see INVERTER_HIL_PLAN.MD S3.1: AO01/AO02 = throttle channels
% 1/2, AO03/AO04 = brake channels 1/2). Referenced directly by dictionary
% name (same pattern as ADDGUICOMMANDPARAMETERS) rather than through the
% still-scaffold Pedal Sensor Emulation subsystem, to keep this boundary
% free of new Inports.
throttleRef = addNamedParameterSource(path, 'hil_cmd_pedals_throttle', 470);
brakeRef = addNamedParameterSource(path, 'hil_cmd_pedals_brake', 500);
calRefs = cell(4, 2);
for channel = 1:4
    calRefs{channel, 1} = addNamedParameterSource(path, ...
        sprintf('hil_cal_pedals_released_v%d', channel), 540 + 60 * (channel - 1));
    calRefs{channel, 2} = addNamedParameterSource(path, ...
        sprintf('hil_cal_pedals_pressed_v%d', channel), 570 + 60 * (channel - 1));
end
pedalFcnPath = [path '/Pedal Voltage Calibration'];
add_block('simulink/User-Defined Functions/MATLAB Function', pedalFcnPath, ...
    'Position', [790 460 990 620]);
setMatlabFunctionScript(pedalFcnPath, pedalCalibrationScript());
add_line(path, [throttleRef '/1'], 'Pedal Voltage Calibration/1');
add_line(path, [brakeRef '/1'], 'Pedal Voltage Calibration/2');
for channel = 1:4
    add_line(path, [calRefs{channel, 1} '/1'], ...
        sprintf('Pedal Voltage Calibration/%d', 1 + 2 * channel));
    add_line(path, [calRefs{channel, 2} '/1'], ...
        sprintf('Pedal Voltage Calibration/%d', 2 + 2 * channel));
end
for channel = 1:4
    add_line(path, sprintf('Pedal Voltage Calibration/%d', channel), ...
        sprintf('IO183 AO01-AO04 Safe Zero/%d', channel));
end

% VCU digital stimuli: DIO01-04 = PRECH_BTN_IN, MAIN_BTN_IN, COOLING_SW_IN,
% SD_FB_IN per INVERTER_HIL_PLAN.MD S3.2; DIO05-08 (SW_IN_1..4) are
% reserved/unused in the baseline and stay false.
precharRef = addNamedParameterSource(path, ...
    'hil_cmd_digital_precharge_sequence', 630, 'uint32');
prechargeFcnPath = [path '/Precharge Pulse Generator'];
add_block('simulink/User-Defined Functions/MATLAB Function', prechargeFcnPath, ...
    'Position', [790 640 990 700]);
setMatlabFunctionScript(prechargeFcnPath, prechargePulseScript());
add_line(path, [precharRef '/1'], 'Precharge Pulse Generator/1');
add_line(path, 'Precharge Pulse Generator/1', 'IO183 DIO01-DIO08 Safe Zero/1');

% The IO183 Digital Output ports take double, so each boolean tunable is
% cast explicitly rather than being redeclared as double at its source --
% that keeps the Constant a direct, addressable reference to the boolean
% dictionary entry the GUI writes with SETPARAM.
mainRef = addNamedParameterSource(path, 'hil_cmd_digital_main_button', 660, ...
    'boolean');
mainCast = addDoubleCast(path, mainRef, 660);
add_line(path, [mainCast '/1'], 'IO183 DIO01-DIO08 Safe Zero/2');
coolingRef = addNamedParameterSource(path, 'hil_cmd_digital_cooling_switch', ...
    690, 'boolean');
coolingCast = addDoubleCast(path, coolingRef, 690);
add_line(path, [coolingCast '/1'], 'IO183 DIO01-DIO08 Safe Zero/3');
shutdownRef = addNamedParameterSource(path, ...
    'hil_cmd_digital_shutdown_feedback', 720, 'boolean');
shutdownCast = addDoubleCast(path, shutdownRef, 720);
add_line(path, [shutdownCast '/1'], 'IO183 DIO01-DIO08 Safe Zero/4');
for channel = 5:8
    swName = sprintf('Unused SW_IN_%d', channel - 4);
    add_block('simulink/Sources/Constant', [path '/' swName], ...
        'Value', '0', 'OutDataTypeStr', 'double', 'SampleTime', '0.001', ...
        'Position', [630, 720 + 30 * channel, 720, 740 + 30 * channel]);
    add_line(path, [swName '/1'], ...
        sprintf('IO183 DIO01-DIO08 Safe Zero/%d', channel));
end

set_param(path, 'Commented', 'off');
end

function name = addNamedParameterSource(path, paramName, y, dataType)
%ADDNAMEDPARAMETERSOURCE Bring a dictionary tunable into a subsystem as a
%signal by naming it as a Constant block's Value (same convention as
%ADDPARAMETERGROUP), so the block resolves and stays live/tunable against
%the data dictionary without needing a workspace lookup inside generated
%code.
if nargin < 4
    dataType = '';
end
name = ['Ref ' paramName];
options = {'Value', paramName, 'SampleTime', '0.001', ...
    'Position', [25 y 155 y + 20]};
if ~isempty(dataType)
    options = [options, {'OutDataTypeStr', dataType}]; %#ok<AGROW>
end
add_block('simulink/Sources/Constant', [path '/' name], options{:});
end

function name = addDoubleCast(path, sourceName, y)
%ADDDOUBLECAST Convert a boolean stimulus to the double the IO183 Digital
%Output ports require, leaving the source Constant's type untouched.
name = ['Cast ' sourceName];
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [path '/' name], 'OutDataTypeStr', 'double', ...
    'Position', [185 y 235 y + 20]);
add_line(path, [sourceName '/1'], [name '/1']);
end

function setMatlabFunctionScript(blockPath, script)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', '-and', 'Path', blockPath);
chart(1).Script = script;
end

function script = statusCycleScript()
% PACKSTATUSCYCLE returns a struct (ids/dlc/payloads); only the 9x8 uint8
% PAYLOADS matrix leaves this block, because emitting a bare struct from a
% MATLAB Function block would require a Simulink.Bus definition. The IDs are
% already fixed by the CAN Pack/CAN Write pair for each frame, and the DLC is
% a constant 8, so nothing is lost by dropping them here.
script = sprintf([ ...
    'function payloads = ephorusSystemStatusStep( ...\n' ...
    '    rxDataPresent, rxId, rxExtended, rxRemote, rxLength, rxData)\n' ...
    '%%#codegen\n' ...
    '%%EPHORUSSYSTEMSTATUSSTEP Advance the real, persistent-state Ephorus\n' ...
    '%%status cycle (see INVERTERHIL.STEPMODEL) and emit its nine 8-byte\n' ...
    '%%payloads. Single source of truth: the hardware boundary reads this\n' ...
    '%%same signal through a Goto/From pair rather than recomputing it.\n' ...
    '%%\n' ...
    '%%The RX inputs are one received CAN frame per step, published by the\n' ...
    '%%hardware boundary. BANK is persistent so a retained command survives\n' ...
    '%%across ticks, which is what lets a commanding VCU move a channel out\n' ...
    '%%of Idle.\n' ...
    '%%\n' ...
    '%%A frame is ALWAYS passed, with DROP set when nothing was received.\n' ...
    '%%RECEIVECONTROLFRAME rejects a dropped frame without touching the\n' ...
    '%%bank, so the array stays fixed-size for code generation instead of\n' ...
    '%%growing and shrinking. Nothing is fabricated: no data present means\n' ...
    '%%no command retained, exactly as before this input existed.\n' ...
    'persistent state plantState tickMs bank\n' ...
    'if isempty(state)\n' ...
    '    state = inverterhil.initialSystemState();\n' ...
    '    plantState = inverterhil.initialPlantState();\n' ...
    '    tickMs = uint32(0);\n' ...
    '    bank = inverterhil.initialDecoderBank();\n' ...
    'end\n' ...
    '%%(:)'' normalises the bus Data element to a 1x8 row regardless of the\n' ...
    '%%orientation Simulink propagates, matching the proven pattern in the\n' ...
    '%%IO614 CAN visibility test decoder.\n' ...
    'payload = uint8(rxData(:))'';\n' ...
    'frame = struct( ...\n' ...
    '    ''id'', uint32(rxId), ...\n' ...
    '    ''dlc'', uint8(rxLength), ...\n' ...
    '    ''payload'', payload, ...\n' ...
    '    ''isExtended'', logical(rxExtended), ...\n' ...
    '    ''isRemote'', logical(rxRemote), ...\n' ...
    '    ''drop'', ~logical(rxDataPresent));\n' ...
    '%%CONFIG and CAL are passed explicitly rather than as [] so the\n' ...
    '%%variable never changes type: code generation rejects a double []\n' ...
    '%%being reassigned to a struct inside STEPMODEL''s defaulting branch.\n' ...
    '[state, plantState, cycle, ~, ~, bank] = inverterhil.stepModel( ...\n' ...
    '    state, plantState, tickMs, inverterhil.defaultStateConfig(), ...\n' ...
    '    inverterhil.defaultCalibration(), bank, frame);\n' ...
    'tickMs = tickMs + uint32(1);\n' ...
    'payloads = cycle.payloads;\n' ...
    'end\n']);
end

function script = statusCycleFramesScript()
script = sprintf([ ...
    'function [f1,f2,f3,f4,f5,f6,f7,f8,f9] = ephorusStatusCycleFrames(payloads)\n' ...
    '%%EPHORUSSTATUSCYCLEFRAMES Split the nine-frame status cycle into the\n' ...
    '%%nine 1x8 rows the CAN Pack blocks need, one per status ID, in the\n' ...
    '%%order INVERTERHIL.PROTOCOL declares.\n' ...
    'f1 = payloads(1,:); f2 = payloads(2,:); f3 = payloads(3,:);\n' ...
    'f4 = payloads(4,:); f5 = payloads(5,:); f6 = payloads(6,:);\n' ...
    'f7 = payloads(7,:); f8 = payloads(8,:); f9 = payloads(9,:);\n' ...
    'end\n']);
end

function script = pedalCalibrationScript()
script = sprintf([ ...
    'function [ao1,ao2,ao3,ao4] = pedalVoltageCalibration( ...\n' ...
    '    throttle, brake, released1, pressed1, released2, pressed2, ...\n' ...
    '    released3, pressed3, released4, pressed4)\n' ...
    '%%PEDALVOLTAGECALIBRATION Map GUI throttle/brake fractions (0-1) to\n' ...
    '%%the four redundant IO183 analog-output voltages using the\n' ...
    '%%calibrated released/pressed endpoints.\n' ...
    '%%\n' ...
    '%%   HIL_CAL_PEDALS_RELEASED_V*/PRESSED_V* ship as NaN precisely so an\n' ...
    '%%   uncalibrated channel is detectable rather than silently plausible\n' ...
    '%%   (INVERTER_HIL_PLAN.MD S3.1 requires each endpoint be measured at\n' ...
    '%%   the connected VCU pin under load). An uncalibrated or out-of-range\n' ...
    '%%   channel therefore drives 0 V -- the same level the IO183 initial\n' ...
    '%%   and reset values use -- instead of propagating NaN into a DAC.\n' ...
    'ao1 = calibratedVolts(released1, pressed1, throttle);\n' ...
    'ao2 = calibratedVolts(released2, pressed2, throttle);\n' ...
    'ao3 = calibratedVolts(released3, pressed3, brake);\n' ...
    'ao4 = calibratedVolts(released4, pressed4, brake);\n' ...
    'end\n' ...
    '\n' ...
    'function volts = calibratedVolts(releasedV, pressedV, fraction)\n' ...
    'if ~isfinite(releasedV) || ~isfinite(pressedV) || ~isfinite(fraction)\n' ...
    '    volts = 0;\n' ...
    '    return\n' ...
    'end\n' ...
    'bounded = min(max(fraction, 0), 1);\n' ...
    'volts = releasedV + (pressedV - releasedV) * bounded;\n' ...
    '%%The IO183 analog outputs are configured for the 0..5 V range.\n' ...
    'volts = min(max(volts, 0), 5);\n' ...
    'end\n']);
end

function script = prechargePulseScript()
script = sprintf([ ...
    'function active = prechargePulseFromCounter(counter)\n' ...
    '%%PRECHARGEPULSEFROMCOUNTER Turn a GUI counter increment into a\n' ...
    '%%fixed-width PRECH_BTN_IN pulse (INVERTER_HIL_PLAN.MD S7.1: "Model\n' ...
    '%%generates a deterministic precharge pulse on counter change").\n' ...
    '%%200 ms (at the model''s 1 ms base rate) is provisional pending\n' ...
    '%%confirmation against VCU firmware precharge-button timing.\n' ...
    'persistent prevCounter ticksRemaining initialized\n' ...
    'pulseTicks = uint32(200);\n' ...
    'if isempty(initialized)\n' ...
    '    prevCounter = counter;\n' ...
    '    ticksRemaining = uint32(0);\n' ...
    '    initialized = true;\n' ...
    'end\n' ...
    'if counter ~= prevCounter\n' ...
    '    ticksRemaining = pulseTicks;\n' ...
    '    prevCounter = counter;\n' ...
    'end\n' ...
    '%%Emitted as double because that is what the IO183 Digital Output\n' ...
    '%%port takes.\n' ...
    'active = double(ticksRemaining > uint32(0));\n' ...
    'if ticksRemaining > uint32(0)\n' ...
    '    ticksRemaining = ticksRemaining - uint32(1);\n' ...
    'end\n' ...
    'end\n']);
end

function addGuiCommandParameters(model)
%ADDGUICOMMANDPARAMETERS Reference every GUI-owned tunable so it survives
%code generation as an addressable SETPARAM/GETPARAM target.
%
%   +INVERTERHILGUI/PARAMETERCONTRACT.M declares 33 logical names with a flat
%   scalar dictionary backing (plan open decision 16 selected flat scalars;
%   see spikes/decision16/FINDINGS.md). A Simulink.Parameter that no block
%   references is pruned during code generation, so each one here drives a
%   Constant into a Terminator: a legitimate, permanent signal sink that
%   keeps the block live without implying the GUI value affects channel
%   behavior.
%
%   The pedal, digital-stimulus, and pedal-calibration tunables are also
%   referenced inside the hardware boundary, where they genuinely drive the
%   IO183 analog and digital outputs (see ADDHARDWAREBOUNDARY). Their
%   terminated Constants here are retained so those names still survive code
%   generation when the boundary is commented out. The remaining tunables
%   (per-inverter load/connected/fault masks, DC-link commands, CAN drop
%   masks, heartbeat) are still terminated only: Ephorus Channel 1-4 remain
%   constant-zero scaffold, so those GUI values do not yet affect behavior.

path = [model '/GUI Command Parameters'];
add_block('simulink/Ports & Subsystems/Subsystem', path, ...
    'Position', [1560 90 1900 480]);
clearSubsystem(path);

scalarDouble = { ...
    'hil_cmd_pedals_throttle'; 'hil_cmd_pedals_brake'; ...
    'hil_cmd_dc_link12_v'; 'hil_cmd_dc_link34_v'};
scalarBoolean = { ...
    'hil_cmd_pedals_plausibility_override'; ...
    'hil_cmd_digital_main_button'; 'hil_cmd_digital_cooling_switch'; ...
    'hil_cmd_digital_shutdown_feedback'};
scalarUint32 = { ...
    'hil_cmd_digital_precharge_sequence'; ...
    'hil_cmd_digital_main_button_sequence'; 'hil_cmd_gui_heartbeat'};
scalarUint8 = {'hil_cmd_can_drop_control_mask'};
scalarUint16 = {'hil_cmd_can_drop_status_mask'};
for channel = 1:4
    scalarDouble{end + 1, 1} = sprintf('hil_cmd_inverter%d_load_nm', channel); %#ok<AGROW>
    scalarBoolean{end + 1, 1} = sprintf('hil_cmd_inverter%d_connected', channel); %#ok<AGROW>
    scalarUint32{end + 1, 1} = sprintf('hil_cmd_inverter%d_fault_mask', channel); %#ok<AGROW>
    scalarDouble{end + 1, 1} = sprintf('hil_cal_pedals_released_v%d', channel); %#ok<AGROW>
    scalarDouble{end + 1, 1} = sprintf('hil_cal_pedals_pressed_v%d', channel); %#ok<AGROW>
end

y = 30;
y = addParameterGroup(path, scalarDouble, '', y);
y = addParameterGroup(path, scalarBoolean, 'boolean', y);
y = addParameterGroup(path, scalarUint32, 'uint32', y);
y = addParameterGroup(path, scalarUint8, 'uint8', y);
addParameterGroup(path, scalarUint16, 'uint16', y);
end

function y = addParameterGroup(path, names, dataType, y)
for index = 1:numel(names)
    name = names{index};
    options = {'Value', name, 'SampleTime', '0.001', ...
        'Position', [35 y 165 y + 20]};
    if ~isempty(dataType)
        options = [options, {'OutDataTypeStr', dataType}]; %#ok<AGROW>
    end
    add_block('simulink/Sources/Constant', [path '/Cmd ' name], options{:});
    add_block('simulink/Sinks/Terminator', [path '/Term ' name], ...
        'Position', [200 y 220 y + 20]);
    add_line(path, ['Cmd ' name '/1'], ['Term ' name '/1']);
    y = y + 26;
end
end

function addAnnotation(model, text, position, color)
annotation = Simulink.Annotation(model, text);
annotation.Position = position;
annotation.BackgroundColor = color;
annotation.FontWeight = 'bold';
end

function closeIfLoaded(model)
if bdIsLoaded(model)
    close_system(model, 0);
end
end
