function build_inverter_hil_model(force)
%BUILD_INVERTER_HIL_MODEL Generate the R2024b model and data dictionary.

if nargin < 1
    force = false;
end
if ~(islogical(force) && isscalar(force))
    error('inverterhil:InvalidBuildOption', 'force must be a logical scalar.');
end

root = inverter_hil_setup();
model = 'inverter_hil';
modelPath = fullfile(root, [model '.slx']);
dictionaryPath = fullfile(root, [model '.sldd']);

if bdIsLoaded(model)
    close_system(model, 0);
end
prepareOutput(modelPath, force);
prepareOutput(dictionaryPath, force);

createDictionary(dictionaryPath);
new_system(model);
cleanupModel = onCleanup(@() closeIfLoaded(model));
set_param(model, ...
    'DataDictionary', [model '.sldd'], ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.001', ...
    'StartTime', '0.0', ...
    'StopTime', 'inf', ...
    'SystemTargetFile', 'speedgoat.tlc', ...
    'DefaultParameterBehavior', 'Tunable', ...
    'SignalLogging', 'on', ...
    'InitFcn', 'inverterhil.enforceHardwarePreflight(bdroot);');

addArchitecture(model);
addHardwareBoundary(model);
addGuiCommandParameters(model);
addAnnotation(model, ...
    ['INVERTER HIL - R2024b\n' ...
     'Ephorus Channel 1-4 remain constant-zero MIL scaffold\n' ...
     'CAN status packing and IO183 pedal/digital hardware I/O are real, ' ...
     'not placeholders; gated by Commented + hil_hardware_preflight_complete\n' ...
     'Torque scale RESOLVED 2026-08-02: 1/256 Nm/count (vcu256, verified), ' ...
     'per MFE26-VC firmware ephorus_driver.hpp:55; 1/512 retained only as a ' ...
     'known-wrong profile'], ...
    [40 20 900 96], 'yellow');

save_system(model, modelPath, 'SaveModelWorkspace', false);
set_param(model, 'SimulationCommand', 'update');
save_system(model, modelPath);

% CREATEDICTIONARY seeds every pedal endpoint at NaN so an uncalibrated
% channel is detectable. That is right for a fresh dictionary and wrong for a
% rebuild: it silently discarded the applied calibration once, and a
% discarded endpoint fails quietly (PEDALVOLTAGECALIBRATION drives 0 V, so
% the GUI sliders still move while the VCU pin does not). Re-applying from
% version-controlled constants here makes a rebuild non-destructive.
apply_pedal_calibration(dictionaryPath);

% The virtual VCU is part of the same deployable application. Add its
% isolated Module 3 / IO614 Port A boundary after the base model has been
% generated; the integration helper is itself R2024b-gated and idempotent.
virtualVcuModels = fullfile(fileparts(root), 'virtual-vcu', 'models');
addpath(virtualVcuModels);
add_virtual_vcu_to_model(modelPath);
patch_virtual_vcu_chart(modelPath);
patch_virtual_vcu_inputs(modelPath);
patch_virtual_vcu_state_outputs(modelPath);

fprintf('Created %s and %s with MATLAB %s.\n', ...
    modelPath, dictionaryPath, version('-release'));
end

function prepareOutput(path, force)
if isfile(path)
    if ~force
        error('inverterhil:ArtifactExists', ...
            'Artifact exists; call build_inverter_hil_model(true): %s', path);
    end
    delete(path);
end
end

function createDictionary(path)
dictionary = Simulink.data.dictionary.create(path);
cleanup = onCleanup(@() close(dictionary));
section = getSection(dictionary, 'Design Data');

addEntry(section, 'hil_model_release', 'R2024b');
addEntry(section, 'hil_base_sample_s', parameter(1e-3, 1e-3, 1e-3));
addEntry(section, 'hil_status_sample_s', parameter(statusPeriodS(), ...
    statusPeriodS(), statusPeriodS()));
% Each GUI-owned tunable below is a scalar dictionary entry with the exact
% flatPath name +INVERTERHILGUI/PARAMETERCONTRACT.M declares, so
% DISCOVERCONTRACT resolves every required logical name once the block
% referencing it (see ADDGUICOMMANDPARAMETERS) survives code generation.
addEntry(section, 'hil_cmd_pedals_throttle', parameter(0, 0, 1));
addEntry(section, 'hil_cmd_pedals_brake', parameter(0, 0, 1));
% Synchronized MTi-680G/Bosch LWS sensor stimulus. The steering bound is the
% Bosch LWS measuring range (+/-780 deg, see REFERENCES/SENSORS and
% INVERTER_HIL/STEERING-SENSOR/PROTOCOL.MD), not an arbitrary GUI limit, so
% the dictionary clamp and the encoder's range check agree.
addEntry(section, 'hil_cmd_steering_angle_deg', parameter(0, -780, 780));
addEntry(section, 'hil_cmd_steering_dropout', parameter(false, false, true));
addEntry(section, 'hil_cmd_imu_dropout', parameter(false, false, true));
% XCP-tunable pedal demand (0-100%, CarMaker's own units) and the
% source-select flag choosing whether Pedal Voltage Calibration reads these
% (normalized to 0-1) or the GUI-owned hil_cmd_pedals_throttle/brake above.
% Distinct entries, not an alias for the GUI ones -- see
% virtual-vcu/docs/carmaker_speedgoat_interface.md section 7 item 2. Default
% inactive (false), so a build with nothing driving these behaves exactly as
% before this entry existed.
addEntry(section, 'hil_cmd_xcp_pedals_throttle', parameter(0, 0, 100));
addEntry(section, 'hil_cmd_xcp_pedals_brake', parameter(0, 0, 100));
addEntry(section, 'hil_cmd_xcp_pedals_active', parameter(false, false, true));
% TestPoint preserves a signal for target inspection, but an ASAP2/A2L
% measurement also needs a resolved Signal object with non-auto storage.
% PATCH_VIRTUAL_VCU_STATE_OUTPUTS binds each Signal Copy output to one of
% these objects.
addVirtualVcuMeasurementSignals(section);
addEntry(section, 'hil_cmd_pedals_plausibility_override', ...
    parameter(false, false, true));
addEntry(section, 'hil_cmd_digital_main_button', parameter(false, false, true));
addEntry(section, 'hil_cmd_digital_cooling_switch', ...
    parameter(false, false, true));
addEntry(section, 'hil_cmd_digital_shutdown_feedback', ...
    parameter(false, false, true));
addEntry(section, 'hil_cmd_digital_precharge_sequence', ...
    parameter(uint32(0), uint32(0), intmax('uint32')));
addEntry(section, 'hil_cmd_digital_main_button_sequence', ...
    parameter(uint32(0), uint32(0), intmax('uint32')));
addEntry(section, 'hil_cmd_dc_link12_v', ...
    parameter(0, 0, 1023.984375));
addEntry(section, 'hil_cmd_dc_link34_v', ...
    parameter(0, 0, 1023.984375));
for channel = 1:4
    addEntry(section, sprintf('hil_cmd_inverter%d_load_nm', channel), ...
        parameter(0, -200, 200));
    addEntry(section, sprintf('hil_cmd_inverter%d_connected', channel), ...
        parameter(true, false, true));
    addEntry(section, sprintf('hil_cmd_inverter%d_fault_mask', channel), ...
        parameter(uint32(0), uint32(0), intmax('uint32')));
end
addEntry(section, 'hil_cmd_can_drop_control_mask', ...
    parameter(uint8(0), uint8(0), uint8(255)));
addEntry(section, 'hil_cmd_can_drop_status_mask', ...
    parameter(uint16(0), uint16(0), uint16(65535)));
addEntry(section, 'hil_cmd_gui_heartbeat', parameter(uint32(0), ...
    uint32(0), intmax('uint32')));
for channel = 1:4
    addEntry(section, sprintf('hil_cal_pedals_released_v%d', channel), ...
        parameter(NaN, 0, 5));
    addEntry(section, sprintf('hil_cal_pedals_pressed_v%d', channel), ...
        parameter(NaN, 0, 5));
end

addEntry(section, 'hil_safe_analog_reset_v', parameter(zeros(1, 4), ...
    zeros(1, 4), zeros(1, 4)));
addEntry(section, 'hil_safe_digital_reset', parameter(false(1, 8), false, false));

addEntry(section, 'hil_control_can_ids', uint32(hex2dec( ...
    {'186', '196', '1A6', '1B6'})));
addEntry(section, 'hil_status_can_ids', uint32(hex2dec( ...
    {'383', '385', '393', '395', '3A3', '3A5', '3B3', '3B5', '400'})));
% Torque scale RESOLVED 2026-08-02 by firmware evidence (see
% INVERTERHIL.PROTOCOL's torqueProfiles.vcu256 comment): 1/256 Nm/count,
% profile 'ephorus3-v1.03-candidate-1over256', matching
% +INVERTERHIL/DEFAULTCALIBRATION.M's default.
addEntry(section, 'hil_torque_profile_id', ...
    'ephorus3-v1.03-candidate-1over256');
addEntry(section, 'hil_torque_scale_nm_per_count', 1 / 256);
addEntry(section, 'hil_torque_scale_verified', true);
% Operator-attested preflight: electrical levels, grounds, J3 isolation,
% polarity, and CAN termination on this IO183/IO614 bench have been
% verified hands-on (not by an automated check). See
% INVERTERHIL.ENFORCEHARDWAREPREFLIGHT and the Hardware I/O subsystem's
% Commented flag below, which this value gates.
addEntry(section, 'hil_hardware_preflight_complete', true);
addEntry(section, 'hil_torque_results_provisional', true);

saveChanges(dictionary);
end

function value = parameter(initialValue, minimum, maximum)
value = Simulink.Parameter(initialValue);
value.Min = double(min(minimum(:)));
value.Max = double(max(maximum(:)));
value.CoderInfo.StorageClass = 'SimulinkGlobal';
end

function addVirtualVcuMeasurementSignals(section)
%ADDVIRTUALVCUMEASUREMENTSIGNALS Add the explicit A2L measurement contract.
% Types and dimensions are inherited from the typed Signal Copy sources;
% duplicating them here would allow this dictionary contract to drift from the
% deployed-chart contract.
names = { ...
    'hil_obs_virtual_vcu_pedal_payload'; ...
    'hil_obs_virtual_vcu_state_id'; ...
    'hil_obs_virtual_vcu_main_enable'; ...
    'hil_obs_virtual_vcu_precharge_enable'; ...
    'hil_obs_virtual_vcu_inverter_control_enable'; ...
    'hil_obs_virtual_vcu_pedal_tx_count'; ...
    'hil_obs_virtual_vcu_control_frame_1'; ...
    'hil_obs_virtual_vcu_apps_brake_fault'; ...
    'hil_obs_virtual_vcu_torque_request_nm'};
descriptions = { ...
    'Virtual VCU transmitted pedal CAN payload.'; ...
    'Virtual VCU state identifier.'; ...
    'Virtual VCU main-enable output.'; ...
    'Virtual VCU precharge-enable output.'; ...
    'Virtual VCU inverter-control-enable output.'; ...
    'Virtual VCU pedal transmit counter.'; ...
    'Virtual VCU control-frame 1 CAN payload.'; ...
    'Virtual VCU APPS/brake plausibility-fault indicator.'; ...
    'Virtual VCU decoded torque request in Nm.'};
for index = 1:numel(names)
    value = Simulink.Signal;
    value.CoderInfo.StorageClass = 'ExportedGlobal';
    value.Description = descriptions{index};
    addEntry(section, names{index}, value);
end
end

function addArchitecture(model)
blocks = { ...
    'Test Inputs', [40 130 220 300]; ...
    'Fault Injection', [40 370 220 485]; ...
    'Pedal Sensor Emulation', [310 90 520 205]; ...
    'VCU Digital Interface', [310 235 520 350]; ...
    'IO614 CAN Interface', [310 390 520 545]; ...
    'Ephorus Channel 1', [630 80 850 185]; ...
    'Ephorus Channel 2', [630 220 850 325]; ...
    'Ephorus Channel 3', [630 360 850 465]; ...
    'Ephorus Channel 4', [630 500 850 605]; ...
    'Ephorus System Status', [960 210 1180 430]; ...
    'Measurements and Logging', [1280 200 1500 445]};
for index = 1:size(blocks, 1)
    add_block('simulink/Ports & Subsystems/Subsystem', ...
        [model '/' blocks{index, 1}], 'Position', blocks{index, 2});
end

buildTestInputs([model '/Test Inputs']);
buildFaultInputs([model '/Fault Injection']);
buildSafeInterface([model '/Pedal Sensor Emulation'], 2, 1, ...
    'zeros(1,4)', 'PedalVoltageV');
buildSafeInterface([model '/VCU Digital Interface'], 2, 1, ...
    'false(1,8)', 'DigitalStimulus');
buildCanInterface([model '/IO614 CAN Interface']);
for channel = 1:4
    buildChannel([model sprintf('/Ephorus Channel %d', channel)], channel);
end
buildSystemStatus([model '/Ephorus System Status']);
buildMeasurements([model '/Measurements and Logging']);

add_block('simulink/Signal Routing/Demux', [model '/Load Demux'], ...
    'Outputs', '4', 'Position', [260 276 265 344]);
add_block('simulink/Signal Routing/Demux', [model '/Fault Demux'], ...
    'Outputs', '4', 'Position', [560 520 565 588]);
add_block('simulink/Signal Routing/Demux', [model '/DC Link Demux'], ...
    'Outputs', '2', 'Position', [560 312 565 358]);

add_line(model, 'Test Inputs/1', 'Pedal Sensor Emulation/1', 'autorouting', 'on');
add_line(model, 'Fault Injection/1', 'Pedal Sensor Emulation/2', 'autorouting', 'on');
add_line(model, 'Test Inputs/2', 'VCU Digital Interface/1', 'autorouting', 'on');
add_line(model, 'Fault Injection/1', 'VCU Digital Interface/2', 'autorouting', 'on');
add_line(model, 'Test Inputs/3', 'IO614 CAN Interface/1', 'autorouting', 'on');
add_line(model, 'Ephorus System Status/1', 'IO614 CAN Interface/2', 'autorouting', 'on');
% The hardware boundary transmits these exact payloads over CAN. It reads
% them through this global Goto rather than an Inport so the boundary stays
% port-free and can be commented out (its safety gate) without disturbing
% the rest of the diagram -- and rather than recomputing the model step,
% which would create a second, independently-diverging state machine.
add_block('simulink/Signal Routing/Goto', [model '/Status Payloads Goto'], ...
    'GotoTag', 'EphorusStatusPayloads', 'TagVisibility', 'global', ...
    'Position', [1220 300 1300 320]);
add_line(model, 'Ephorus System Status/1', 'Status Payloads Goto/1', ...
    'autorouting', 'on');

% The received-frame observation has no consumer inside the model -- it
% exists purely so the GUI can READ it -- but a subsystem output port must
% still be connected or the diagram will not update. A Terminator is the
% established pattern this file already uses everywhere for exactly this
% (see ADDTERMINATEDINPUT and ADDGUICOMMANDPARAMETERS's Constant->Terminator
% pairs): a real consumer that keeps a signal live through code generation
% without implying anything downstream depends on its value.
%
% DATALOGGING is deliberately NOT set here, though an earlier version of
% this file did set it (alongside TESTPOINT) believing the Terminator alone
% might not survive optimization. That combination reliably crashed the
% HOST MATLAB process -- not the target -- with an access violation inside
% LIBMWSLRESTIME_XCP.DLL's AsyncQueue::write/StreamingList teardown, every
% time STOP(TARGET) ran while this port's logged stream was active
% (confirmed against four separate matlab_crash_dump.* traces, same top two
% frames each time; GETCRASHSTACK on the target found no corresponding
% target-side fault, so the deployed application itself was never at fault).
% DataLogging opens a persistent host-side signal-streaming subscription
% distinct from GETSIGNAL's own one-shot reads, and it is that subscription
% whose teardown was crashing. The Terminator was always sufficient by
% itself -- this file's own established pattern proves it -- so there was
% nothing to gain from DataLogging and a live MATLAB session to lose.
add_block('simulink/Sinks/Terminator', ...
    [model '/Received Control Observation Terminator'], ...
    'Position', [1220 350 1240 370]);
add_line(model, 'Ephorus System Status/2', ...
    'Received Control Observation Terminator/1', 'autorouting', 'on');

% Port 3 (the four measured Rail Monitor AI channels, Fix 1) has no
% consumer inside the model either -- it exists purely so the GUI can READ
% it -- so it gets the same Terminator treatment as port 2 above, for the
% same reason: a subsystem output port must be connected for the diagram to
% update, and a Terminator is a real, permanent consumer that implies
% nothing about downstream use.
add_block('simulink/Sinks/Terminator', ...
    [model '/Analog Input Telemetry Terminator'], ...
    'Position', [1220 390 1240 410]);
add_line(model, 'Ephorus System Status/3', ...
    'Analog Input Telemetry Terminator/1', 'autorouting', 'on');
% Port 5 is the shared vehicle state (see BUILDSTATUSCYCLE's Port 5 note).
% Published as a global Goto so the synchronized MTi/LWS encoders inside
% IO614 CAN INTERFACE observe the same tick the inverter plant produced.
% A Goto is a real consumer, so unlike ports 2 and 3 above this needs no
% Terminator. Port 4 (TRANSMITCOUNT) is read by the GUI straight off the
% subsystem port and has no model-level consumer either.
add_block('simulink/Signal Routing/Goto', [model '/Vehicle State Goto'], ...
    'GotoTag', 'HILSharedVehicleState', 'TagVisibility', 'global', ...
    'Position', [1220 430 1300 450]);
add_line(model, 'Ephorus System Status/5', 'Vehicle State Goto/1', ...
    'autorouting', 'on');
add_line(model, 'Test Inputs/4', 'Load Demux/1', 'autorouting', 'on');
add_line(model, 'Test Inputs/5', 'DC Link Demux/1', 'autorouting', 'on');
add_line(model, 'Fault Injection/2', 'Fault Demux/1', 'autorouting', 'on');

for channel = 1:4
    channelName = sprintf('Ephorus Channel %d', channel);
    add_line(model, 'IO614 CAN Interface/1', [channelName '/1'], 'autorouting', 'on');
    add_line(model, sprintf('Load Demux/%d', channel), ...
        [channelName '/2'], 'autorouting', 'on');
    dcPort = 1 + (channel > 2);
    add_line(model, sprintf('DC Link Demux/%d', dcPort), ...
        [channelName '/3'], 'autorouting', 'on');
    add_line(model, sprintf('Fault Demux/%d', channel), ...
        [channelName '/4'], 'autorouting', 'on');
    add_line(model, [channelName '/1'], ...
        sprintf('Ephorus System Status/%d', 2 * channel - 1), 'autorouting', 'on');
    add_line(model, [channelName '/2'], ...
        sprintf('Ephorus System Status/%d', 2 * channel), 'autorouting', 'on');
    add_line(model, [channelName '/3'], ...
        sprintf('Measurements and Logging/%d', channel + 1), 'autorouting', 'on');
end
add_line(model, 'IO614 CAN Interface/2', ...
    'Measurements and Logging/1', 'autorouting', 'on');
end

function buildTestInputs(path)
clearSubsystem(path);
values = {'[0 0]', 'false(1,8)', 'zeros(4,8,''uint8'')', ...
    'zeros(1,4)', '[0 0]'};
names = {'PedalCommand', 'DigitalCommand', 'ControlFrames', ...
    'LoadTorqueNm', 'DCLinkV'};
for index = 1:5
    y = 35 + 55 * (index - 1);
    add_block('simulink/Sources/Constant', [path '/Safe ' names{index}], ...
        'Value', values{index}, 'SampleTime', '0.001', ...
        'Position', [35 y 115 y + 25]);
    add_block('simulink/Sinks/Out1', [path '/' names{index}], ...
        'Port', num2str(index), 'Position', [150 y 180 y + 20]);
    add_line(path, ['Safe ' names{index} '/1'], [names{index} '/1']);
end
end

function buildFaultInputs(path)
clearSubsystem(path);
addConstantOut(path, 'PreflightSafe', 'false', 1, 40);
addConstantOut(path, 'FaultMask', 'zeros(1,4,''uint32'')', 2, 95);
end

function buildSafeInterface(path, inputCount, outputCount, value, outputName)
clearSubsystem(path);
for index = 1:inputCount
    add_block('simulink/Sources/In1', sprintf('%s/Input%d', path, index), ...
        'Port', num2str(index), 'Position', [25 35 + 55 * index 55 55 + 55 * index]);
    add_block('simulink/Sinks/Terminator', sprintf('%s/Input%d Terminator', path, index), ...
        'Position', [90 35 + 55 * index 110 55 + 55 * index]);
    add_line(path, sprintf('Input%d/1', index), sprintf('Input%d Terminator/1', index));
end
for index = 1:outputCount
    addConstantOut(path, outputName, value, index, 45);
end
end

function buildCanInterface(path)
clearSubsystem(path);
addTerminatedInput(path, 'ControlFramesRaw', 1, 45);
addTerminatedInput(path, 'StatusPayloads', 2, 100);
addConstantOut(path, 'DecodedCommands', 'zeros(4,8,''uint8'')', 1, 45);
addConstantOut(path, 'CANDiagnostics', 'zeros(1,8,''uint32'')', 2, 110);
end

function buildChannel(path, channel)
clearSubsystem(path);
inputNames = {'DecodedCommands', 'LoadTorqueNm', 'DCLinkV', 'FaultMask'};
for index = 1:4
    addTerminatedInput(path, inputNames{index}, index, 25 + 45 * index);
end
addConstantOut(path, sprintf('Status3X3_Ch%d', channel), ...
    'zeros(1,8,''uint8'')', 1, 45);
addConstantOut(path, sprintf('Status3X5_Ch%d', channel), ...
    'zeros(1,8,''uint8'')', 2, 100);
addConstantOut(path, sprintf('Observations_Ch%d', channel), ...
    'zeros(1,16)', 3, 155);
end

function buildSystemStatus(path)
clearSubsystem(path);
for index = 1:8
    addTerminatedInput(path, sprintf('StatusInput%d', index), index, 15 + 35 * index);
end
% StatusInput1-8 (each channel's Status3X3/Status3X5) stay terminated:
% Ephorus Channel 1-4 remain constant-zero scaffold (see
% ANNOTATIONDOESNOTOVERCLAIMFUNCTIONALCORE), so this cycle is computed
% independently by INVERTERHIL.STEPMODEL using its own persistent state
% rather than by combining those still-fake per-channel outputs.

% Received control and status frames, published by the hardware boundary.
% Retained in EPHORUS RX RETENTION below at the CAN Read block's own rate
% (1 ms, BUILDCANINTERFACE): the virtual VCU transmits five CAN IDs (the
% pedal broadcast plus four control frames) every 5 ms, 1000 msg/s, and a
% single FIFO pop every 5 ms only drains 200 msg/s -- the receive FIFO
% permanently fell behind, so the retained command was stale at best and,
% once the FIFO backed up, simply frozen: frames genuinely sent were never
% read. Draining at 1 ms matches the production rate. EPHORUS STATUS CYCLE
% further below keeps the state machine, plant, and CAN-write chain at the
% ORIGINAL 5 ms status-cycle rate, unchanged -- see that block for why it
% is not also sped up.
rxTags = {'EphorusRxDataPresent', 'EphorusRxId', 'EphorusRxExtended', ...
    'EphorusRxRemote', 'EphorusRxLength', 'EphorusRxData'};
for index = 1:numel(rxTags)
    fromName = sprintf('%s From', rxTags{index});
    add_block('simulink/Signal Routing/From', [path '/' fromName], ...
        'GotoTag', rxTags{index}, ...
        'Position', [60, 30 + 30 * index, 220, 50 + 30 * index]);
end
% The CAN control-frame drop mask (Fix 4) moves here from EPHORUS STATUS
% CYCLE's external inputs below: masking now happens where retention
% happens. Its GUI Command Parameters source already runs at the model's
% 1 ms base rate, the same rate this block now runs at, so no Rate
% Transition is needed for it (contrast the externalTags loop below, which
% still crosses from 1 ms into the 5 ms status-cycle rate).
dropControlFromName = 'GuiCmdCanDropControlMask From';
add_block('simulink/Signal Routing/From', [path '/' dropControlFromName], ...
    'GotoTag', 'GuiCmdCanDropControlMask', ...
    'Position', [60, 30 + 30 * (numel(rxTags) + 1), 220, ...
    50 + 30 * (numel(rxTags) + 1)]);

retentionFcnPath = [path '/Ephorus RX Retention'];
add_block('simulink/User-Defined Functions/MATLAB Function', retentionFcnPath, ...
    'Position', [250 45 430 220]);
setMatlabFunctionScript(retentionFcnPath, rxRetentionScript());
for index = 1:numel(rxTags)
    add_line(path, sprintf('%s From/1', rxTags{index}), ...
        sprintf('Ephorus RX Retention/%d', index), 'autorouting', 'on');
end
add_line(path, [dropControlFromName '/1'], ...
    sprintf('Ephorus RX Retention/%d', numel(rxTags) + 1), 'autorouting', 'on');

% One Rate Transition brings EPHORUS RX RETENTION's flattened 13x14
% observation matrix from its 1 ms rate down to EPHORUS STATUS CYCLE's
% 5 ms rate -- the same zero-order-hold pattern the externalTags loop below
% already uses for GUI commands crossing the same two rates.
obsRtPath = [path '/Ephorus RX Observation RT'];
add_block('simulink/Signal Attributes/Rate Transition', obsRtPath, ...
    'Position', [460 60 480 80]);
add_line(path, 'Ephorus RX Retention/1', 'Ephorus RX Observation RT/1', ...
    'autorouting', 'on');

fcnPath = [path '/Ephorus Status Cycle'];
add_block('simulink/User-Defined Functions/MATLAB Function', fcnPath, ...
    'Position', [520 45 700 220]);
setMatlabFunctionScript(fcnPath, statusCycleScript());
add_line(path, 'Ephorus RX Observation RT/1', 'Ephorus Status Cycle/1', ...
    'autorouting', 'on');

add_block('simulink/Sinks/Out1', [path '/OrderedStatusPayloads'], ...
    'Port', '1', 'Position', [745 60 775 80]);
add_line(path, 'Ephorus Status Cycle/1', 'OrderedStatusPayloads/1');

% Port 2 publishes what the target actually RECEIVED (rows 1:4 are control
% RX; rows 5:13 are inverter status RX), still at the 5 ms rate this port
% always ran at -- that cadence was never the bottleneck; CAN READ popping
% the FIFO fast enough was. GETSIGNAL can only read signals on wires, so
% without this port the GUI has no way to observe received traffic at all.
% Terminated rather than left unconnected because nothing in the model
% consumes it; the GUI reads the port directly.
add_block('simulink/Sinks/Out1', [path '/ReceivedControlObservation'], ...
    'Port', '2', 'Position', [745 120 775 140]);
add_line(path, 'Ephorus Status Cycle/2', 'ReceivedControlObservation/1');

% Port 3: the four IO183 Rail Monitor AI channels, read back into "measured
% pedal voltage" GUI telemetry (see PINOUTS.MD S4.2 and
% ADDHARDWAREBOUNDARY's Analog Inputs Goto). A straight passthrough with no
% logic of its own -- not part of either MATLAB Function block above -- so
% it is wired here as a separate From/Out1 pair rather than as another
% chart input, per Fix 1's explicit instruction not to feed this into
% INVERTERHIL.STEPMODEL/the plant.
add_block('simulink/Signal Routing/From', [path '/Analog Inputs From'], ...
    'GotoTag', 'AnalogInputsV', 'Position', [300 240 420 260]);
% AnalogInputsV is a bare passthrough with no other consumer in the model
% (same shape as the Virtual VCU state observers PATCH_VIRTUAL_VCU_STATE_
% OUTPUTS.M documents), so Simulink's block-IO optimization collapses its
% storage onto the upstream signal and GETSIGNAL on the Out1 below fails
% with "Add a SignalCopy block". Fix is the same one that script uses: a
% Signal Conversion block (ConversionOutput='Signal copy') with its output
% port TestPoint='on', which forces independent, non-optimizable storage.
copyBlock = add_block('simulink/Signal Attributes/Signal Conversion', ...
    [path '/Analog Inputs Signal Copy'], 'ConversionOutput', 'Signal copy', ...
    'Position', [445 240 475 260]);
copyPorts = get_param(copyBlock, 'PortHandles');
set_param(copyPorts.Outport, 'TestPoint', 'on');
add_block('simulink/Sinks/Out1', [path '/AnalogInputTelemetry'], ...
    'Port', '3', 'Position', [545 240 575 260]);
add_line(path, 'Analog Inputs From/1', 'Analog Inputs Signal Copy/1');
add_line(path, 'Analog Inputs Signal Copy/1', 'AnalogInputTelemetry/1');

% Port 4: a genuine, target-measured count of status-cycle payloads this
% block has emitted (see STATUSCYCLESCRIPT's TXCOUNT comment) -- the CAN
% Write blocks' own driver exposes no cumulative transmit counter, so this
% is the closest real signal to "messages sent" available without adding a
% counter per CAN Write. Lets the GUI show an honest, target-measured
% count instead of the dashed rate column, the same way ACCEPTEDCOUNT
% already does on the RX side.
add_block('simulink/Sinks/Out1', [path '/TransmitCount'], ...
    'Port', '4', 'Position', [745 180 775 200]);
add_line(path, 'Ephorus Status Cycle/3', 'TransmitCount/1');

% Port 5: the shared vehicle state EPHORUSSYSTEMSTATUSSTEP advances from the
% same inverter-plant tick (INVERTERHIL.STEPVEHICLESTATE). Published so the
% synchronized MTi/LWS encoders in BUILDCANINTERFACE observe the SAME state
% the inverter plant produced this step instead of running as an unrelated
% signal generator -- that shared tick is the whole point of the sensor
% co-simulation. Port 4 is TRANSMITCOUNT above, so this continues at 5;
% master's copy of this file uses port 4 because it has no transmit counter.
add_block('simulink/Sinks/Out1', [path '/VehicleStateFromStatusCycle'], ...
    'Port', '5', 'Position', [745 240 775 260]);
add_line(path, 'Ephorus Status Cycle/4', 'VehicleStateFromStatusCycle/1');

% GUI-commanded per-channel load torque, connected flag, and pair DC-link
% voltage (Fix 2): sourced from GUI COMMAND PARAMETERS' Gotos (see
% GUICOMMANDGOTOTAGS) rather than the dead "Ephorus Channel 1-4" scaffold's
% Load/DC Link/Fault Demux inputs, matching how the CAN RX path above
% already bypasses that scaffold. Port 1 is the rate-transitioned
% observation matrix above; these continue directly after it.
% Each Goto above is sourced from a GUI COMMAND PARAMETERS Constant running
% at the model's 1 ms base rate, but EPHORUS STATUS CYCLE runs at the 5 ms
% status-cycle rate (inherited from the Rate Transition above, ultimately
% still the IO614 CAN Read block's ts before this fix). A MATLAB Function
% block requires consistent input rates, so each new input gets its own
% explicit Rate Transition rather than relying on the model-wide
% "automatically handle rate transition" diagnostic -- this keeps the
% 1 ms -> 5 ms conversion visible in the diagram instead of silently
% inserted, and it is a genuine zero-order hold, which is the correct
% behavior for a slowly-polled GUI command feeding a faster-declared
% consumer: the status cycle always sees the most recently written GUI
% value.
externalTags = { ...
    'GuiCmdInverter1LoadNm', 'GuiCmdInverter2LoadNm', ...
    'GuiCmdInverter3LoadNm', 'GuiCmdInverter4LoadNm', ...
    'GuiCmdInverter1Connected', 'GuiCmdInverter2Connected', ...
    'GuiCmdInverter3Connected', 'GuiCmdInverter4Connected', ...
    'GuiCmdDcLink12V', 'GuiCmdDcLink34V', 'GuiCmdSteeringAngleDeg'};
for index = 1:numel(externalTags)
    port = 1 + index;
    fromName = sprintf('%s From', externalTags{index});
    add_block('simulink/Signal Routing/From', [path '/' fromName], ...
        'GotoTag', externalTags{index}, ...
        'Position', [60, 30 + 30 * port, 190, 50 + 30 * port]);
    rtName = sprintf('%s RT', externalTags{index});
    add_block('simulink/Signal Attributes/Rate Transition', ...
        [path '/' rtName], ...
        'Position', [200, 30 + 30 * port, 220, 50 + 30 * port]);
    add_line(path, [fromName '/1'], [rtName '/1'], 'autorouting', 'on');
    add_line(path, [rtName '/1'], ...
        sprintf('Ephorus Status Cycle/%d', port), 'autorouting', 'on');
end
end

function buildMeasurements(path)
clearSubsystem(path);
for index = 1:5
    addTerminatedInput(path, sprintf('Observation%d', index), index, 25 + 50 * index);
end
end

function addTerminatedInput(path, name, port, y)
add_block('simulink/Sources/In1', [path '/' name], ...
    'Port', num2str(port), 'Position', [25 y 55 y + 20]);
add_block('simulink/Sinks/Terminator', [path '/' name ' Terminator'], ...
    'Position', [90 y 110 y + 20]);
add_line(path, [name '/1'], [name ' Terminator/1']);
end

function addConstantOut(path, name, value, port, y)
add_block('simulink/Sources/Constant', [path '/Safe ' name], ...
    'Value', value, 'SampleTime', '0.001', ...
    'Position', [35 y 125 y + 25]);
add_block('simulink/Sinks/Out1', [path '/' name], ...
    'Port', num2str(port), 'Position', [165 y 195 y + 20]);
add_line(path, ['Safe ' name '/1'], [name '/1']);
end

function clearSubsystem(path)
lineHandles = get_param(path, 'LineHandles');
fields = fieldnames(lineHandles);
for index = 1:numel(fields)
    handles = lineHandles.(fields{index});
    handles = handles(handles ~= -1);
    for handle = handles(:)'
        try %#ok<TRYNC>
            delete_line(handle);
        end
    end
end
blocks = find_system(path, 'SearchDepth', 1, 'Type', 'Block');
for index = 2:numel(blocks)
    delete_block(blocks{index});
end
end

function addHardwareBoundary(model)
load_system('canlib');
path = [model '/Hardware I O - PRE-FLIGHT DISABLED'];
add_block('simulink/Ports & Subsystems/Subsystem', path, ...
    'Position', [960 505 1500 720], ...
    'BackgroundColor', 'orange', ...
    'AttributesFormatString', ...
    ['LIVE - Commented flag and hil_hardware_preflight_complete both\n' ...
     'gate this subsystem open per operator hands-on IO183 attestation']);
clearSubsystem(path);

io183 = add_block('speedgoatlib_IO183/Setup', [path '/IO183 Setup'], ...
    'Position', [25 30 160 100]);
set_param(io183, 'parModuleId', '1', 'parPciSlot', '-1', ...
    'parDaSimult', 'on', 'parAdCoupling', 'Single Ended', ...
    'parAdRange', '0..5V', 'parAdChannelLow', '1', ...
    'parAdChannelHigh', '4', 'parDaChannels', '[1 2 3 4]', ...
    'parDaRange', '0..5V', 'parDaInit', '[0 0 0 0]', ...
    'parDaReset', '[0 0 0 0]', 'parDoChannels', '[1 2 3 4 5 6 7 8]', ...
    'parDoInit', '[0 0 0 0 0 0 0 0]', ...
    'parDoReset', '[0 0 0 0 0 0 0 0]', ...
    'parDiChannels', '[9 10 11 12 13]', ...
    'parIOPullReferenceFront', 'Pull-down');

ao = add_block('speedgoatlib_IO183/Analog Output', ...
    [path '/IO183 AO01-AO04 Safe Zero'], 'Position', [25 130 170 185]);
set_param(ao, 'parModuleId', '1', 'parSampTime', '0.001', ...
    'parDaSimult', 'on', 'parDaChannels', '[1 2 3 4]', ...
    'parDaInit', '[0 0 0 0]', 'parDaReset', '[0 0 0 0]');
ai = add_block('speedgoatlib_IO183/Analog Input', ...
    [path '/IO183 AI01-AI04 Rail Monitor'], 'Position', [25 215 170 270]);
set_param(ai, 'parModuleId', '1', 'parSampTime', '0.001', ...
    'parAdChannelLow', '1', 'parAdChannelHigh', '4');

% Despite the "Rail Monitor" block name, these 4 channels are NOT a DC
% electrical bus/rail voltage monitor -- per PINOUTS.MD S4.2 they are
% harness taps reading 5V_THROTTLE_1, 5V_THROTTLE_2, 5V_BP_1, 5V_BP_2: a
% self-loopback readback of the same pedal voltage lines the AO block above
% commands. This routes the 4 previously-unconnected output ports (verified
% with PortHandles before this fix: all 4 were -1, not even a Terminator)
% out for "measured pedal voltage" GUI telemetry alongside the existing
% commanded value, mirroring the EphorusStatusPayloads/EphorusRx* Goto/From
% convention rather than adding a port to this port-free boundary.
% Deliberately NOT fed into INVERTERHIL.STEPMODEL/the plant: this is a
% hardware self-check telemetry signal, unrelated to the DC-link voltage
% STEPMODEL already computes DCLINK12/34ABOVEMINIMUM from.
add_block('simulink/Signal Routing/Mux', [path '/Analog Input Mux'], ...
    'Inputs', '4', 'Position', [195 215 215 270]);
for port = 1:4
    add_line(path, sprintf('IO183 AI01-AI04 Rail Monitor/%d', port), ...
        sprintf('Analog Input Mux/%d', port), 'autorouting', 'on');
end
add_block('simulink/Signal Routing/Goto', [path '/Analog Inputs Goto'], ...
    'GotoTag', 'AnalogInputsV', 'TagVisibility', 'global', ...
    'Position', [235 232 340 252]);
add_line(path, 'Analog Input Mux/1', 'Analog Inputs Goto/1', ...
    'autorouting', 'on');

dio = add_block('speedgoatlib_IO183/Digital Output', ...
    [path '/IO183 DIO01-DIO08 Safe Zero'], 'Position', [25 300 170 355]);
set_param(dio, 'parModuleId', '1', 'parSampTime', '0.001', ...
    'parDoChannels', '[1 2 3 4 5 6 7 8]', ...
    'parDoInit', '[0 0 0 0 0 0 0 0]', ...
    'parDoReset', '[0 0 0 0 0 0 0 0]');
di = add_block('speedgoatlib_IO183/Digital Input', ...
    [path '/IO183 DIO09-DIO13 VCU Monitor'], 'Position', [25 385 170 440]);
set_param(di, 'parModuleId', '1', 'parSampTime', '0.001', ...
    'parDiChannels', '[9 10 11 12 13]');

% Publish DIO09-13 as a global tag, mirroring AnalogInputsV above. On this
% bench there is no real VCU, so these 5 pins are repurposed as a
% self-loop readback of Module 1's own DIO01-04 stimulus outputs
% (precharge/main/cooling/shutdown-feedback) -- the same self-loop pattern
% already used for analog. The Virtual VCU chart reads this vector (see
% VIRTUAL-VCU/MODELS/PATCH_VIRTUAL_VCU_INPUTS.M) instead of Module 2's own
% (physically disconnected) IO183 DI channels.
add_block('simulink/Signal Routing/Mux', [path '/VCU Monitor Pins Mux'], ...
    'Inputs', '5', 'Position', [195 385 215 440]);
for port = 1:5
    add_line(path, sprintf('IO183 DIO09-DIO13 VCU Monitor/%d', port), ...
        sprintf('VCU Monitor Pins Mux/%d', port), 'autorouting', 'on');
end
add_block('simulink/Signal Routing/Goto', [path '/VCU Monitor Pins Goto'], ...
    'GotoTag', 'VcuMonitorPins', 'TagVisibility', 'global', ...
    'Position', [235 402 340 422]);
add_line(path, 'VCU Monitor Pins Mux/1', 'VCU Monitor Pins Goto/1', ...
    'autorouting', 'on');

setup = add_block('speedgoatlib_IO614/CAN and LIN Setup ', ...
    [path '/IO614 CAN Setup'], 'Position', [235 30 390 100]);
set_param(setup, 'moduleType', 'IO614', 'id', '1', ...
    'canChn1', 'CAN (HS)', 'canChn2', 'CAN (HS)', ...
    'canChn3', 'Disabled', 'canChn4', 'Disabled', ...
    'arbBdrChn1', '1.0 MBaud', 'arbBdrChn2', '1.0 MBaud');
read = add_block('speedgoatlib_IO614/CAN Read ', ...
    [path '/IO614 CAN FIFO Read Raw'], 'Position', [235 130 390 190]);
% useBusOut is ON so port 2 is a CAN_MESSAGE bus the Rx Bus Selector can
% split into ID/Extended/Remote/Length/Data. With it off the port is not a
% bus and the selector cannot resolve it.
%
% ts is 0.001, the model's base rate, matching every other IO183/IO614
% block that isn't explicitly on the 5 ms status-cycle rate. This is a
% single FIFO read per 1 ms tick: the virtual VCU transmits five CAN IDs
% (the pedal broadcast plus four control frames) every 5 ms -- 1000 msg/s
% -- and reading once per 5 ms tick (200 msg/s) permanently fell behind,
% so the receive FIFO backed up and the retained command was stale at best
% and, once the buffer filled, simply frozen: frames genuinely sent were
% never read. Reading once per 1 ms tick (1000 msg/s) matches that rate.
%
% A naive earlier attempt raised this same ts without anything else
% changing, which put the WHOLE status-cycle chain (state machine, plant,
% CAN Pack/Write) this reading fed on a 1 ms rate that collided with the
% CAN Write blocks' own explicit 5 ms rate. The received frame now instead
% drives EPHORUS RX RETENTION (a small, separate 1 ms MATLAB Function
% block; see BUILDSYSTEMSTATUS/RXRETENTIONSCRIPT) that only drains and
% retains; EPHORUS STATUS CYCLE (STATUSCYCLESCRIPT), which still owns the
% state machine/plant/CAN-write chain, is unchanged at 5 ms, joined to the
% fast block by one Rate Transition. TESTMODELARTIFACTS'
% io614CanAndOrderedWritesAreExact locks in both halves of that split so
% neither this rate nor the CAN Write rate can drift back out of sync
% silently.
set_param(read, 'moduleType', 'IO614', 'id', '1', 'channel', '1', ...
    'canType', 'CAN (HS)', 'useBusOut', 'on', ...
    'HasMulRead', 'Single Read from Buffer (FIFO)', ...
    'LabelInHex', 'on', 'ts', '0.001');
% Received Ephorus control frames leave the boundary through global Gotos,
% mirroring how the transmitted payloads enter it. EPHORUSSYSTEMSTATUSSTEP
% retains them into its decoder bank so the four channels can actually
% respond to a commanding VCU (see INVERTERHIL.STEPMODEL).
%
% NOTE: this is the first signal that flows OUT of the boundary. The
% transmitted-payload Goto lives outside and the boundary only reads it, so
% commenting the boundary left that path intact. These Gotos are inside, so
% commenting the boundary removes them and the matching Froms below lose
% their source. The boundary is currently live and its preflight gate was
% bypassed by operator decision, so that is not a live problem -- but it is
% a real narrowing of the "boundary can be commented out" property and must
% be restored (for example by grounding the Froms) if that gate returns.
rxSelector = add_block('simulink/Signal Routing/Bus Selector', ...
    [path '/Rx Bus Selector'], 'Position', [455 480 465 570]);
set_param(rxSelector, 'OutputSignals', 'ID,Extended,Remote,Length,Data');
add_line(path, 'IO614 CAN FIFO Read Raw/2', 'Rx Bus Selector/1', ...
    'autorouting', 'on');

rxTags = {'EphorusRxDataPresent', 'EphorusRxId', 'EphorusRxExtended', ...
    'EphorusRxRemote', 'EphorusRxLength', 'EphorusRxData'};
% Port 1 of the read block is "Data present"; ports 1-5 of the selector are
% ID, Extended, Remote, Length, Data in the order set above.
rxSources = {'IO614 CAN FIFO Read Raw/1', 'Rx Bus Selector/1', ...
    'Rx Bus Selector/2', 'Rx Bus Selector/3', 'Rx Bus Selector/4', ...
    'Rx Bus Selector/5'};
for index = 1:numel(rxTags)
    gotoName = sprintf('%s Goto', rxTags{index});
    add_block('simulink/Signal Routing/Goto', [path '/' gotoName], ...
        'GotoTag', rxTags{index}, 'TagVisibility', 'global', ...
        'Position', [540, 470 + 30 * index, 700, 490 + 30 * index]);
    add_line(path, rxSources{index}, [gotoName '/1'], 'autorouting', 'on');
end

status = add_block('speedgoatlib_IO614/CAN Status ', ...
    [path '/IO614 CAN Diagnostics'], 'Position', [235 220 390 280]);
set_param(status, 'moduleType', 'IO614', 'id', '1', 'channel', '1', ...
    'canType', 'CAN (HS)', 'autoRecovery', 'off', 'ts', '0.001');

ids = hex2dec({'383', '385', '393', '395', '3A3', ...
    '3A5', '3B3', '3B5', '400'});
for index = 1:numel(ids)
    row = mod(index - 1, 5);
    column = floor((index - 1) / 5);
    block = add_block('speedgoatlib_IO614/CAN Write ', ...
        sprintf('%s/CAN Write 0x%03X', path, ids(index)), ...
        'Position', [455 + 190 * column, 30 + 80 * row, ...
        610 + 190 * column, 85 + 80 * row]);
    % enableInput ("Show Transmission Control Input") adds a Tx Control
    % input port (port 1; the CAN Msg data port becomes port 2). When Tx
    % Control is false this CAN Write block genuinely does not transmit
    % that tick -- a real absence on the wire, not a zeroed payload -- which
    % is what Fix 4's hil_cmd_can_drop_status_mask requires. See the "Status
    % Transmit Mask" wiring below.
    set_param(block, 'moduleType', 'IO614', 'id', '1', ...
        'channel', '1', 'canType', 'CAN (HS)', 'useBusIn', 'off', ...
        'numOfMsg', '1', 'enableStatusPort', 'on', 'enableInput', 'on', ...
        'ts', num2str(statusPeriodS()), ...
        'UserData', uint32(ids(index)), 'UserDataPersistent', 'on', ...
        'Description', sprintf('Ordered Ephorus status ID 0x%03X', ids(index)));
end

% Independent MTi-680G and Bosch LWS simulation. Both encode the shared
% vehicle state produced by EPHORUSSYSTEMSTATUSSTEP, so their frames carry
% the same simulation tick the inverter status frames do.
%
% CHANNEL SELECTION -- branch-specific, see MTI680_LWS_INTEGRATION_PLAN.MD
% "Branch-specific model locations". These writes stay on IO614 id 1,
% channel 1 / Port B: the inverter HIL rig's own transmit boundary, the same
% channel master uses. They are deliberately NOT moved to channel 2 / Port A.
% Port A is the VIRTUAL VCU's transmit boundary (ADD_VIRTUAL_VCU_TO_MODEL.M),
% and the LWS/MTi are sensors a VCU READS, not signals it sources -- putting
% them on Port A would model the VCU transmitting its own steering sensor.
% Port A and Port B are one bus (the internal loopback PINOUTS.MD S5 and
% virtual-vcu/docs/carmaker_speedgoat_interface.md describe), so a frame
% written here is received by the virtual VCU's Port A CAN Read exactly the
% way this model's Ephorus status frames already reach it. No additional
% Port A writes are required, and adding a second transmitter for these IDs
% would put two drivers on one ID. Sensor IDs 0x032/0x034/0x2B0 collide with
% neither the virtual VCU's 0x186/0x196/0x1A6/0x1B6/0x1F5 nor the nine
% Ephorus status IDs.
sensorFrom = add_block('simulink/Signal Routing/From', ...
    [path '/Shared Vehicle State From'], 'GotoTag', ...
    'HILSharedVehicleState', 'Position', [25 820 170 840]);
steeringFrom = add_block('simulink/Signal Routing/From', ...
    [path '/Steering Angle From'], 'GotoTag', 'GuiCmdSteeringAngleDeg', ...
    'Position', [25 850 170 870]);
imuDropFrom = add_block('simulink/Signal Routing/From', ...
    [path '/IMU Dropout From'], 'GotoTag', 'GuiCmdImuDropout', ...
    'Position', [25 880 170 900]);
lwsDropFrom = add_block('simulink/Signal Routing/From', ...
    [path '/LWS Dropout From'], 'GotoTag', 'GuiCmdSteeringDropout', ...
    'Position', [25 910 170 930]);
sensorFcnPath = [path '/Synchronized Sensor Payloads'];
add_block('simulink/User-Defined Functions/MATLAB Function', sensorFcnPath, ...
    'Position', [280 820 480 960]);
setMatlabFunctionScript(sensorFcnPath, sensorPayloadScript());
% The vehicle state already arrives at the 5 ms status rate, but the three
% GUI command Gotos run at the model's 1 ms base rate. A MATLAB Function
% block requires consistent input rates, and this model has concurrent
% execution enabled, which forbids an implicit rate transition -- without
% these the block resolves to 1 ms and every CAN Pack/CAN Write pair in this
% subsystem fails with IllegalIPortRateTransForConcurrentExecution, the
% existing status frames included. Explicit Rate Transitions keep the
% 1 ms -> 5 ms zero-order hold visible in the diagram, exactly as
% BUILDSTATUSCYCLE does for the status chart's own GUI inputs.
sensorInputs = {sensorFrom, steeringFrom, imuDropFrom, lwsDropFrom};
for index = 1:numel(sensorInputs)
    sourceName = get_param(sensorInputs{index}, 'Name');
    if index == 1
        % Already at the status rate; no transition needed.
        add_line(path, [sourceName '/1'], ...
            sprintf('Synchronized Sensor Payloads/%d', index));
        continue
    end
    rtName = sprintf('%s RT', sourceName);
    add_block('simulink/Signal Attributes/Rate Transition', ...
        [path '/' rtName], ...
        'Position', [200, 820 + 30 * (index - 1), 220, 840 + 30 * (index - 1)]);
    add_line(path, [sourceName '/1'], [rtName '/1'], 'autorouting', 'on');
    add_line(path, [rtName '/1'], ...
        sprintf('Synchronized Sensor Payloads/%d', index), 'autorouting', 'on');
end
% MsgLength is the sensor's real DLC (MTi 6, Bosch LWS_Standard 5), not the
% Ephorus status frames' 8 -- PACKMTI680PAYLOAD/PACKLWSPAYLOAD size their
% payloads to match (see commit 704f0f7).
sensorIds = [hex2dec('034'), hex2dec('032'), hex2dec('2B0')];
sensorLengths = [6 6 5];
for index = 1:3
    name = sprintf('CAN Pack Sensor 0x%03X', sensorIds(index));
    packBlock = add_block('canlib/CAN Pack', [path '/' name], ...
        'Position', [530 820 + 55 * (index - 1) 650 855 + 55 * (index - 1)]);
    set_param(packBlock, 'DataFormat', 'raw data', 'MsgIDType', ...
        'Standard (11-bit identifier)', 'MsgIdentifier', num2str(sensorIds(index)), ...
        'CANIDInput', 'off', 'MsgLength', num2str(sensorLengths(index)), ...
        'Remote', 'off', 'BusOutput', 'off', 'Description', ...
        sprintf('Packs independent sensor ID 0x%03X', sensorIds(index)));
    add_line(path, sprintf('Synchronized Sensor Payloads/%d', index), ...
        [name '/1']);
    writer = add_block('speedgoatlib_IO614/CAN Write ', ...
        sprintf('%s/CAN Write Sensor 0x%03X', path, sensorIds(index)), ...
        'Position', [710 820 + 55 * (index - 1) 890 855 + 55 * (index - 1)]);
    set_param(writer, 'moduleType', 'IO614', 'id', '1', 'channel', '1', ...
        'canType', 'CAN (HS)', 'useBusIn', 'off', 'numOfMsg', '1', ...
        'enableStatusPort', 'on', 'enableInput', 'on', ...
        'ts', num2str(statusPeriodS()), 'UserData', uint32(sensorIds(index)), ...
        'UserDataPersistent', 'on', 'Description', ...
        sprintf('Transmits independent sensor ID 0x%03X', sensorIds(index)));
    add_line(path, sprintf('Synchronized Sensor Payloads/%d', index + 3), ...
        sprintf('CAN Write Sensor 0x%03X/1', sensorIds(index)));
    add_line(path, [name '/1'], ...
        sprintf('CAN Write Sensor 0x%03X/2', sensorIds(index)));
end

% Fix 4: hil_cmd_can_drop_status_mask gates which of the nine status frames
% actually transmit, one Tx Control bit per CAN Write above, computed once
% by INVERTERHIL.STATUSTRANSMITMASK and split into nine scalars (a CAN
% Write's Tx Control port takes a scalar) because a MATLAB Function block
% cannot emit a bus without a Simulink.Bus definition -- the same reason
% EPHORUSSTATUSCYCLEFRAMES splits PAYLOADS into f1..f9 below. Sourced from
% GUI COMMAND PARAMETERS' Goto (see GUICOMMANDGOTOTAGS), matching the
% control-frame drop mask's route into EPHORUS STATUS CYCLE rather than a
% second, independent named-parameter reference to the same dictionary
% entry.
% Rate-transitioned for the same reason as EPHORUS STATUS CYCLE's new
% inputs above: the GUI Constant runs at the 1 ms base rate and the CAN
% Write blocks' Tx Control ports run at the 5 ms status-cycle rate.
add_block('simulink/Signal Routing/From', ...
    [path '/Drop Status Mask From'], ...
    'GotoTag', 'GuiCmdCanDropStatusMask', 'Position', [1030 300 1150 320]);
add_block('simulink/Signal Attributes/Rate Transition', ...
    [path '/Drop Status Mask RT'], 'Position', [1160 300 1180 320]);
add_line(path, 'Drop Status Mask From/1', 'Drop Status Mask RT/1');
transmitMaskFcnPath = [path '/Status Transmit Mask'];
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    transmitMaskFcnPath, 'Position', [1030 360 1210 400]);
setMatlabFunctionScript(transmitMaskFcnPath, statusTransmitMaskScript());
add_line(path, 'Drop Status Mask RT/1', 'Status Transmit Mask/1');
for index = 1:numel(ids)
    add_line(path, sprintf('Status Transmit Mask/%d', index), ...
        sprintf('CAN Write 0x%03X/1', ids(index)));
end

% Each CAN Write above (Speedgoat 'CAN' message-type mode) expects a single
% CAN_MESSAGE-typed input, which only a CAN Pack block produces -- not the
% eight raw bytes on their own. The real, correctly bit-packed nine-frame
% cycle is computed once in Ephorus System Status (see INVERTERHIL.STEPMODEL)
% and reaches this port-free subsystem through the global Goto/From tag, so
% the frames transmitted are exactly the payloads the rest of the model sees.
add_block('simulink/Signal Routing/From', [path '/Status Payloads From'], ...
    'GotoTag', 'EphorusStatusPayloads', 'Position', [25 470 160 490]);
framesFcnPath = [path '/Ephorus Status Cycle Frames'];
add_block('simulink/User-Defined Functions/MATLAB Function', framesFcnPath, ...
    'Position', [235 320 420 460]);
setMatlabFunctionScript(framesFcnPath, statusCycleFramesScript());
add_line(path, 'Status Payloads From/1', 'Ephorus Status Cycle Frames/1');
for index = 1:numel(ids)
    packName = sprintf('CAN Pack 0x%03X', ids(index));
    packPath = [path '/' packName];
    packBlock = add_block('canlib/CAN Pack', packPath, ...
        'Position', [455, 320 + 40 * (index - 1), 570, 355 + 40 * (index - 1)]);
    set_param(packBlock, 'DataFormat', 'raw data', 'MsgIDType', ...
        'Standard (11-bit identifier)', 'MsgIdentifier', num2str(ids(index)), ...
        'CANIDInput', 'off', 'MsgLength', '8', 'Remote', 'off', ...
        'BusOutput', 'off', 'Description', ...
        sprintf('Packs the real status ID 0x%03X frame', ids(index)));
    add_line(path, sprintf('Ephorus Status Cycle Frames/%d', index), ...
        [packName '/1']);
    % Port 2, not port 1: enableInput above ("Show Transmission Control
    % Input") makes port 1 the Tx Control input (wired from Status Transmit
    % Mask, Fix 4) and moves the CAN_MESSAGE data input this Pack produces
    % to port 2.
    add_line(path, [packName '/1'], ...
        sprintf('CAN Write 0x%03X/2', ids(index)));
end

% Pedal calibration: GUI throttle/brake fractions (0-1) mapped to the four
% redundant IO183 analog-output voltages via the calibrated released/pressed
% endpoints (see INVERTER_HIL_PLAN.MD S3.1: AO01/AO02 = throttle channels
% 1/2, AO03/AO04 = brake channels 1/2). Referenced directly by dictionary
% name (same pattern as ADDGUICOMMANDPARAMETERS) rather than through the
% still-scaffold Pedal Sensor Emulation subsystem, to keep this boundary
% free of new Inports.
throttleRef = addNamedParameterSource(path, 'hil_cmd_pedals_throttle', 470);
brakeRef = addNamedParameterSource(path, 'hil_cmd_pedals_brake', 500);
% XCP source-select: hil_cmd_xcp_pedals_active picks between the GUI-owned
% throttle/brake above (default, active=false) and the new
% hil_cmd_xcp_pedals_throttle/brake tunables (0-100%, normalized to 0-1
% here) once an XCP master sets active=true. Two Switch blocks share one
% control tap from the same Ref block (Simulink signal fan-out), so both
% pedals always agree on which source is live -- see
% virtual-vcu/docs/carmaker_speedgoat_interface.md section 7 item 2.
xcpThrottleRef = addNamedParameterSource(path, 'hil_cmd_xcp_pedals_throttle', 350);
xcpBrakeRef = addNamedParameterSource(path, 'hil_cmd_xcp_pedals_brake', 375);
xcpActiveRef = addNamedParameterSource(path, 'hil_cmd_xcp_pedals_active', 400, 'boolean');
xcpThrottleGain = [path '/XCP Throttle Percent To Fraction'];
add_block('simulink/Math Operations/Gain', xcpThrottleGain, 'Gain', '1/100', ...
    'Position', [185 350 235 370]);
add_line(path, [xcpThrottleRef '/1'], 'XCP Throttle Percent To Fraction/1');
xcpBrakeGain = [path '/XCP Brake Percent To Fraction'];
add_block('simulink/Math Operations/Gain', xcpBrakeGain, 'Gain', '1/100', ...
    'Position', [185 375 235 395]);
add_line(path, [xcpBrakeRef '/1'], 'XCP Brake Percent To Fraction/1');
throttleSwitch = [path '/Throttle Source Switch'];
add_block('simulink/Signal Routing/Switch', throttleSwitch, ...
    'Criteria', 'u2 ~= 0', 'Position', [280 345 330 385]);
add_line(path, 'XCP Throttle Percent To Fraction/1', 'Throttle Source Switch/1');
add_line(path, [xcpActiveRef '/1'], 'Throttle Source Switch/2');
add_line(path, [throttleRef '/1'], 'Throttle Source Switch/3');
brakeSwitch = [path '/Brake Source Switch'];
add_block('simulink/Signal Routing/Switch', brakeSwitch, ...
    'Criteria', 'u2 ~= 0', 'Position', [280 400 330 440]);
add_line(path, 'XCP Brake Percent To Fraction/1', 'Brake Source Switch/1');
add_line(path, [xcpActiveRef '/1'], 'Brake Source Switch/2');
add_line(path, [brakeRef '/1'], 'Brake Source Switch/3');
calRefs = cell(4, 2);
for channel = 1:4
    calRefs{channel, 1} = addNamedParameterSource(path, ...
        sprintf('hil_cal_pedals_released_v%d', channel), 540 + 60 * (channel - 1));
    calRefs{channel, 2} = addNamedParameterSource(path, ...
        sprintf('hil_cal_pedals_pressed_v%d', channel), 570 + 60 * (channel - 1));
end
pedalFcnPath = [path '/Pedal Voltage Calibration'];
add_block('simulink/User-Defined Functions/MATLAB Function', pedalFcnPath, ...
    'Position', [790 460 990 620]);
setMatlabFunctionScript(pedalFcnPath, pedalCalibrationScript());
add_line(path, 'Throttle Source Switch/1', 'Pedal Voltage Calibration/1');
add_line(path, 'Brake Source Switch/1', 'Pedal Voltage Calibration/2');
for channel = 1:4
    add_line(path, [calRefs{channel, 1} '/1'], ...
        sprintf('Pedal Voltage Calibration/%d', 1 + 2 * channel));
    add_line(path, [calRefs{channel, 2} '/1'], ...
        sprintf('Pedal Voltage Calibration/%d', 2 + 2 * channel));
end
for channel = 1:4
    add_line(path, sprintf('Pedal Voltage Calibration/%d', channel), ...
        sprintf('IO183 AO01-AO04 Safe Zero/%d', channel));
end

% VCU digital stimuli: DIO01-04 = PRECH_BTN_IN, MAIN_BTN_IN, COOLING_SW_IN,
% SD_FB_IN per INVERTER_HIL_PLAN.MD S3.2; DIO05-08 (SW_IN_1..4) are
% reserved/unused in the baseline and stay false.
precharRef = addNamedParameterSource(path, ...
    'hil_cmd_digital_precharge_sequence', 630, 'uint32');
prechargeFcnPath = [path '/Precharge Pulse Generator'];
add_block('simulink/User-Defined Functions/MATLAB Function', prechargeFcnPath, ...
    'Position', [790 640 990 700]);
setMatlabFunctionScript(prechargeFcnPath, prechargePulseScript());
add_line(path, [precharRef '/1'], 'Precharge Pulse Generator/1');
add_line(path, 'Precharge Pulse Generator/1', 'IO183 DIO01-DIO08 Safe Zero/1');

% MAIN_BTN_IN is driven by the momentary MainMomentaryButton pulse
% (hil_cmd_digital_main_button_sequence), mirroring PRECH_BTN_IN's
% pulse-on-counter-change pattern above -- a real start button is pressed
% and released, not held. hil_cmd_digital_main_button (the MainButtonSwitch
% checkbox) is intentionally NOT wired to a DIO pin here; it remains a
% valid, addressable SETPARAM target via its Terminator in GUI COMMAND
% PARAMETERS (see ADDGUICOMMANDPARAMETERS), it simply no longer has a
% hardware effect.
mainButtonRef = addNamedParameterSource(path, ...
    'hil_cmd_digital_main_button_sequence', 660, 'uint32');
mainButtonFcnPath = [path '/Main Button Pulse Generator'];
add_block('simulink/User-Defined Functions/MATLAB Function', mainButtonFcnPath, ...
    'Position', [790 710 990 770]);
setMatlabFunctionScript(mainButtonFcnPath, mainButtonPulseScript());
add_line(path, [mainButtonRef '/1'], 'Main Button Pulse Generator/1');
add_line(path, 'Main Button Pulse Generator/1', 'IO183 DIO01-DIO08 Safe Zero/2');
coolingRef = addNamedParameterSource(path, 'hil_cmd_digital_cooling_switch', ...
    690, 'boolean');
coolingCast = addDoubleCast(path, coolingRef, 690);
add_line(path, [coolingCast '/1'], 'IO183 DIO01-DIO08 Safe Zero/3');
shutdownRef = addNamedParameterSource(path, ...
    'hil_cmd_digital_shutdown_feedback', 720, 'boolean');
shutdownCast = addDoubleCast(path, shutdownRef, 720);
add_line(path, [shutdownCast '/1'], 'IO183 DIO01-DIO08 Safe Zero/4');
for channel = 5:8
    swName = sprintf('Unused SW_IN_%d', channel - 4);
    add_block('simulink/Sources/Constant', [path '/' swName], ...
        'Value', '0', 'OutDataTypeStr', 'double', 'SampleTime', '0.001', ...
        'Position', [630, 720 + 30 * channel, 720, 740 + 30 * channel]);
    add_line(path, [swName '/1'], ...
        sprintf('IO183 DIO01-DIO08 Safe Zero/%d', channel));
end

set_param(path, 'Commented', 'off');
end

function name = addNamedParameterSource(path, paramName, y, dataType)
%ADDNAMEDPARAMETERSOURCE Bring a dictionary tunable into a subsystem as a
%signal by naming it as a Constant block's Value (same convention as
%ADDPARAMETERGROUP), so the block resolves and stays live/tunable against
%the data dictionary without needing a workspace lookup inside generated
%code.
if nargin < 4
    dataType = '';
end
name = ['Ref ' paramName];
options = {'Value', paramName, 'SampleTime', '0.001', ...
    'Position', [25 y 155 y + 20]};
if ~isempty(dataType)
    options = [options, {'OutDataTypeStr', dataType}]; %#ok<AGROW>
end
add_block('simulink/Sources/Constant', [path '/' name], options{:});
end

function name = addDoubleCast(path, sourceName, y)
%ADDDOUBLECAST Convert a boolean stimulus to the double the IO183 Digital
%Output ports require, leaving the source Constant's type untouched.
name = ['Cast ' sourceName];
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [path '/' name], 'OutDataTypeStr', 'double', ...
    'Position', [185 y 235 y + 20]);
add_line(path, [sourceName '/1'], [name '/1']);
end

function setMatlabFunctionScript(blockPath, script)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', '-and', 'Path', blockPath);
chart(1).Script = script;
end

function script = rxRetentionScript()
%RXRETENTIONSCRIPT Drain the CAN Read FIFO and retain frames at this
%block's own rate (the CAN Read block's ts, 1 ms -- see BUILDCANINTERFACE).
%The virtual VCU transmits five CAN IDs (the pedal broadcast plus four
%control frames) every 5 ms, 1000 msg/s; a single FIFO pop every 5 ms only
%drains 200 msg/s, so the receive FIFO permanently fell behind and the
%retained command was stale at best and, once the FIFO backed up, simply
%frozen -- frames genuinely sent were never read. Draining at 1 ms matches
%the production rate. EPHORUS STATUS CYCLE (STATUSCYCLESCRIPT) keeps the
%state machine, plant, and CAN-write chain at the original 5 ms rate.
script = sprintf([ ...
    'function rxObservation = ephorusRxRetentionStep( ...\n' ...
    '    rxDataPresent, rxId, rxExtended, rxRemote, rxLength, rxData, ...\n' ...
    '    dropControlMask)\n' ...
    '%%#codegen\n' ...
    '%%EPHORUSRXRETENTIONSTEP Drain one CAN Read FIFO pop per call and\n' ...
    '%%retain it, at this block''s own 1 ms rate. See BUILD_INVERTER_HIL_\n' ...
    '%%MODEL''s RXRETENTIONSCRIPT for why: the virtual VCU''s five CAN IDs\n' ...
    '%%every 5 ms (1000 msg/s) outran a single 5 ms FIFO pop (200 msg/s).\n' ...
    '%%\n' ...
    '%%A frame is ALWAYS passed, with DROP set when nothing was received.\n' ...
    '%%RECEIVECONTROLFRAME rejects a dropped frame without touching the\n' ...
    '%%bank, so the array stays fixed-size for code generation instead of\n' ...
    '%%growing and shrinking. Nothing is fabricated: no data present means\n' ...
    '%%no command retained.\n' ...
    '%%\n' ...
    '%%BANK/STATUSBANK/TICKMS are persistent so retention survives across\n' ...
    '%%calls, exactly as the single combined block this was split out of\n' ...
    '%%used to carry it.\n' ...
    'persistent bank statusBank tickMs\n' ...
    'if isempty(bank)\n' ...
    '    bank = inverterhil.initialDecoderBank();\n' ...
    '    statusBank = inverterhil.initialStatusBank();\n' ...
    '    tickMs = uint32(0);\n' ...
    'end\n' ...
    '%%(:)'' normalises the bus Data element to a 1x8 row regardless of the\n' ...
    '%%orientation Simulink propagates, matching the proven pattern in the\n' ...
    '%%IO614 CAN visibility test decoder.\n' ...
    'payload = uint8(rxData(:))'';\n' ...
    'frame = struct( ...\n' ...
    '    ''id'', uint32(rxId), ...\n' ...
    '    ''dlc'', uint8(rxLength), ...\n' ...
    '    ''payload'', payload, ...\n' ...
    '    ''isExtended'', logical(rxExtended), ...\n' ...
    '    ''isRemote'', logical(rxRemote), ...\n' ...
    '    ''drop'', ~logical(rxDataPresent));\n' ...
    'statusBank = inverterhil.receiveStatusFrame(statusBank, frame, tickMs);\n' ...
    '%%The CAN control-frame drop mask (Fix 4) is applied to a COPY of the\n' ...
    '%%received frame used only for retention -- STATUSBANK above already\n' ...
    '%%saw the unmodified FRAME, so this mask cannot affect the received-\n' ...
    '%%status-frame path, only whether a control frame is retained into the\n' ...
    '%%decoder bank.\n' ...
    'controlFrame = inverterhil.applyControlDropMask(frame, uint8(dropControlMask));\n' ...
    'bank = inverterhil.receiveControlFrame(bank, controlFrame, tickMs);\n' ...
    '%%RXOBSERVATION is taken BEFORE the tick advances, so the ages it\n' ...
    '%%reports are measured against the same tick the frame above was\n' ...
    '%%retained at. Advancing first would make a frame received this step\n' ...
    '%%appear one period old.\n' ...
    'controlRows = inverterhil.rxObservation(bank, tickMs);\n' ...
    'statusRows = inverterhil.statusObservation(statusBank, tickMs);\n' ...
    'rxObservation = zeros(13, 14);\n' ...
    'rxObservation(1:4, :) = controlRows;\n' ...
    'rxObservation(5:13, 1:11) = statusRows;\n' ...
    '%%TICKMS is REAL MILLISECONDS, advanced by 1 per call at this block''s\n' ...
    '%%own 1 ms period. The MOD wrap matches DECODERSNAPSHOT''s rollover-\n' ...
    '%%safe modulo arithmetic; MATLAB uint32 addition otherwise SATURATES\n' ...
    '%%(the generated C++ made that explicit: if (t + 1U < t) { t =\n' ...
    '%%MAX_uint32_T; }) and would freeze the counter at intmax rather than\n' ...
    '%%roll over, which would freeze every retained frame at age 0 forever\n' ...
    '%%and stop command timeouts from firing entirely.\n' ...
    'tickMs = uint32(mod(double(tickMs) + 1, 4294967296));\n' ...
    'end\n']);
end

function script = statusCycleScript()
% PACKSTATUSCYCLE returns a struct (ids/dlc/payloads); only the 9x8 uint8
% PAYLOADS matrix leaves this block, because emitting a bare struct from a
% MATLAB Function block would require a Simulink.Bus definition. The IDs are
% already fixed by the CAN Pack/CAN Write pair for each frame, and the DLC is
% a constant 8, so nothing is lost by dropping them here.
script = sprintf([ ...
    'function [payloads, rxObservationOut, txCount, vehicleState] = ...\n' ...
    '        ephorusSystemStatusStep( ...\n' ...
    '    rxObservation, ...\n' ...
    '    loadNm1, loadNm2, loadNm3, loadNm4, ...\n' ...
    '    connected1, connected2, connected3, connected4, ...\n' ...
    '    dcLink12V, dcLink34V, steeringAngleDeg)\n' ...
    '%%#codegen\n' ...
    '%%EPHORUSSYSTEMSTATUSSTEP Advance the real, persistent-state Ephorus\n' ...
    '%%status cycle (see INVERTERHIL.STEPMODEL) and emit its nine 8-byte\n' ...
    '%%payloads, at the 5 ms status-cycle rate. Single source of truth:\n' ...
    '%%the hardware boundary reads PAYLOADS through a Goto/From pair rather\n' ...
    '%%than recomputing it.\n' ...
    '%%\n' ...
    '%%CAN retention itself now happens upstream in EPHORUS RX RETENTION,\n' ...
    '%%at that block''s own 1 ms rate -- fast enough to keep up with the\n' ...
    '%%virtual VCU''s five-CAN-ID, 5 ms burst, which a single 5 ms FIFO pop\n' ...
    '%%could not drain (see RXRETENTIONSCRIPT). RXOBSERVATION arrives here\n' ...
    '%%as that block''s flattened 13x14 matrix, rate-transitioned down to\n' ...
    '%%this block''s own 5 ms rate (see BUILD_INVERTER_HIL_MODEL''s\n' ...
    '%%BUILDSYSTEMSTATUS). This block was deliberately NOT sped up to 1 ms\n' ...
    '%%itself: doing that once made the whole chain -- state machine,\n' ...
    '%%plant, and the CAN Pack/Write pair this block feeds -- run at 1 ms\n' ...
    '%%too, which collided with the CAN Write blocks'' own explicit 5 ms\n' ...
    '%%rate (see BUILDCANINTERFACE''s CAN Read comment and\n' ...
    '%%TESTMODELARTIFACTS'' io614CanAndOrderedWritesAreExact guard).\n' ...
    '%%Splitting retention out is what lets the FIFO drain fast without\n' ...
    '%%moving the status/torque cadence off its real 5 ms hardware\n' ...
    '%%contract.\n' ...
    '%%\n' ...
    '%%Each channel''s command is re-decoded here from RXOBSERVATION''s own\n' ...
    '%%retained payload bytes with the SAME INVERTERHIL.DECODECONTROLFRAME\n' ...
    '%%the GUI and RXOBSERVATION already use, so this can never disagree\n' ...
    '%%with what the RX table shows.\n' ...
    '%%\n' ...
    '%%BANK persists only for COMMANDOUTOFDOMAIN, which is latched (plan:\n' ...
    '%%once set it stays set until the application restarts) and so cannot\n' ...
    '%%be re-derived from a single RXOBSERVATION snapshot; every other BANK\n' ...
    '%%field is refreshed from RXOBSERVATION below before use. TICKMS here\n' ...
    '%%is a fixed local reference, not a running clock: this block no\n' ...
    '%%longer measures command age itself -- RXOBSERVATION column 11\n' ...
    '%%already carries it, correctly measured against EPHORUS RX\n' ...
    '%%RETENTION''s real 1 ms clock -- so LASTVALIDTICKMS below is set to\n' ...
    '%%make DECODERSNAPSHOT''s own age formula (TICKMS - LASTVALIDTICKMS,\n' ...
    '%%mod 2^32) reproduce that exact value rather than measuring a second,\n' ...
    '%%inconsistent one.\n' ...
    '%%\n' ...
    '%%TXCOUNT is a genuine, target-measured count of status-cycle payloads\n' ...
    '%%this block has emitted -- one real per-call increment, not an\n' ...
    '%%estimate derived from elapsed host time (the CAN Write blocks''\n' ...
    '%%own driver exposes no cumulative transmit counter, so this is the\n' ...
    '%%actual count of cycles this block computed, which in normal\n' ...
    '%%operation, i.e. HIL_CMD_CAN_DROP_STATUS_MASK == 0, is exactly the\n' ...
    '%%count of frames each CAN Write actually sent). Shared across all 9\n' ...
    '%%status IDs since they are packed together every call; a caller\n' ...
    '%%wanting a genuinely independent per-ID count would need one counter\n' ...
    '%%per CAN Write''s own Tx Control gate instead. Held in its own\n' ...
    '%%persistent TXCOUNTER, distinct from the TXCOUNT output variable:\n' ...
    '%%Simulink''s MATLAB Function analysis could not determine output\n' ...
    '%%sizes/types for this block when a single variable was both\n' ...
    '%%persistent and a direct function output.\n' ...
    'persistent state plantState bank txCounter vehicleStateBank\n' ...
    'if isempty(state)\n' ...
    '    state = inverterhil.initialSystemState();\n' ...
    '    plantState = inverterhil.initialPlantState();\n' ...
    '    bank = inverterhil.initialDecoderBank();\n' ...
    '    txCounter = uint32(0);\n' ...
    '    vehicleStateBank = [0 0 0 0];\n' ...
    'end\n' ...
    'tickMs = uint32(0);\n' ...
    'controlIds = inverterhil.protocol().controlIds;\n' ...
    'for channelIndex = 1:4\n' ...
    '    bank.hasCommand(channelIndex) = rxObservation(channelIndex, 9) ~= 0;\n' ...
    '    if bank.hasCommand(channelIndex)\n' ...
    '        framePayload = uint8(rxObservation(channelIndex, 1:8));\n' ...
    '        [~, ~, command] = inverterhil.decodeControlFrame( ...\n' ...
    '            controlIds(channelIndex), uint8(8), framePayload, false, false);\n' ...
    '        bank.commands(channelIndex) = command;\n' ...
    '        ageMs = rxObservation(channelIndex, 11);\n' ...
    '        bank.lastValidTickMs(channelIndex) = ...\n' ...
    '            uint32(mod(double(tickMs) - ageMs, 4294967296));\n' ...
    '    end\n' ...
    'end\n' ...
    '%%EXTERNALINPUTS carries the GUI-commanded per-channel load torque, DC\n' ...
    '%%link pair voltage (dcLink12V feeds channels 1-2, dcLink34V feeds\n' ...
    '%%channels 3-4, matching ADDARCHITECTURE''s dcPort = 1 + (channel > 2)\n' ...
    '%%convention), and connected flag into STEPMODEL -- see\n' ...
    '%%INVERTERHIL.DEFAULTEXTERNALINPUTS for why faultMask is left at its\n' ...
    '%%default (no consumer exists for it yet).\n' ...
    'externalInputs = inverterhil.defaultExternalInputs();\n' ...
    'externalInputs.channels(1).loadTorqueNm = double(loadNm1);\n' ...
    'externalInputs.channels(2).loadTorqueNm = double(loadNm2);\n' ...
    'externalInputs.channels(3).loadTorqueNm = double(loadNm3);\n' ...
    'externalInputs.channels(4).loadTorqueNm = double(loadNm4);\n' ...
    'externalInputs.channels(1).connected = logical(connected1);\n' ...
    'externalInputs.channels(2).connected = logical(connected2);\n' ...
    'externalInputs.channels(3).connected = logical(connected3);\n' ...
    'externalInputs.channels(4).connected = logical(connected4);\n' ...
    'externalInputs.channels(1).dcLinkV = double(dcLink12V);\n' ...
    'externalInputs.channels(2).dcLinkV = double(dcLink12V);\n' ...
    'externalInputs.channels(3).dcLinkV = double(dcLink34V);\n' ...
    'externalInputs.channels(4).dcLinkV = double(dcLink34V);\n' ...
    '%%FRAMES is a single always-dropped frame: retention already happened\n' ...
    '%%upstream in EPHORUS RX RETENTION, so STEPMODEL must not retain\n' ...
    '%%anything a second time here. Its REJECTEDCOUNT/LASTREJECTCODE side\n' ...
    '%%effect on that dropped frame is therefore not this block''s\n' ...
    '%%bookkeeping -- RXOBSERVATIONOUT below carries EPHORUS RX\n' ...
    '%%RETENTION''s own correctly-tracked columns 13-14 straight through\n' ...
    '%%instead. Only COMMANDOUTOFDOMAIN, which STEPMODEL sets as a side\n' ...
    '%%effect of building PLANTINPUT from the freshly-decoded commands\n' ...
    '%%above, is read back from NEXTBANK.\n' ...
    'droppedFrame = struct(''id'', uint32(0), ''dlc'', uint8(0), ...\n' ...
    '    ''payload'', zeros(1, 8, ''uint8''), ''isExtended'', false, ...\n' ...
    '    ''isRemote'', false, ''drop'', true);\n' ...
    '[state, plantState, cycle, ~, plantOutput, nextBank] = inverterhil.stepModel( ...\n' ...
    '    state, plantState, tickMs, inverterhil.defaultStateConfig(), ...\n' ...
    '    inverterhil.defaultCalibration(), bank, droppedFrame, ...\n' ...
    '    externalInputs);\n' ...
    'bank.commandOutOfDomain = nextBank.commandOutOfDomain;\n' ...
    '%%The MTi/LWS observations are sampled from the SAME PLANTOUTPUT this\n' ...
    '%%tick produced, so the sensor frames and the inverter status frames\n' ...
    '%%are observations of one vehicle rather than three unrelated signal\n' ...
    '%%generators. VEHICLESTATE leaves this block on port 4 and reaches the\n' ...
    '%%encoders through the HILSHAREDVEHICLESTATE Goto/From pair.\n' ...
    '[vehicleStateBank, vehicleState] = inverterhil.stepVehicleState( ...\n' ...
    '    vehicleStateBank, plantOutput, double(steeringAngleDeg), ' ...
    num2str(statusPeriodS()) ');\n' ...
    'payloads = cycle.payloads;\n' ...
    'rxObservationOut = rxObservation;\n' ...
    'rxObservationOut(1:4, 12) = double(bank.commandOutOfDomain(:));\n' ...
    'txCounter = uint32(mod(double(txCounter) + 1, 4294967296));\n' ...
    'txCount = txCounter;\n' ...
    'end\n']);
end

function script = sensorPayloadScript()
%SENSORPAYLOADSCRIPT Encode the independent MTi-680G and Bosch LWS frames.
script = sprintf([ ...
    'function [acceleration, rateOfTurn, steering, enableAcceleration, ...\n' ...
    '    enableRateOfTurn, enableSteering] = synchronizedSensorPayloads( ...\n' ...
    '    vehicleState, steeringAngleDeg, imuDropout, steeringDropout)\n' ...
    '%%#codegen\n' ...
    '%%SYNCHRONIZEDSENSORPAYLOADS Encode the independent sensor contracts.\n' ...
    '%%VEHICLESTATE is the 1x6 [ax ay az wx wy wz] observation produced by\n' ...
    '%%the SAME inverter-plant tick (INVERTERHIL.STEPVEHICLESTATE''s second\n' ...
    '%%output), so these frames and the Ephorus status frames describe one\n' ...
    '%%vehicle rather than three unrelated generators.\n' ...
    'persistent phase lastSteeringDeg\n' ...
    'if isempty(phase)\n' ...
    '    phase = uint8(0);\n' ...
    '    lastSteeringDeg = double(steeringAngleDeg);\n' ...
    'end\n' ...
    'angleDeg = double(steeringAngleDeg);\n' ...
    'acceleration = packMti680Payload(''acceleration'', vehicleState(1:3));\n' ...
    'rateOfTurn = packMti680Payload(''rateofturn'', vehicleState(4:6));\n' ...
    '%%LWS_SPEED is the STEERING WHEEL angular speed -- the Bosch datasheet\n' ...
    '%%defines it as "Angular speed", 0 to 1016 deg/s at 4 deg/s resolution,\n' ...
    '%%i.e. the rate of change of LWS_ANGLE. It is NOT the vehicle yaw rate,\n' ...
    '%%which is a different physical quantity on a different sensor (the\n' ...
    '%%MTi rate-of-turn frame above already carries yaw rate). Derived here\n' ...
    '%%from the commanded angle over this block''s own period and clamped\n' ...
    '%%into the encoder range so a fast dial sweep cannot range-error\n' ...
    '%%PACKLWSPAYLOAD.\n' ...
    'speedDegPerS = min(1016, abs(angleDeg - lastSteeringDeg) / ' ...
    num2str(statusPeriodS()) ');\n' ...
    'lastSteeringDeg = angleDeg;\n' ...
    'steering = packLwsPayload(angleDeg, speedDegPerS, uint8(7));\n' ...
    'enableAcceleration = uint32(~logical(imuDropout));\n' ...
    'enableRateOfTurn = enableAcceleration;\n' ...
    '%%The LWS updates at 100 Hz / 10 ms (datasheet "CAN update rate") and\n' ...
    '%%this block runs at the 5 ms status rate, so every second tick\n' ...
    '%%transmits. A dropout is a genuine absence on the wire (Tx Control\n' ...
    '%%low), not a zeroed payload.\n' ...
    'enableSteering = uint32(~logical(steeringDropout) && mod(phase, 2) == 0);\n' ...
    'phase = uint8(mod(double(phase) + 1, 2));\n' ...
    'end\n']);
end

function value = statusPeriodS()
%STATUSPERIODS The Ephorus status-cycle period, in seconds.
%   Single source of truth for every CAN Write 'ts' and the
%   HIL_STATUS_SAMPLE_S dictionary entry. The CAN Read block and
%   EPHORUS RX RETENTION run at the model's 1 ms base rate instead (see
%   BUILDCANINTERFACE's CAN Read comment) -- only the state-machine/
%   plant/CAN-write side of the status cycle, in EPHORUS STATUS CYCLE,
%   still runs at this rate.
value = 0.005;
end

function script = statusCycleFramesScript()
script = sprintf([ ...
    'function [f1,f2,f3,f4,f5,f6,f7,f8,f9] = ephorusStatusCycleFrames(payloads)\n' ...
    '%%EPHORUSSTATUSCYCLEFRAMES Split the nine-frame status cycle into the\n' ...
    '%%nine 1x8 rows the CAN Pack blocks need, one per status ID, in the\n' ...
    '%%order INVERTERHIL.PROTOCOL declares.\n' ...
    'f1 = payloads(1,:); f2 = payloads(2,:); f3 = payloads(3,:);\n' ...
    'f4 = payloads(4,:); f5 = payloads(5,:); f6 = payloads(6,:);\n' ...
    'f7 = payloads(7,:); f8 = payloads(8,:); f9 = payloads(9,:);\n' ...
    'end\n']);
end

function script = statusTransmitMaskScript()
script = sprintf([ ...
    'function [k1,k2,k3,k4,k5,k6,k7,k8,k9] = ...\n' ...
    '    ephorusStatusTransmitMask(dropStatusMask)\n' ...
    '%%#codegen\n' ...
    '%%EPHORUSSTATUSTRANSMITMASK Fix 4: split INVERTERHIL.STATUSTRANSMITMASK''s\n' ...
    '%%9-entry keep vector into nine scalar Tx Control outputs, one per\n' ...
    '%%CAN Write block in INVERTERHIL.PROTOCOL status-cycle order, because\n' ...
    '%%each CAN Write''s Tx Control port takes a scalar and a MATLAB\n' ...
    '%%Function block cannot emit a bus without a Simulink.Bus definition.\n' ...
    '%%\n' ...
    '%%CAN Write''s Tx Control input is uint32 (a transmit-count control, not\n' ...
    '%%a boolean enable), so KEEP is cast rather than passed as logical: 1 to\n' ...
    '%%transmit this tick, 0 to genuinely skip it.\n' ...
    'keep = uint32(inverterhil.statusTransmitMask(dropStatusMask));\n' ...
    'k1 = keep(1); k2 = keep(2); k3 = keep(3);\n' ...
    'k4 = keep(4); k5 = keep(5); k6 = keep(6);\n' ...
    'k7 = keep(7); k8 = keep(8); k9 = keep(9);\n' ...
    'end\n']);
end

function script = pedalCalibrationScript()
script = sprintf([ ...
    'function [ao1,ao2,ao3,ao4] = pedalVoltageCalibration( ...\n' ...
    '    throttle, brake, released1, pressed1, released2, pressed2, ...\n' ...
    '    released3, pressed3, released4, pressed4)\n' ...
    '%%PEDALVOLTAGECALIBRATION Map GUI throttle/brake fractions (0-1) to\n' ...
    '%%the four redundant IO183 analog-output voltages using the\n' ...
    '%%calibrated released/pressed endpoints.\n' ...
    '%%\n' ...
    '%%   HIL_CAL_PEDALS_RELEASED_V*/PRESSED_V* ship as NaN precisely so an\n' ...
    '%%   uncalibrated channel is detectable rather than silently plausible\n' ...
    '%%   (INVERTER_HIL_PLAN.MD S3.1 requires each endpoint be measured at\n' ...
    '%%   the connected VCU pin under load). An uncalibrated or out-of-range\n' ...
    '%%   channel therefore drives 0 V -- the same level the IO183 initial\n' ...
    '%%   and reset values use -- instead of propagating NaN into a DAC.\n' ...
    'ao1 = calibratedVolts(released1, pressed1, throttle);\n' ...
    'ao2 = calibratedVolts(released2, pressed2, throttle);\n' ...
    'ao3 = calibratedVolts(released3, pressed3, brake);\n' ...
    'ao4 = calibratedVolts(released4, pressed4, brake);\n' ...
    'end\n' ...
    '\n' ...
    'function volts = calibratedVolts(releasedV, pressedV, fraction)\n' ...
    'if ~isfinite(releasedV) || ~isfinite(pressedV) || ~isfinite(fraction)\n' ...
    '    volts = 0;\n' ...
    '    return\n' ...
    'end\n' ...
    'bounded = min(max(fraction, 0), 1);\n' ...
    'volts = releasedV + (pressedV - releasedV) * bounded;\n' ...
    '%%The IO183 analog outputs are configured for the 0..5 V range.\n' ...
    'volts = min(max(volts, 0), 5);\n' ...
    'end\n']);
end

function script = prechargePulseScript()
script = sprintf([ ...
    'function active = prechargePulseFromCounter(counter)\n' ...
    '%%PRECHARGEPULSEFROMCOUNTER Turn a GUI counter increment into a\n' ...
    '%%fixed-width PRECH_BTN_IN pulse (INVERTER_HIL_PLAN.MD S7.1: "Model\n' ...
    '%%generates a deterministic precharge pulse on counter change").\n' ...
    '%%200 ms (at the model''s 1 ms base rate) is provisional pending\n' ...
    '%%confirmation against VCU firmware precharge-button timing.\n' ...
    'persistent prevCounter ticksRemaining initialized\n' ...
    'pulseTicks = uint32(200);\n' ...
    'if isempty(initialized)\n' ...
    '    prevCounter = counter;\n' ...
    '    ticksRemaining = uint32(0);\n' ...
    '    initialized = true;\n' ...
    'end\n' ...
    'if counter ~= prevCounter\n' ...
    '    ticksRemaining = pulseTicks;\n' ...
    '    prevCounter = counter;\n' ...
    'end\n' ...
    '%%Emitted as double because that is what the IO183 Digital Output\n' ...
    '%%port takes.\n' ...
    'active = double(ticksRemaining > uint32(0));\n' ...
    'if ticksRemaining > uint32(0)\n' ...
    '    ticksRemaining = ticksRemaining - uint32(1);\n' ...
    'end\n' ...
    'end\n']);
end

function script = mainButtonPulseScript()
script = sprintf([ ...
    'function active = mainButtonPulseFromCounter(counter)\n' ...
    '%%MAINBUTTONPULSEFROMCOUNTER Turn a GUI counter increment into a\n' ...
    '%%fixed-width MAIN_BTN_IN pulse, mirroring\n' ...
    '%%PRECHARGEPULSEFROMCOUNTER''s pulse-on-counter-change pattern: a real\n' ...
    '%%start button is pressed and released, not held. 200 ms (at the\n' ...
    '%%model''s 1 ms base rate) matches the precharge pulse width.\n' ...
    'persistent prevCounter ticksRemaining initialized\n' ...
    'pulseTicks = uint32(200);\n' ...
    'if isempty(initialized)\n' ...
    '    prevCounter = counter;\n' ...
    '    ticksRemaining = uint32(0);\n' ...
    '    initialized = true;\n' ...
    'end\n' ...
    'if counter ~= prevCounter\n' ...
    '    ticksRemaining = pulseTicks;\n' ...
    '    prevCounter = counter;\n' ...
    'end\n' ...
    '%%Emitted as double because that is what the IO183 Digital Output\n' ...
    '%%port takes.\n' ...
    'active = double(ticksRemaining > uint32(0));\n' ...
    'if ticksRemaining > uint32(0)\n' ...
    '    ticksRemaining = ticksRemaining - uint32(1);\n' ...
    'end\n' ...
    'end\n']);
end

function addGuiCommandParameters(model)
%ADDGUICOMMANDPARAMETERS Reference every GUI-owned tunable so it survives
%code generation as an addressable SETPARAM/GETPARAM target.
%
%   +INVERTERHILGUI/PARAMETERCONTRACT.M declares 33 logical names with a flat
%   scalar dictionary backing (plan open decision 16 selected flat scalars;
%   see spikes/decision16/FINDINGS.md). A Simulink.Parameter that no block
%   references is pruned during code generation, so each one here drives a
%   Constant into either a Terminator (a legitimate, permanent signal sink
%   that keeps the block live without implying the GUI value affects channel
%   behavior) or, for the tunables listed in GOTOTAGFOR below, a global Goto
%   that carries the value to a real consumer elsewhere in the model --
%   EPHORUSSTATUSCYCLESCRIPT (Fix 2: load/connected/dc-link) or the hardware
%   boundary's status-frame Tx Control gate (Fix 4: CAN drop masks).
%
%   The pedal, digital-stimulus, and pedal-calibration tunables are also
%   referenced inside the hardware boundary, where they genuinely drive the
%   IO183 analog and digital outputs (see ADDHARDWAREBOUNDARY). Their
%   terminated Constants here are retained so those names still survive code
%   generation when the boundary is commented out. The Goto-routed tunables
%   below do NOT need that same backup: their real consumers (EPHORUS SYSTEM
%   STATUS and its MATLAB Function blocks) live outside the hardware
%   boundary and are unaffected by its Commented flag, so a single Goto here
%   is the only live reference they need. The remaining tunable
%   (per-inverter fault_mask) is still terminated only: no function in
%   +INVERTERHIL/ consumes a per-channel fault-injection bitmask today (see
%   INVERTERHIL.DEFAULTEXTERNALINPUTS), so wiring it would invent behavior
%   that does not exist; left as a documented follow-up.

path = [model '/GUI Command Parameters'];
add_block('simulink/Ports & Subsystems/Subsystem', path, ...
    'Position', [1560 90 1900 480]);
clearSubsystem(path);

scalarDouble = { ...
    'hil_cmd_pedals_throttle'; 'hil_cmd_pedals_brake'; ...
    'hil_cmd_xcp_pedals_throttle'; 'hil_cmd_xcp_pedals_brake'; ...
    'hil_cmd_steering_angle_deg'; ...
    'hil_cmd_dc_link12_v'; 'hil_cmd_dc_link34_v'};
scalarBoolean = { ...
    'hil_cmd_steering_dropout'; 'hil_cmd_imu_dropout'; ...
    'hil_cmd_pedals_plausibility_override'; ...
    'hil_cmd_digital_main_button'; 'hil_cmd_digital_cooling_switch'; ...
    'hil_cmd_digital_shutdown_feedback'; 'hil_cmd_xcp_pedals_active'};
scalarUint32 = { ...
    'hil_cmd_digital_precharge_sequence'; ...
    'hil_cmd_digital_main_button_sequence'; 'hil_cmd_gui_heartbeat'};
scalarUint8 = {'hil_cmd_can_drop_control_mask'};
scalarUint16 = {'hil_cmd_can_drop_status_mask'};
for channel = 1:4
    scalarDouble{end + 1, 1} = sprintf('hil_cmd_inverter%d_load_nm', channel); %#ok<AGROW>
    scalarBoolean{end + 1, 1} = sprintf('hil_cmd_inverter%d_connected', channel); %#ok<AGROW>
    scalarUint32{end + 1, 1} = sprintf('hil_cmd_inverter%d_fault_mask', channel); %#ok<AGROW>
    scalarDouble{end + 1, 1} = sprintf('hil_cal_pedals_released_v%d', channel); %#ok<AGROW>
    scalarDouble{end + 1, 1} = sprintf('hil_cal_pedals_pressed_v%d', channel); %#ok<AGROW>
end

gotoTags = guiCommandGotoTags();

y = 30;
y = addParameterGroup(path, scalarDouble, '', y, gotoTags);
y = addParameterGroup(path, scalarBoolean, 'boolean', y, gotoTags);
y = addParameterGroup(path, scalarUint32, 'uint32', y, gotoTags);
y = addParameterGroup(path, scalarUint8, 'uint8', y, gotoTags);
addParameterGroup(path, scalarUint16, 'uint16', y, gotoTags);
end

function tags = guiCommandGotoTags()
%GUICOMMANDGOTOTAGS Map of GUI Command Parameters tunable name -> global
%Goto tag, for the tunables ADDPARAMETERGROUP routes to a real consumer
%instead of a Terminator (Fix 2 and Fix 4). Any name not a key here keeps
%the original Constant -> Terminator dead-end.
tags = containers.Map('KeyType', 'char', 'ValueType', 'char');
tags('hil_cmd_dc_link12_v') = 'GuiCmdDcLink12V';
tags('hil_cmd_dc_link34_v') = 'GuiCmdDcLink34V';
tags('hil_cmd_can_drop_control_mask') = 'GuiCmdCanDropControlMask';
tags('hil_cmd_can_drop_status_mask') = 'GuiCmdCanDropStatusMask';
tags('hil_cmd_steering_angle_deg') = 'GuiCmdSteeringAngleDeg';
tags('hil_cmd_steering_dropout') = 'GuiCmdSteeringDropout';
tags('hil_cmd_imu_dropout') = 'GuiCmdImuDropout';
for channel = 1:4
    tags(sprintf('hil_cmd_inverter%d_load_nm', channel)) = ...
        sprintf('GuiCmdInverter%dLoadNm', channel);
    tags(sprintf('hil_cmd_inverter%d_connected', channel)) = ...
        sprintf('GuiCmdInverter%dConnected', channel);
end
end

function y = addParameterGroup(path, names, dataType, y, gotoTags)
if nargin < 5
    gotoTags = containers.Map('KeyType', 'char', 'ValueType', 'char');
end
for index = 1:numel(names)
    name = names{index};
    options = {'Value', name, 'SampleTime', '0.001', ...
        'Position', [35 y 165 y + 20]};
    if ~isempty(dataType)
        options = [options, {'OutDataTypeStr', dataType}]; %#ok<AGROW>
    end
    add_block('simulink/Sources/Constant', [path '/Cmd ' name], options{:});
    if isKey(gotoTags, name)
        add_block('simulink/Signal Routing/Goto', [path '/Goto ' name], ...
            'GotoTag', gotoTags(name), 'TagVisibility', 'global', ...
            'Position', [200 y 260 y + 20]);
        add_line(path, ['Cmd ' name '/1'], ['Goto ' name '/1']);
    else
        add_block('simulink/Sinks/Terminator', [path '/Term ' name], ...
            'Position', [200 y 220 y + 20]);
        add_line(path, ['Cmd ' name '/1'], ['Term ' name '/1']);
    end
    y = y + 26;
end
end

function addAnnotation(model, text, position, color)
annotation = Simulink.Annotation(model, text);
annotation.Position = position;
annotation.BackgroundColor = color;
annotation.FontWeight = 'bold';
end

function closeIfLoaded(model)
if bdIsLoaded(model)
    close_system(model, 0);
end
end
